# Generated by Django 5.2.14 on 2026-05-17 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStudentFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_status', models.CharField(choices=[('normal', 'Normal'), ('watch', 'Watch'), ('at_risk', 'At risk'), ('critical', 'Critical')], db_index=True, default='normal', max_length=12, verbose_name='Risk status')),
                ('support_status', models.CharField(blank=True, max_length=40, verbose_name='Support status')),
                ('is_deactivated_by_admin', models.BooleanField(default=False, verbose_name='Deactivated by admin')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_flag', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Platform student flag',
                'verbose_name_plural': 'Platform student flags',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(db_index=True, max_length=80, verbose_name='Action type')),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Object type')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Object ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_logs_targeting', to=settings.AUTH_USER_MODEL, verbose_name='Target user')),
            ],
            options={
                'verbose_name': 'Platform audit log',
                'verbose_name_plural': 'Platform audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='platform_ad_actor_i_f8d2f4_idx'), models.Index(fields=['target_user', '-created_at'], name='platform_ad_target__0382c7_idx'), models.Index(fields=['action_type', '-created_at'], name='platform_ad_action__6333fa_idx'), models.Index(fields=['object_type', 'object_id'], name='platform_ad_object__7beb63_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlatformStudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Note')),
                ('is_private', models.BooleanField(default=False, verbose_name='Private')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_notes_authored', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_notes', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Platform student note',
                'verbose_name_plural': 'Platform student notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='platform_ad_student_f3fc06_idx')],
            },
        ),
    ]
