"""Learning analytics service.

Aggregations over learning_core models for the admin dashboard. All queries
use aggregate / values / count and avoid loading full querysets into memory.
Empty data returns empty lists; never raises.
"""
from __future__ import annotations

from datetime import timedelta
from typing import Any

from django.contrib.auth import get_user_model
from django.db.models import Avg, Count, F, Q, Sum
from django.utils import timezone

from learning_core.models import (
    AdaptiveExercise,
    ExerciseAttempt,
    SkillMastery,
    StudentLearningProfile,
    UserError,
    UserWeakness,
)
from tutor.models import TutorConversation, TutorMessage

User = get_user_model()


def compute_learning_metrics(*, days: int = 30, cefr_level: str | None = None, skill_id: int | None = None) -> dict[str, Any]:
    now = timezone.now()
    horizon = now - timedelta(days=days)

    profiles_qs = StudentLearningProfile.objects.all()
    attempts_qs = ExerciseAttempt.objects.filter(created_at__gte=horizon)
    errors_qs = UserError.objects.filter(created_at__gte=horizon)
    weaknesses_qs = UserWeakness.objects.filter(status="active")
    masteries_qs = SkillMastery.objects.all()

    if cefr_level:
        profiles_qs = profiles_qs.filter(current_cefr_level=cefr_level)
        attempts_qs = attempts_qs.filter(user__learning_profile__current_cefr_level=cefr_level)

    if skill_id:
        masteries_qs = masteries_qs.filter(skill_id=skill_id)
        attempts_qs = attempts_qs.filter(exercise__skill_id=skill_id)
        errors_qs = errors_qs.filter(skill_id=skill_id)
        weaknesses_qs = weaknesses_qs.filter(skill_id=skill_id)

    # 1. Total active learners (any activity in window)
    active_learners = (
        ExerciseAttempt.objects.filter(created_at__gte=horizon).values("user_id").distinct().count()
    )

    # 2. CEFR distribution
    cefr_dist = list(
        StudentLearningProfile.objects.exclude(current_cefr_level="")
        .values("current_cefr_level")
        .annotate(c=Count("id"))
        .order_by("current_cefr_level")
    )

    # 3. Average mastery by skill category
    avg_mastery_by_skill = list(
        masteries_qs.values("skill__category", "skill__name")
        .annotate(avg=Avg("mastery_score"), n=Count("id"))
        .order_by("-avg")[:20]
    )

    # 4. Top grammar weaknesses (by frequency of active weaknesses)
    top_weaknesses = list(
        weaknesses_qs.exclude(grammar_topic__isnull=True)
        .values("grammar_topic__name")
        .annotate(c=Count("id"), avg_priority=Avg("priority_score"))
        .order_by("-avg_priority")[:10]
    )

    # 5. Most common error types
    error_type_breakdown = list(
        errors_qs.values("error_type").annotate(c=Count("id")).order_by("-c")
    )

    # 6. Exercises generated by AI (in window)
    exercises_window = AdaptiveExercise.objects.filter(created_at__gte=horizon)
    exercises_total = exercises_window.count()
    exercises_ai = exercises_window.filter(generated_by_ai=True).count()

    # 7. Exercise success rate
    attempts_total = attempts_qs.count()
    attempts_correct = attempts_qs.filter(is_correct=True).count()
    success_rate = (attempts_correct / attempts_total * 100.0) if attempts_total else 0.0

    # 8. Tutor usage
    tutor_messages = TutorMessage.objects.filter(created_at__gte=horizon).count()
    tutor_conversations = TutorConversation.objects.filter(updated_at__gte=horizon).count()

    # 9. At-risk students: average mastery below 40 OR 0 attempts in window
    at_risk_low_mastery = (
        SkillMastery.objects.values("user_id")
        .annotate(avg=Avg("mastery_score"), n=Count("id"))
        .filter(avg__lt=40.0, n__gte=1)
        .count()
    )
    inactive_users = User.objects.exclude(
        id__in=ExerciseAttempt.objects.filter(created_at__gte=now - timedelta(days=7))
        .values("user_id")
        .distinct()
    ).filter(date_joined__lte=now - timedelta(days=7)).count()

    return {
        "window_days": days,
        "filters": {"cefr_level": cefr_level, "skill_id": skill_id},
        "active_learners": active_learners,
        "cefr_distribution": cefr_dist,
        "avg_mastery_by_skill": avg_mastery_by_skill,
        "top_weaknesses": top_weaknesses,
        "error_type_breakdown": error_type_breakdown,
        "exercises_generated_total": exercises_total,
        "exercises_generated_by_ai": exercises_ai,
        "exercise_success_rate": round(success_rate, 2),
        "exercise_attempts_total": attempts_total,
        "tutor_messages": tutor_messages,
        "tutor_conversations": tutor_conversations,
        "at_risk_low_mastery_users": at_risk_low_mastery,
        "inactive_7d_users": inactive_users,
    }
