# Generated by Django 5.2 on 2026-05-06

from django.db import migrations, models


def seed_methods(apps, schema_editor):
    PaymentMethodAccount = apps.get_model("payments", "PaymentMethodAccount")
    PaymentMethodAccount.objects.get_or_create(
        method="bankak",
        defaults=dict(
            label="Bankak",
            account_number="1234 5678 9012",
            account_holder="Onlenco Sudan",
            sort_order=10,
        ),
    )
    PaymentMethodAccount.objects.get_or_create(
        method="fawry",
        defaults=dict(
            label="Fawry",
            account_number="+249 91 234 5678",
            account_holder="Onlenco Sudan",
            sort_order=20,
        ),
    )
    PaymentMethodAccount.objects.get_or_create(
        method="ocash",
        defaults=dict(
            label="O-Cash",
            account_number="+249 92 876 5432",
            account_holder="Onlenco Sudan",
            sort_order=30,
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethodAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("method", models.CharField(choices=[("bankak", "Bankak"), ("fawry", "Fawry"), ("ocash", "O-Cash")], max_length=10, unique=True)),
                ("label", models.CharField(help_text="Display name, e.g. 'Bankak'", max_length=80)),
                ("account_number", models.CharField(help_text="Account number, IBAN, or phone number to send to.", max_length=80)),
                ("account_holder", models.CharField(default="Onlenco Sudan", help_text="Name on the account.", max_length=120)),
                ("instructions", models.TextField(blank=True, help_text="Optional extra instructions shown under the account info.")),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment method account",
                "verbose_name_plural": "Payment method accounts",
                "ordering": ["sort_order", "method"],
            },
        ),
        migrations.RunPython(seed_methods, reverse_code=migrations.RunPython.noop),
    ]

