# Generated by Django 5.2.14 on 2026-05-07 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentmethodaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsubmission',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymentsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('needs_review', 'Needs admin review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
    ]
