# Generated by Django 5.2.14 on 2026-05-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentsubmission_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentsubmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment submission', 'verbose_name_plural': 'Payment submissions'},
        ),
    ]
