# Generated by Django 5.2.14 on 2026-06-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentsubmission_refund_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsubmission',
            name='platform_earnings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentsubmission',
            name='teacher_earnings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
