"""Seed the placement question bank.

Idempotent: each row keyed by `code`, so re-running the command
upserts text without creating duplicates.

Layout:
  Written  (≥100):
    - 25 intro / personal writing
    - 30 grammar fill-blank / correct-sentence MCQ
    - 25 sentence / paragraph
    - 20 daily / past / future
    - 15 reason / opinion / goal

  Speaking (≥100):
    - 25 name / introduction
    - 25 age / country / nationality
    - 20 work / study / family
    - 15 hobby / free time
    - 15 reason for learning / goal
    - 10 travel / opinion

Each row: bilingual EN/AR text, CEFR range, difficulty 0..1, scoring rubric.
"""
from __future__ import annotations

from django.core.management.base import BaseCommand

from placement.models import PlacementQuestion


# ---------------------------------------------------------------------------
# Question definitions — kept compact: each tuple is (code, en, ar, topic,
# skill, cefr_min, cefr_max, difficulty, expected_answer_type, options).
# `options` is empty list unless expected_answer_type == "mcq".
# ---------------------------------------------------------------------------

WRITTEN_INTRO = [
    ("wr.intro.001", "Write 2 sentences about yourself.",
     "اكتب جملتين عن نفسك.",
     0.15, "short_text"),
    ("wr.intro.002", "Introduce yourself in 3 sentences.",
     "عرّف بنفسك في 3 جمل.",
     0.20, "short_text"),
    ("wr.intro.003", "Write a short paragraph (3-5 sentences) introducing yourself.",
     "اكتب فقرة قصيرة (3-5 جمل) للتعريف بنفسك.",
     0.30, "paragraph"),
    ("wr.intro.004", "Describe your family in 2 sentences.",
     "صف عائلتك في جملتين.",
     0.20, "short_text"),
    ("wr.intro.005", "Where do you live? Write 1 sentence.",
     "أين تعيش؟ اكتب جملة واحدة.",
     0.10, "sentence"),
    ("wr.intro.006", "What is your job or what do you study?",
     "ما هي وظيفتك أو ماذا تدرس؟",
     0.15, "sentence"),
    ("wr.intro.007", "Describe your best friend in 2-3 sentences.",
     "صف أفضل صديق لك في جملتين أو ثلاث.",
     0.30, "short_text"),
    ("wr.intro.008", "Write 2 sentences about your hometown.",
     "اكتب جملتين عن مسقط رأسك.",
     0.25, "short_text"),
    ("wr.intro.009", "What is your favorite food and why?",
     "ما هو طعامك المفضل ولماذا؟",
     0.25, "sentence"),
    ("wr.intro.010", "Describe yourself in three words and explain.",
     "صف نفسك في ثلاث كلمات واشرح.",
     0.35, "short_text"),
    ("wr.intro.011", "Write about a person you admire in 3-4 sentences.",
     "اكتب عن شخص تعجب به في 3-4 جمل.",
     0.40, "paragraph"),
    ("wr.intro.012", "What is your favorite hobby? Write 2 sentences.",
     "ما هي هوايتك المفضلة؟ اكتب جملتين.",
     0.20, "short_text"),
    ("wr.intro.013", "Describe your morning in 3 sentences.",
     "صف صباحك في 3 جمل.",
     0.30, "short_text"),
    ("wr.intro.014", "What languages do you speak?",
     "ما اللغات التي تتحدثها؟",
     0.10, "sentence"),
    ("wr.intro.015", "Write 2 sentences about your country.",
     "اكتب جملتين عن بلدك.",
     0.25, "short_text"),
    ("wr.intro.016", "Describe your house or apartment briefly.",
     "صف منزلك أو شقتك بإيجاز.",
     0.30, "short_text"),
    ("wr.intro.017", "Write 3 sentences about your weekend.",
     "اكتب 3 جمل عن عطلة نهاية الأسبوع.",
     0.30, "short_text"),
    ("wr.intro.018", "What kind of music do you like and why?",
     "ما نوع الموسيقى التي تحبها ولماذا؟",
     0.30, "short_text"),
    ("wr.intro.019", "Describe a typical day in your life.",
     "صف يوماً اعتيادياً في حياتك.",
     0.40, "paragraph"),
    ("wr.intro.020", "Write about your favorite season.",
     "اكتب عن فصلك المفضل في السنة.",
     0.30, "short_text"),
    ("wr.intro.021", "What are your three main hobbies? Explain briefly.",
     "ما هي هواياتك الثلاث الرئيسية؟ اشرح بإيجاز.",
     0.35, "short_text"),
    ("wr.intro.022", "Describe your closest friend and why you like them.",
     "صف أقرب أصدقائك ولماذا تحبه.",
     0.40, "paragraph"),
    ("wr.intro.023", "Where would you like to live in the future?",
     "أين تود أن تعيش في المستقبل؟",
     0.30, "sentence"),
    ("wr.intro.024", "Describe a meal you cooked or ate recently.",
     "صف وجبة طبختها أو تناولتها مؤخراً.",
     0.45, "paragraph"),
    ("wr.intro.025", "Write 4 sentences introducing yourself for a job interview.",
     "اكتب 4 جمل للتعريف بنفسك لمقابلة عمل.",
     0.55, "paragraph"),
]

WRITTEN_GRAMMAR_MCQ = [
    ("wr.grammar.001",
     "Choose the correct option: 'She ___ to school every day.'",
     "اختر الخيار الصحيح: 'She ___ to school every day.'",
     0.15, "mcq",
     ["go", "goes", "going", "gone"]),
    ("wr.grammar.002",
     "Choose the correct option: 'I ___ a book yesterday.'",
     "اختر الصحيح: 'I ___ a book yesterday.'",
     0.20, "mcq",
     ["read", "reads", "reading", "readed"]),
    ("wr.grammar.003",
     "Choose the correct option: 'They ___ playing football now.'",
     "اختر: 'They ___ playing football now.'",
     0.20, "mcq",
     ["is", "are", "am", "be"]),
    ("wr.grammar.004",
     "Choose the correct option: 'He ___ his homework yet.'",
     "اختر: 'He ___ his homework yet.'",
     0.40, "mcq",
     ["didn't finished", "hasn't finished", "doesn't finish", "isn't finishing"]),
    ("wr.grammar.005",
     "Which sentence is correct?",
     "أي الجمل صحيحة؟",
     0.20, "mcq",
     ["She go to school.", "She goes to school.", "She going to school.", "She gone to school."]),
    ("wr.grammar.006",
     "Which sentence is correct?",
     "أي الجمل صحيحة؟",
     0.30, "mcq",
     ["I have ate lunch.", "I has eaten lunch.", "I have eaten lunch.", "I have eated lunch."]),
    ("wr.grammar.007",
     "Choose the correct option: 'There ___ many books on the table.'",
     "اختر: 'There ___ many books on the table.'",
     0.20, "mcq",
     ["is", "are", "be", "was"]),
    ("wr.grammar.008",
     "Choose the correct option: 'If it ___ tomorrow, we will stay home.'",
     "اختر: 'If it ___ tomorrow, we will stay home.'",
     0.45, "mcq",
     ["rains", "rain", "will rain", "rained"]),
    ("wr.grammar.009",
     "Choose the correct option: 'I ___ in London for 5 years.'",
     "اختر: 'I ___ in London for 5 years.'",
     0.50, "mcq",
     ["live", "lived", "have lived", "am living"]),
    ("wr.grammar.010",
     "Choose: 'She is taller ___ her sister.'",
     "اختر: 'She is taller ___ her sister.'",
     0.25, "mcq",
     ["than", "then", "as", "from"]),
    ("wr.grammar.011",
     "Complete: 'Yesterday, I ___ to the market.'",
     "أكمل: 'Yesterday, I ___ to the market.'",
     0.25, "short_text"),
    ("wr.grammar.012",
     "Complete: 'I usually ___ coffee in the morning.'",
     "أكمل: 'I usually ___ coffee in the morning.'",
     0.20, "short_text"),
    ("wr.grammar.013",
     "Complete: 'She ___ been to Egypt before.'",
     "أكمل: 'She ___ been to Egypt before.'",
     0.45, "short_text"),
    ("wr.grammar.014",
     "Complete: 'If I ___ rich, I would travel the world.'",
     "أكمل: 'If I ___ rich, I would travel the world.'",
     0.55, "short_text"),
    ("wr.grammar.015",
     "Complete: 'They ___ here since 2020.'",
     "أكمل: 'They ___ here since 2020.'",
     0.50, "short_text"),
    ("wr.grammar.016",
     "Correct this sentence: 'He don't like coffee.'",
     "صحح هذه الجملة: 'He don't like coffee.'",
     0.20, "sentence"),
    ("wr.grammar.017",
     "Correct: 'She have two cats.'",
     "صحح: 'She have two cats.'",
     0.20, "sentence"),
    ("wr.grammar.018",
     "Correct: 'I no understand this question.'",
     "صحح: 'I no understand this question.'",
     0.25, "sentence"),
    ("wr.grammar.019",
     "Correct: 'Yesterday I go to the beach.'",
     "صحح: 'Yesterday I go to the beach.'",
     0.25, "sentence"),
    ("wr.grammar.020",
     "Correct: 'She is more taller than me.'",
     "صحح: 'She is more taller than me.'",
     0.35, "sentence"),
    ("wr.grammar.021",
     "Correct: 'I am living in Cairo since 2019.'",
     "صحح: 'I am living in Cairo since 2019.'",
     0.55, "sentence"),
    ("wr.grammar.022",
     "Correct: 'He suggested me to study harder.'",
     "صحح: 'He suggested me to study harder.'",
     0.65, "sentence"),
    ("wr.grammar.023",
     "Choose: 'Neither John ___ Mary was at the party.'",
     "اختر: 'Neither John ___ Mary was at the party.'",
     0.55, "mcq",
     ["nor", "or", "and", "but"]),
    ("wr.grammar.024",
     "Choose: 'He looks ___ if he is tired.'",
     "اختر: 'He looks ___ if he is tired.'",
     0.55, "mcq",
     ["like", "as", "such", "than"]),
    ("wr.grammar.025",
     "Choose: 'By next year, she ___ here for a decade.'",
     "اختر: 'By next year, she ___ here for a decade.'",
     0.75, "mcq",
     ["will work", "will have worked", "has worked", "is working"]),
    ("wr.grammar.026",
     "Complete: 'I wish I ___ more time to read.'",
     "أكمل: 'I wish I ___ more time to read.'",
     0.65, "short_text"),
    ("wr.grammar.027",
     "Complete: 'She ___ for the bus when it started raining.'",
     "أكمل: 'She ___ for the bus when it started raining.'",
     0.50, "short_text"),
    ("wr.grammar.028",
     "Choose: 'He didn't tell me ___ he was leaving.'",
     "اختر: 'He didn't tell me ___ he was leaving.'",
     0.55, "mcq",
     ["why", "because", "for", "so"]),
    ("wr.grammar.029",
     "Correct: 'The book what I read was great.'",
     "صحح: 'The book what I read was great.'",
     0.50, "sentence"),
    ("wr.grammar.030",
     "Choose: 'It is high time we ___ home.'",
     "اختر: 'It is high time we ___ home.'",
     0.80, "mcq",
     ["go", "went", "have gone", "had gone"]),
]

WRITTEN_SENTENCE = [
    ("wr.sentence.001", "Write one sentence about your daily routine.",
     "اكتب جملة واحدة عن روتينك اليومي.",
     0.20, "sentence"),
    ("wr.sentence.002", "Write a sentence using the word 'because'.",
     "اكتب جملة باستخدام كلمة 'because'.",
     0.25, "sentence"),
    ("wr.sentence.003", "Write a sentence about what you did last weekend.",
     "اكتب جملة عما فعلته في عطلة نهاية الأسبوع الماضية.",
     0.30, "sentence"),
    ("wr.sentence.004", "Write a sentence about your plans for tomorrow.",
     "اكتب جملة عن خططك ليوم غد.",
     0.30, "sentence"),
    ("wr.sentence.005", "Write a sentence comparing two cities you know.",
     "اكتب جملة تقارن فيها بين مدينتين تعرفهما.",
     0.40, "sentence"),
    ("wr.sentence.006", "Write a sentence using a past tense verb.",
     "اكتب جملة باستخدام فعل في زمن الماضي.",
     0.25, "sentence"),
    ("wr.sentence.007", "Write a question you would ask a new friend.",
     "اكتب سؤالاً قد تطرحه على صديق جديد.",
     0.25, "sentence"),
    ("wr.sentence.008", "Write a sentence describing the weather today.",
     "اكتب جملة تصف الطقس اليوم.",
     0.20, "sentence"),
    ("wr.sentence.009", "Write a sentence about something you want to learn.",
     "اكتب جملة عن شيء تود تعلمه.",
     0.30, "sentence"),
    ("wr.sentence.010", "Write a sentence using the word 'although'.",
     "اكتب جملة باستخدام كلمة 'although'.",
     0.45, "sentence"),
    ("wr.sentence.011", "Write a paragraph (4 sentences) about a memorable trip.",
     "اكتب فقرة (4 جمل) عن رحلة لا تنسى.",
     0.50, "paragraph"),
    ("wr.sentence.012", "Write a paragraph about your favorite movie.",
     "اكتب فقرة عن فيلمك المفضل.",
     0.40, "paragraph"),
    ("wr.sentence.013", "Write a short paragraph about your school or workplace.",
     "اكتب فقرة قصيرة عن مدرستك أو مكان عملك.",
     0.40, "paragraph"),
    ("wr.sentence.014", "Write 4-5 sentences about a typical evening.",
     "اكتب 4-5 جمل عن مساء اعتيادي.",
     0.40, "paragraph"),
    ("wr.sentence.015", "Write a paragraph about a problem you solved.",
     "اكتب فقرة عن مشكلة قمت بحلها.",
     0.55, "paragraph"),
    ("wr.sentence.016", "Write 5 sentences about the place you grew up in.",
     "اكتب 5 جمل عن المكان الذي نشأت فيه.",
     0.50, "paragraph"),
    ("wr.sentence.017", "Write a paragraph imagining your perfect day.",
     "اكتب فقرة تتخيل فيها يومك المثالي.",
     0.55, "paragraph"),
    ("wr.sentence.018", "Write 5 sentences comparing life now vs 10 years ago.",
     "اكتب 5 جمل تقارن فيها الحياة اليوم بمنذ 10 سنوات.",
     0.65, "paragraph"),
    ("wr.sentence.019", "Write a paragraph about a person who influenced you.",
     "اكتب فقرة عن شخص أثّر فيك.",
     0.55, "paragraph"),
    ("wr.sentence.020", "Write a paragraph describing a busy market.",
     "اكتب فقرة تصف سوقاً مزدحماً.",
     0.60, "paragraph"),
    ("wr.sentence.021", "Write 5 sentences about a difficult decision.",
     "اكتب 5 جمل عن قرار صعب.",
     0.65, "paragraph"),
    ("wr.sentence.022", "Write a paragraph arguing for or against working from home.",
     "اكتب فقرة تؤيد أو تعارض العمل من المنزل.",
     0.70, "paragraph"),
    ("wr.sentence.023", "Write a 6-sentence paragraph about a recent news story.",
     "اكتب فقرة من 6 جمل عن خبر حديث.",
     0.75, "paragraph"),
    ("wr.sentence.024", "Write a paragraph about how technology changes education.",
     "اكتب فقرة عن كيف تغيّر التكنولوجيا التعليم.",
     0.80, "paragraph"),
    ("wr.sentence.025", "Write a paragraph about cultural differences you've experienced.",
     "اكتب فقرة عن الفروق الثقافية التي عايشتها.",
     0.80, "paragraph"),
]

WRITTEN_DAILY = [
    ("wr.daily.001", "What did you do yesterday? Write 3 sentences.",
     "ماذا فعلت أمس؟ اكتب 3 جمل.",
     0.30, "short_text"),
    ("wr.daily.002", "What will you do tomorrow? Write 3 sentences.",
     "ماذا ستفعل غداً؟ اكتب 3 جمل.",
     0.30, "short_text"),
    ("wr.daily.003", "Describe your daily routine in 4-5 sentences.",
     "صف روتينك اليومي في 4-5 جمل.",
     0.40, "paragraph"),
    ("wr.daily.004", "Where were you last weekend? Describe briefly.",
     "أين كنت في عطلة نهاية الأسبوع الماضية؟ صف بإيجاز.",
     0.30, "short_text"),
    ("wr.daily.005", "What is your plan for next month?",
     "ما خطتك للشهر القادم؟",
     0.35, "short_text"),
    ("wr.daily.006", "Describe what you usually do after work or school.",
     "صف ما تفعله عادةً بعد العمل أو المدرسة.",
     0.35, "short_text"),
    ("wr.daily.007", "Write about a habit you want to change.",
     "اكتب عن عادة تريد تغييرها.",
     0.45, "short_text"),
    ("wr.daily.008", "Tell me about a holiday you took recently.",
     "أخبرني عن إجازة قضيتها مؤخراً.",
     0.45, "paragraph"),
    ("wr.daily.009", "Describe your morning ritual in 3-4 sentences.",
     "صف طقسك الصباحي في 3-4 جمل.",
     0.40, "short_text"),
    ("wr.daily.010", "What is something you do every Friday?",
     "ما الذي تفعله كل يوم جمعة؟",
     0.30, "sentence"),
    ("wr.daily.011", "Write about your last birthday.",
     "اكتب عن آخر عيد ميلاد لك.",
     0.45, "paragraph"),
    ("wr.daily.012", "Describe a typical lunch break.",
     "صف فترة استراحة غداء اعتيادية.",
     0.35, "short_text"),
    ("wr.daily.013", "What did you learn last week?",
     "ماذا تعلمت الأسبوع الماضي؟",
     0.40, "short_text"),
    ("wr.daily.014", "Write about something you achieved last year.",
     "اكتب عن إنجاز حققته العام الماضي.",
     0.50, "paragraph"),
    ("wr.daily.015", "Describe how you plan to spend the next holiday.",
     "صف كيف تنوي قضاء الإجازة القادمة.",
     0.50, "paragraph"),
    ("wr.daily.016", "What is your goal for this year?",
     "ما هدفك لهذا العام؟",
     0.40, "short_text"),
    ("wr.daily.017", "Write about a time you helped someone.",
     "اكتب عن مرة ساعدت فيها شخصاً.",
     0.50, "paragraph"),
    ("wr.daily.018", "Describe a hobby you started recently.",
     "صف هواية بدأتها مؤخراً.",
     0.40, "paragraph"),
    ("wr.daily.019", "What is the most interesting thing you did this month?",
     "ما أكثر شيء مثير قمت به هذا الشهر؟",
     0.45, "paragraph"),
    ("wr.daily.020", "Describe how your week usually goes.",
     "صف كيف يمر أسبوعك عادة.",
     0.45, "paragraph"),
]

WRITTEN_REASON = [
    ("wr.reason.001", "Why do you want to learn English? Write 2-3 sentences.",
     "لماذا تريد تعلم الإنجليزية؟ اكتب 2-3 جمل.",
     0.30, "short_text"),
    ("wr.reason.002", "What is the most important benefit of speaking English?",
     "ما أهم فائدة من تحدث الإنجليزية؟",
     0.40, "short_text"),
    ("wr.reason.003", "Do you prefer studying alone or in a group? Why?",
     "هل تفضل الدراسة بمفردك أم في مجموعة؟ ولماذا؟",
     0.40, "short_text"),
    ("wr.reason.004", "What is your biggest goal for learning English?",
     "ما أكبر هدف لك من تعلم الإنجليزية؟",
     0.35, "short_text"),
    ("wr.reason.005", "Should children learn a foreign language? Why?",
     "هل ينبغي للأطفال تعلم لغة أجنبية؟ ولماذا؟",
     0.50, "paragraph"),
    ("wr.reason.006", "Is it better to live in a city or a village? Explain.",
     "هل من الأفضل العيش في المدينة أم القرية؟ اشرح.",
     0.55, "paragraph"),
    ("wr.reason.007", "What is one thing you would change about your country?",
     "ما الشيء الذي تود تغييره في بلدك؟",
     0.55, "paragraph"),
    ("wr.reason.008", "Should students study online? Why or why not?",
     "هل ينبغي للطلاب الدراسة عبر الإنترنت؟ ولماذا؟",
     0.60, "paragraph"),
    ("wr.reason.009", "Why is it good to travel?",
     "لماذا من الجيد السفر؟",
     0.40, "short_text"),
    ("wr.reason.010", "Do you think social media has more positive or negative effects?",
     "هل ترى أن لوسائل التواصل آثاراً إيجابية أكثر أم سلبية؟",
     0.65, "paragraph"),
    ("wr.reason.011", "What advice would you give to someone learning English?",
     "ما النصيحة التي تقدمها لشخص يتعلم الإنجليزية؟",
     0.55, "paragraph"),
    ("wr.reason.012", "Is it important to read books? Why?",
     "هل من المهم قراءة الكتب؟ ولماذا؟",
     0.45, "paragraph"),
    ("wr.reason.013", "Why is exercise important?",
     "لماذا التمرين مهم؟",
     0.35, "short_text"),
    ("wr.reason.014", "Do you think money brings happiness? Explain.",
     "هل تعتقد أن المال يجلب السعادة؟ اشرح.",
     0.65, "paragraph"),
    ("wr.reason.015", "What is the best way to learn a new skill?",
     "ما أفضل طريقة لتعلم مهارة جديدة؟",
     0.55, "paragraph"),
]

# ---------------------------------------------------------------------------
# Speaking — voice answer captured by the browser, transcribed server-side.
# ---------------------------------------------------------------------------

SPEAKING_NAME = [
    ("sp.name.001", "What is your name?",                       "ما اسمك؟",                    0.05),
    ("sp.name.002", "Can you introduce yourself?",              "هل يمكنك تعريف نفسك؟",        0.20),
    ("sp.name.003", "Tell me your full name and where you're from.",
     "أخبرني باسمك الكامل ومن أين أنت.",                                                       0.20),
    ("sp.name.004", "What should I call you?",                  "بماذا أناديك؟",               0.10),
    ("sp.name.005", "Spell your name for me, please.",          "اهجِ اسمك من فضلك.",           0.15),
    ("sp.name.006", "How do you write your name in English?",   "كيف تكتب اسمك بالإنجليزية؟",  0.20),
    ("sp.name.007", "Introduce yourself in 3 sentences.",       "عرّف نفسك في 3 جمل.",          0.30),
    ("sp.name.008", "What does your name mean?",                "ما معنى اسمك؟",               0.30),
    ("sp.name.009", "Did your parents choose your name? Why?",  "هل اختار والداك اسمك؟ ولماذا؟",0.40),
    ("sp.name.010", "If you could change your name, would you?","لو استطعت تغيير اسمك، هل ستفعل؟",0.45),
    ("sp.name.011", "Have you got any nicknames? Tell me.",     "هل لديك ألقاب؟ أخبرني.",       0.35),
    ("sp.name.012", "Tell me one interesting thing about you.", "أخبرني بشيء مثير عنك.",        0.45),
    ("sp.name.013", "How would your friends describe you?",     "كيف يصفك أصدقاؤك؟",            0.45),
    ("sp.name.014", "What three words describe you best?",      "ما الكلمات الثلاث التي تصفك أفضل؟",0.40),
    ("sp.name.015", "Tell me a little about your background.",  "أخبرني قليلاً عن خلفيتك.",      0.50),
    ("sp.name.016", "What kind of person are you?",             "أي نوع من الأشخاص أنت؟",        0.50),
    ("sp.name.017", "Where did you grow up?",                   "أين نشأت؟",                    0.30),
    ("sp.name.018", "Tell me about your family briefly.",       "أخبرني عن عائلتك بإيجاز.",      0.30),
    ("sp.name.019", "Are you the oldest, middle, or youngest in your family?",
     "هل أنت الأكبر أم الأوسط أم الأصغر في عائلتك؟",                                            0.35),
    ("sp.name.020", "How many people are in your family?",      "كم شخصاً في عائلتك؟",           0.20),
    ("sp.name.021", "Describe yourself in one short paragraph.","صف نفسك في فقرة قصيرة.",       0.55),
    ("sp.name.022", "What's something most people don't know about you?",
     "ما الشيء الذي لا يعرفه معظم الناس عنك؟",                                                  0.55),
    ("sp.name.023", "Are you a quiet or talkative person? Why?","هل أنت شخص هادئ أم كثير الحديث؟",0.45),
    ("sp.name.024", "Tell me about your closest friend.",       "أخبرني عن أقرب أصدقائك.",       0.45),
    ("sp.name.025", "What do you and your friends usually do?", "ماذا تفعل أنت وأصدقاؤك عادة؟",  0.40),
]

SPEAKING_AGE_COUNTRY = [
    ("sp.age.001", "How old are you?",                          "كم عمرك؟",                     0.05),
    ("sp.age.002", "Where are you from?",                       "من أين أنت؟",                  0.05),
    ("sp.age.003", "What is your nationality?",                 "ما جنسيتك؟",                   0.10),
    ("sp.age.004", "What country do you live in?",              "في أي بلد تعيش؟",              0.10),
    ("sp.age.005", "What city are you from?",                   "من أي مدينة أنت؟",             0.10),
    ("sp.age.006", "Tell me about your hometown.",              "أخبرني عن مسقط رأسك.",          0.30),
    ("sp.age.007", "When is your birthday?",                    "متى عيد ميلادك؟",              0.15),
    ("sp.age.008", "What is famous in your country?",           "ما المشهور في بلدك؟",           0.30),
    ("sp.age.009", "What is the weather like in your country?", "كيف الطقس في بلدك؟",            0.30),
    ("sp.age.010", "Describe your country in 3 sentences.",     "صف بلدك في 3 جمل.",             0.40),
    ("sp.age.011", "What language is spoken in your country?",  "ما اللغة المتحدث بها في بلدك؟", 0.20),
    ("sp.age.012", "How big is your city?",                     "ما حجم مدينتك؟",               0.30),
    ("sp.age.013", "Have you lived anywhere else?",             "هل عشت في أي مكان آخر؟",        0.40),
    ("sp.age.014", "What do you like about your country?",      "ما الذي يعجبك في بلدك؟",         0.40),
    ("sp.age.015", "What food is your country famous for?",     "ما الطعام الذي اشتهر به بلدك؟", 0.40),
    ("sp.age.016", "Describe a popular festival in your country.","صف عيداً مشهوراً في بلدك.",   0.50),
    ("sp.age.017", "What's a tradition in your culture you love?","ما تقليد في ثقافتك تحبه؟",    0.55),
    ("sp.age.018", "Tell me about a famous landmark.",          "أخبرني عن معلم مشهور.",          0.45),
    ("sp.age.019", "What's a common dish you grew up eating?",  "ما طبق شائع نشأت على تناوله؟",  0.45),
    ("sp.age.020", "Describe the geography of your region.",    "صف جغرافية منطقتك.",            0.55),
    ("sp.age.021", "Compare summer and winter in your country.","قارن الصيف والشتاء في بلدك.",  0.55),
    ("sp.age.022", "What's the population of your city, roughly?","كم تعداد مدينتك تقريباً؟",   0.45),
    ("sp.age.023", "If a tourist visits your country, what should they see?",
     "إذا زار سائحٌ بلدك، فماذا ينبغي أن يرى؟",                                                  0.55),
    ("sp.age.024", "How is life in your city different from a big city?",
     "كيف تختلف الحياة في مدينتك عن مدينة كبيرة؟",                                              0.65),
    ("sp.age.025", "Describe a typical day in your culture.",   "صف يوماً اعتيادياً في ثقافتك.", 0.60),
]

SPEAKING_WORK_STUDY = [
    ("sp.work.001", "What do you do?",                          "ماذا تعمل؟",                   0.10),
    ("sp.work.002", "Do you work or study?",                    "هل تعمل أم تدرس؟",             0.10),
    ("sp.work.003", "What is your job?",                        "ما وظيفتك؟",                   0.10),
    ("sp.work.004", "Where do you work?",                       "أين تعمل؟",                   0.15),
    ("sp.work.005", "Tell me about a typical day at work or school.",
     "أخبرني عن يوم اعتيادي في العمل أو المدرسة.",                                              0.45),
    ("sp.work.006", "What subject do you study?",               "ما المادة التي تدرسها؟",       0.20),
    ("sp.work.007", "Why did you choose your job?",             "لماذا اخترت وظيفتك؟",          0.45),
    ("sp.work.008", "What do you like about your work?",        "ما الذي يعجبك في عملك؟",        0.40),
    ("sp.work.009", "What is difficult about your job?",        "ما الصعب في وظيفتك؟",           0.50),
    ("sp.work.010", "What's your dream job?",                   "ما وظيفة أحلامك؟",             0.40),
    ("sp.work.011", "Tell me about your colleagues.",           "أخبرني عن زملائك.",            0.45),
    ("sp.work.012", "What are your skills?",                    "ما مهاراتك؟",                 0.40),
    ("sp.work.013", "Have you worked from home? Did you like it?","هل عملت من المنزل؟ هل أعجبك؟",0.50),
    ("sp.work.014", "Describe your education path.",            "صف مسارك التعليمي.",            0.55),
    ("sp.work.015", "What do you want to do in 5 years?",       "ماذا تريد أن تفعل خلال 5 سنوات؟",0.55),
    ("sp.work.016", "How is technology changing your job?",     "كيف تغيّر التكنولوجيا وظيفتك؟", 0.65),
    ("sp.work.017", "Tell me about a project you completed.",   "أخبرني عن مشروع أنجزته.",       0.55),
    ("sp.work.018", "What's the best advice your boss gave you?","ما أفضل نصيحة قدمها لك مديرك؟",0.55),
    ("sp.work.019", "Have you ever done volunteer work?",       "هل قمت بعمل تطوعي من قبل؟",     0.45),
    ("sp.work.020", "Describe a workplace challenge.",          "صف تحدياً في مكان العمل.",       0.65),
]

SPEAKING_HOBBY = [
    ("sp.hobby.001", "What do you do in your free time?",       "ماذا تفعل في وقت فراغك؟",      0.20),
    ("sp.hobby.002", "What are your hobbies?",                  "ما هواياتك؟",                  0.20),
    ("sp.hobby.003", "Do you play any sports?",                 "هل تمارس أي رياضة؟",            0.20),
    ("sp.hobby.004", "Do you like reading? What kind of books?","هل تحب القراءة؟ أي نوع من الكتب؟",0.30),
    ("sp.hobby.005", "What music do you listen to?",            "ما الموسيقى التي تستمع إليها؟", 0.25),
    ("sp.hobby.006", "Do you like watching films? Tell me about your favorite.",
     "هل تحب مشاهدة الأفلام؟ أخبرني عن المفضل لديك.",                                            0.40),
    ("sp.hobby.007", "What do you do on weekends?",             "ماذا تفعل في عطلات نهاية الأسبوع؟",0.30),
    ("sp.hobby.008", "Do you cook? What's your favorite dish to make?",
     "هل تطبخ؟ ما طبقك المفضل لتحضيره؟",                                                       0.40),
    ("sp.hobby.009", "Have you ever played a musical instrument?","هل سبق أن عزفت على آلة موسيقية؟",0.45),
    ("sp.hobby.010", "Do you prefer the city or the countryside?","هل تفضل المدينة أم الريف؟",  0.40),
    ("sp.hobby.011", "What's a hobby you'd like to start?",     "ما هواية تود البدء بها؟",       0.45),
    ("sp.hobby.012", "Describe the last thing you watched on TV.","صف آخر شيء شاهدته على التلفاز.",0.50),
    ("sp.hobby.013", "What's something you collect?",           "ما الشيء الذي تجمعه؟",          0.45),
    ("sp.hobby.014", "Do you prefer indoor or outdoor activities?","هل تفضل الأنشطة الداخلية أم الخارجية؟",0.40),
    ("sp.hobby.015", "Tell me about a hobby you've had since childhood.",
     "أخبرني عن هواية تمارسها منذ الطفولة.",                                                    0.55),
]

SPEAKING_REASON = [
    ("sp.reason.001", "Why do you want to learn English?",      "لماذا تريد تعلم الإنجليزية؟",   0.20),
    ("sp.reason.002", "How will English help your career?",     "كيف ستساعدك الإنجليزية في مسارك المهني؟",0.40),
    ("sp.reason.003", "What's your goal in 6 months?",          "ما هدفك خلال 6 أشهر؟",          0.35),
    ("sp.reason.004", "Where do you want to use English most?", "أين تريد استخدام الإنجليزية أكثر؟",0.35),
    ("sp.reason.005", "What do you find difficult about learning English?",
     "ما الذي تجده صعباً في تعلم الإنجليزية؟",                                                  0.45),
    ("sp.reason.006", "How do you usually practise English?",   "كيف تتدرب على الإنجليزية عادة؟",0.40),
    ("sp.reason.007", "Have you visited any English-speaking country?",
     "هل زرت بلداً ناطقاً بالإنجليزية؟",                                                        0.40),
    ("sp.reason.008", "Tell me about a teacher who inspired you.","أخبرني عن معلم ألهمك.",       0.50),
    ("sp.reason.009", "What's your biggest English-learning win?","ما أكبر إنجاز لك في تعلم الإنجليزية؟",0.50),
    ("sp.reason.010", "Why is it important to speak more than one language?",
     "لماذا من المهم تحدث أكثر من لغة؟",                                                        0.55),
    ("sp.reason.011", "What's harder for you, listening or speaking?",
     "أيهما أصعب لك، الاستماع أم التحدث؟",                                                     0.45),
    ("sp.reason.012", "How will you celebrate when you reach C1 level?",
     "كيف ستحتفل عند الوصول إلى مستوى C1؟",                                                    0.50),
    ("sp.reason.013", "Tell me about a time English helped you.",
     "أخبرني عن مرة ساعدتك فيها الإنجليزية.",                                                  0.50),
    ("sp.reason.014", "What's one thing you'll do this week to improve your English?",
     "ما الشيء الذي ستفعله هذا الأسبوع لتحسين إنجليزيتك؟",                                      0.45),
    ("sp.reason.015", "If you could speak any other language, which one and why?",
     "لو استطعت تحدث لغة أخرى، فأيها ولماذا؟",                                                  0.55),
]

SPEAKING_TRAVEL = [
    ("sp.travel.001", "Have you travelled recently?",           "هل سافرت مؤخراً؟",              0.30),
    ("sp.travel.002", "Tell me about your favorite trip.",      "أخبرني عن رحلتك المفضلة.",      0.40),
    ("sp.travel.003", "Where would you love to visit one day?", "أين تود الزيارة يوماً ما؟",     0.35),
    ("sp.travel.004", "Do you prefer the beach or the mountains?","هل تفضل الشاطئ أم الجبال؟",  0.30),
    ("sp.travel.005", "What's the best way to explore a new city?","ما أفضل طريقة لاستكشاف مدينة جديدة؟",0.50),
    ("sp.travel.006", "Tell me about a holiday that didn't go as planned.",
     "أخبرني عن إجازة لم تسر كما خططت.",                                                      0.55),
    ("sp.travel.007", "Do you prefer travelling alone or with others?","هل تفضل السفر منفرداً أم برفقة آخرين؟",0.45),
    ("sp.travel.008", "What's the strangest food you've tried?", "ما أغرب طعام جرّبته؟",         0.55),
    ("sp.travel.009", "What do you pack first when travelling?",  "ما الشيء الذي تحزمه أولاً عند السفر؟",0.40),
    ("sp.travel.010", "Has travel ever changed your view of something?",
     "هل غيّر السفر يوماً نظرتك إلى شيء؟",                                                     0.65),
]

# ---------------------------------------------------------------------------
# Topic → list mapping. Skill is inferred from question_type / topic.
# ---------------------------------------------------------------------------

WRITTEN_BUCKETS = [
    ("intro",       "writing", WRITTEN_INTRO),
    ("grammar_fix", "grammar", WRITTEN_GRAMMAR_MCQ),
    ("sentence",    "writing", WRITTEN_SENTENCE),
    ("daily",       "writing", WRITTEN_DAILY),
    ("reason",      "writing", WRITTEN_REASON),
]

SPEAKING_BUCKETS = [
    ("name",        "speaking", SPEAKING_NAME),
    ("age_country", "speaking", SPEAKING_AGE_COUNTRY),
    ("work_study",  "speaking", SPEAKING_WORK_STUDY),
    ("hobby",       "speaking", SPEAKING_HOBBY),
    ("reason",      "speaking", SPEAKING_REASON),
    ("travel",      "speaking", SPEAKING_TRAVEL),
]


def _cefr_band(diff: float) -> tuple[str, str]:
    """Map difficulty 0..1 to a CEFR (min, max) band."""
    if diff < 0.20:
        return ("A0", "A1")
    if diff < 0.35:
        return ("A1", "A2")
    if diff < 0.55:
        return ("A2", "B1")
    if diff < 0.70:
        return ("B1", "B2")
    if diff < 0.85:
        return ("B2", "C1")
    return ("C1", "C2")


class Command(BaseCommand):
    help = "Seed the placement question bank (≥100 written + ≥100 speaking)."

    def handle(self, *args, **opts):
        written = self._seed_written()
        speaking = self._seed_speaking()
        total = written + speaking
        self.stdout.write(self.style.SUCCESS(
            f"Placement bank: written={written} speaking={speaking} total={total}"
        ))

    def _seed_written(self) -> int:
        upserted = 0
        for topic, skill, items in WRITTEN_BUCKETS:
            for item in items:
                if len(item) == 6:
                    code, en, ar, diff, answer_type, options = item
                else:
                    code, en, ar, diff, answer_type = item
                    options = []
                cefr_min, cefr_max = _cefr_band(diff)
                PlacementQuestion.objects.update_or_create(
                    code=code,
                    defaults={
                        "question_text": en,
                        "question_text_ar": ar,
                        "question_type": "written",
                        "skill": skill if answer_type != "mcq" else "grammar",
                        "topic": topic,
                        "cefr_min_level": cefr_min,
                        "cefr_max_level": cefr_max,
                        "difficulty_score": diff,
                        "expected_answer_type": answer_type,
                        "options": options,
                        "is_active": True,
                    },
                )
                upserted += 1
        return upserted

    def _seed_speaking(self) -> int:
        upserted = 0
        for topic, skill, items in SPEAKING_BUCKETS:
            for code, en, ar, diff in items:
                cefr_min, cefr_max = _cefr_band(diff)
                PlacementQuestion.objects.update_or_create(
                    code=code,
                    defaults={
                        "question_text": en,
                        "question_text_ar": ar,
                        "question_type": "speaking",
                        "skill": skill,
                        "topic": topic,
                        "cefr_min_level": cefr_min,
                        "cefr_max_level": cefr_max,
                        "difficulty_score": diff,
                        "expected_answer_type": "voice",
                        "options": [],
                        "is_active": True,
                    },
                )
                upserted += 1
        return upserted
