# Generated by Django 5.2.14 on 2026-05-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_alter_placementresult_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementresult',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='placement/audio/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='placementresult',
            name='audio_duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='placementresult',
            name='audio_transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='placementresult',
            name='fluency_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementresult',
            name='pronunciation_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
