# Generated by Django 5.2.14 on 2026-05-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_placementresult_audio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placementresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Placement result', 'verbose_name_plural': 'Placement results'},
        ),
    ]
