# Generated by Django 5.2.14 on 2026-05-09 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_alter_placementresult_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('written_completed', 'Written completed'), ('speaking_completed', 'Speaking completed'), ('completed', 'Completed')], default='started', max_length=20)),
                ('written_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('speaking_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('overall_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recommended_cefr_level', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], max_length=2)),
                ('feedback', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.ForeignKey(blank=True, help_text='Linked PlacementResult once scoring completes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='placement.placementresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Placement attempt',
                'verbose_name_plural': 'Placement attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Stable identifier — used by the seeder for idempotency.', max_length=80, unique=True)),
                ('question_text', models.TextField(verbose_name='Question (English)')),
                ('question_text_ar', models.TextField(blank=True, help_text='Optional. Falls back to English if blank.', verbose_name='Question (Arabic)')),
                ('question_type', models.CharField(choices=[('written', 'Written'), ('speaking', 'Speaking')], db_index=True, max_length=12, verbose_name='Question type')),
                ('skill', models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('writing', 'Writing'), ('speaking', 'Speaking'), ('fluency', 'Fluency'), ('comprehension', 'Comprehension')], db_index=True, max_length=20, verbose_name='Skill')),
                ('topic', models.CharField(blank=True, choices=[('intro', 'Introduction / personal'), ('grammar_fix', 'Grammar fill-blank / correct'), ('sentence', 'Sentence / paragraph'), ('daily', 'Daily routine / past / future'), ('reason', 'Reason / opinion / goal'), ('name', 'Name / introduction'), ('age_country', 'Age / country / nationality'), ('work_study', 'Work / study / family'), ('hobby', 'Hobby / free time'), ('travel', 'Travel / opinion')], db_index=True, max_length=20, verbose_name='Topic bucket')),
                ('cefr_min_level', models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], default='A0', max_length=2, verbose_name='CEFR min level')),
                ('cefr_max_level', models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], default='C2', max_length=2, verbose_name='CEFR max level')),
                ('difficulty_score', models.FloatField(default=0.5, help_text='0 = trivial A0, 1 = C2 advanced.', verbose_name='Difficulty (0..1)')),
                ('expected_answer_type', models.CharField(choices=[('short_text', 'Short text'), ('sentence', 'Sentence'), ('paragraph', 'Paragraph'), ('voice', 'Voice / transcript'), ('mcq', 'Multiple choice')], default='sentence', max_length=12, verbose_name='Expected answer type')),
                ('options', models.JSONField(blank=True, default=list, help_text="Used when expected_answer_type='mcq'.", verbose_name='MCQ options')),
                ('scoring_rubric', models.JSONField(blank=True, default=dict, help_text='Free-form JSON used by the assessor.', verbose_name='Scoring rubric')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Placement question',
                'verbose_name_plural': 'Placement questions',
                'ordering': ['question_type', 'topic', 'code'],
                'indexes': [models.Index(fields=['question_type', 'is_active'], name='placement_p_questio_9f4407_idx'), models.Index(fields=['topic', 'is_active'], name='placement_p_topic_4a3930_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlacementAttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('written', 'Written'), ('speaking', 'Speaking')], db_index=True, max_length=12)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('user_answer_text', models.TextField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='placement/attempts/%Y/%m/')),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('error_analysis', models.JSONField(blank=True, default=dict)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='placement.placementattempt')),
                ('question', models.ForeignKey(help_text="PROTECT — bank questions can't be deleted while still referenced.", on_delete=django.db.models.deletion.PROTECT, related_name='attempt_uses', to='placement.placementquestion')),
            ],
            options={
                'verbose_name': 'Placement attempt question',
                'verbose_name_plural': 'Placement attempt questions',
                'ordering': ['attempt', 'section', 'order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='placementattempt',
            index=models.Index(fields=['user', '-started_at'], name='placement_p_user_id_3cdb42_idx'),
        ),
        migrations.AddIndex(
            model_name='placementattempt',
            index=models.Index(fields=['status'], name='placement_p_status_41b46c_idx'),
        ),
        migrations.AddIndex(
            model_name='placementattemptquestion',
            index=models.Index(fields=['attempt', 'section', 'order'], name='placement_p_attempt_4aa7c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='placementattemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question'),
        ),
    ]
