# Generated by Codex on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placement", "0005_placementattempt_placementquestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="placementattempt",
            name="fluency_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placementattempt",
            name="grammar_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placementattempt",
            name="pronunciation_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placementattempt",
            name="vocabulary_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placementattemptquestion",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placementattemptquestion",
            name="fluency_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placementattemptquestion",
            name="grammar_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placementattemptquestion",
            name="pronunciation_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placementattemptquestion",
            name="skill_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placementattemptquestion",
            name="vocabulary_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placementresult",
            name="grammar_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placementresult",
            name="overall_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placementresult",
            name="vocabulary_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
