# Generated by Django 5.2.14 on 2026-05-19 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0006_question_dimension_scores'),
        ('tutor', '0004_voicecallevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementattempt',
            name='voice_conversation',
            field=models.ForeignKey(blank=True, help_text='Linked TutorConversation when the speaking step is done via a live voice call (Part 2 of placement).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_attempts', to='tutor.tutorconversation'),
        ),
    ]
