# Generated by Django 5.2.14 on 2026-06-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0007_placementattempt_voice_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementquestion',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated stable identifier (e.g. wr.intro.001). Leave blank — the system assigns the next free sequence from the question_type + topic on save.', max_length=80, unique=True),
        ),
    ]
