# Generated by Django 5.2.14 on 2026-06-04 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0008_alter_placementquestion_code'),
        ('tutor', '0005_aishortroleplaysession_aishortroleplaymessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementSpeakingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed_start', 'Failed start — no answers'), ('insufficient_answers', 'Insufficient answers'), ('cancelled', 'Cancelled')], default='started', max_length=24)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('question_count_answered', models.PositiveSmallIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_used_attempt', models.BooleanField(db_index=True, default=False)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('reset_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_speaking_attempts', to='tutor.tutorconversation')),
                ('placement_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaking_attempts', to='placement.placementattempt')),
                ('reset_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_speaking_resets', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_speaking_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Placement speaking attempt',
                'verbose_name_plural': 'Placement speaking attempts',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['student', '-started_at'], name='placement_p_student_4ea786_idx'), models.Index(fields=['student', 'is_used_attempt', 'reset_at'], name='placement_p_student_f7ca48_idx')],
            },
        ),
    ]
