# Generated by Django 5.2.14 on 2026-06-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0009_placementspeakingattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementquestion',
            name='ai_alternatives',
            field=models.JSONField(blank=True, default=list, help_text='Cached alternative answer suggestions (oral guidance).'),
        ),
    ]
