# Generated by Django 5.2.14 on 2026-06-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0010_placementquestion_ai_alternatives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementspeakingattempt',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed_start', 'Failed start — no answers'), ('insufficient_answers', 'Insufficient answers'), ('needs_retry', 'Needs retry — too short'), ('cancelled', 'Cancelled')], default='started', max_length=24),
        ),
    ]
