# Generated by Django 5.2.14 on 2026-06-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0011_alter_placementspeakingattempt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementattempt',
            name='speaking_retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='placementspeakingattempt',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed_start', 'Failed start — no answers'), ('insufficient_answers', 'Insufficient answers'), ('needs_retry', 'Needs retry — too short'), ('unable_to_answer_after_retries', 'Unable to answer after retries'), ('failed_system', 'Failed — system/STT error'), ('cancelled', 'Cancelled')], default='started', max_length=32),
        ),
    ]
