# Generated by Django 5.2.14 on 2026-05-08 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('error_analysis', 'Error analysis'), ('cefr_prediction', 'CEFR prediction'), ('exercise_generation', 'Exercise generation'), ('answer_explanation', 'Answer explanation'), ('tutor_reply', 'Tutor reply'), ('speaking_feedback', 'Speaking feedback'), ('writing_feedback', 'Writing feedback')], max_length=24)),
                ('provider', models.CharField(choices=[('rules', 'Rules'), ('local_classifier', 'Local classifier'), ('local_llm', 'Local LLM'), ('rag', 'RAG / question bank'), ('openai', 'OpenAI'), ('none', 'None')], default='none', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('fallback_used', models.BooleanField(default=False)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('model_version', models.CharField(blank=True, max_length=80)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_type', '-created_at'], name='ai_engine_m_task_ty_61786b_idx'), models.Index(fields=['provider', '-created_at'], name='ai_engine_m_provide_d76bf9_idx'), models.Index(fields=['success'], name='ai_engine_m_success_21e697_idx'), models.Index(fields=['fallback_used'], name='ai_engine_m_fallbac_9f1410_idx'), models.Index(fields=['user', '-created_at'], name='ai_engine_m_user_id_46f148_idx')],
            },
        ),
    ]
