# Generated by Django 5.2.14 on 2026-05-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderKillSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(help_text="One of the registered task types, or '*' for all.", max_length=24)),
                ('provider', models.CharField(choices=[('rules', 'Rules'), ('local_classifier', 'Local classifier'), ('local_llm', 'Local LLM'), ('rag', 'RAG / question bank'), ('openai', 'OpenAI'), ('none', 'None')], max_length=20)),
                ('disabled', models.BooleanField(default=True, help_text='True = provider is skipped by the router for this task.')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-clear time. Null = stays disabled until manually re-enabled.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['task_type', 'provider'],
                'indexes': [models.Index(fields=['task_type', 'provider'], name='ai_engine_p_task_ty_b61339_idx'), models.Index(fields=['disabled'], name='ai_engine_p_disable_1652e8_idx')],
                'constraints': [models.UniqueConstraint(fields=('task_type', 'provider'), name='ai_engine_kill_switch_unique')],
            },
        ),
    ]
