# Generated by Django 5.2.14 on 2026-05-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_providerkillswitch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelpredictionlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Model prediction log', 'verbose_name_plural': 'Model prediction logs'},
        ),
        migrations.AlterModelOptions(
            name='providerkillswitch',
            options={'ordering': ['task_type', 'provider'], 'verbose_name': 'Provider kill switch', 'verbose_name_plural': 'Provider kill switches'},
        ),
        migrations.AlterField(
            model_name='modelpredictionlog',
            name='task_type',
            field=models.CharField(choices=[('error_analysis', 'Error analysis'), ('cefr_prediction', 'CEFR prediction'), ('exercise_generation', 'Exercise generation'), ('answer_explanation', 'Answer explanation'), ('tutor_reply', 'Tutor reply'), ('speaking_feedback', 'Speaking feedback'), ('writing_feedback', 'Writing feedback'), ('difficulty_estimation', 'Difficulty estimation')], max_length=24),
        ),
    ]
