# Generated by Django 5.2.14 on 2026-05-08 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstitutionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('items', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
                'indexes': [models.Index(fields=['kind', 'is_active'], name='factory_sub_kind_6f0a7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('kind', models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking'), ('pronunciation', 'Pronunciation'), ('comprehension', 'Comprehension')], max_length=20)),
                ('cefr_level', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], max_length=2)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='factory.topic')),
            ],
            options={
                'ordering': ['kind', 'cefr_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(help_text='Stable identifier used for deterministic codegen.', max_length=80, unique=True)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('fill_blank', 'Fill in the blank'), ('correction', 'Correction'), ('sentence_ordering', 'Sentence ordering'), ('translation', 'Translation'), ('short_answer', 'Short answer'), ('reading_comprehension', 'Reading comprehension'), ('listening_comprehension', 'Listening comprehension'), ('speaking_prompt', 'Speaking prompt'), ('writing_prompt', 'Writing prompt'), ('vocabulary_matching', 'Vocabulary matching'), ('grammar_transformation', 'Grammar transformation')], max_length=24)),
                ('cefr_level', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], max_length=2)),
                ('pattern', models.TextField(help_text='Sentence template with {var} placeholders.')),
                ('variables', models.JSONField(default=dict, help_text='Map of placeholder → SubstitutionBank.name.')),
                ('correct_answer_expression', models.CharField(help_text='DSL expression that resolves to the correct answer given the bound bank row.', max_length=160)),
                ('distractor_strategy', models.CharField(choices=[('static', 'Static — distractors come from the template'), ('from_bank', 'From bank — sample wrong answers from a substitution bank'), ('morph', 'Morph — programmatic perturbations of the correct answer'), ('ai', 'AI-generated — call the LLM router')], default='from_bank', max_length=10)),
                ('distractor_config', models.JSONField(blank=True, default=dict, help_text='Strategy-specific config (e.g. bank name for from_bank).')),
                ('explanation_pattern', models.TextField(blank=True, help_text='Optional explanation template — same {var} syntax.')),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('estimated_time_seconds', models.PositiveSmallIntegerField(default=30)),
                ('difficulty_score', models.FloatField(default=0.5)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='factory.topic')),
            ],
            options={
                'ordering': ['topic', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('question_generation', 'Prompt → question'), ('error_correction', 'Wrong sentence → corrected sentence'), ('difficulty_estimation', 'Question → difficulty score'), ('cefr_classification', 'Question → CEFR level'), ('explanation_writing', 'Q+A → explanation'), ('rag_corpus', 'RAG corpus (chunks for retrieval)')], max_length=24)),
                ('description', models.TextField(blank=True)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Source-row filters (cefr, skill, generated_by, etc.).')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('building', 'Building'), ('ready', 'Ready'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('last_export_path', models.CharField(blank=True, max_length=500)),
                ('last_exported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('bytes_written', models.PositiveBigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='factory.trainingdataset')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['kind', 'cefr_level'], name='factory_top_kind_dde41b_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['is_active'], name='factory_top_is_acti_e6f028_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['parent'], name='factory_top_parent__78a82e_idx'),
        ),
        migrations.AddIndex(
            model_name='questiontemplate',
            index=models.Index(fields=['topic', 'is_active'], name='factory_que_topic_i_d8759c_idx'),
        ),
        migrations.AddIndex(
            model_name='questiontemplate',
            index=models.Index(fields=['question_type', 'cefr_level'], name='factory_que_questio_a305a5_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingdataset',
            index=models.Index(fields=['kind', 'status'], name='factory_tra_kind_59d652_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetexportjob',
            index=models.Index(fields=['dataset', '-started_at'], name='factory_dat_dataset_aadf08_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetexportjob',
            index=models.Index(fields=['status'], name='factory_dat_status_050fb2_idx'),
        ),
    ]
