# Generated by Django 5.2.14 on 2026-05-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasetexportjob',
            options={'ordering': ['-started_at'], 'verbose_name': 'Dataset export job', 'verbose_name_plural': 'Dataset export jobs'},
        ),
        migrations.AlterModelOptions(
            name='questiontemplate',
            options={'ordering': ['topic', 'name'], 'verbose_name': 'Question template', 'verbose_name_plural': 'Question templates'},
        ),
        migrations.AlterModelOptions(
            name='substitutionbank',
            options={'ordering': ['kind', 'name'], 'verbose_name': 'Substitution bank', 'verbose_name_plural': 'Substitution banks'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['kind', 'cefr_level', 'name'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AlterModelOptions(
            name='trainingdataset',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Training dataset', 'verbose_name_plural': 'Training datasets'},
        ),
    ]
