# Generated by Django 5.2.14 on 2026-05-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorconversation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Tutor conversation', 'verbose_name_plural': 'Tutor conversations'},
        ),
        migrations.AlterModelOptions(
            name='tutormessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Tutor message', 'verbose_name_plural': 'Tutor messages'},
        ),
    ]
