# Generated by Django 5.2.14 on 2026-05-12 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courselessonprogress'),
        ('tutor', '0002_alter_tutorconversation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITutorPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_slug', models.CharField(blank=True, db_index=True, help_text='Free-form slug; lets a prompt live outside any Lesson row.', max_length=120, verbose_name='Lesson slug')),
                ('cefr_level', models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A0', max_length=2)),
                ('prompt_en', models.TextField(verbose_name='Prompt (EN)')),
                ('prompt_ar', models.TextField(verbose_name='Prompt (AR)')),
                ('expected_student_answer', models.TextField(blank=True, help_text='Reference answer the chat service can score against.')),
                ('correction_strategy', models.CharField(choices=[('echo-and-encourage', 'Echo and encourage'), ('mouth-position', 'Mouth position hint'), ('letter-shape', 'Letter-shape hint'), ('add-missing-word', 'Add the missing word'), ('quick-fix-with-why', 'Quick fix with rationale')], default='echo-and-encourage', max_length=24)),
                ('difficulty_score', models.FloatField(default=0.1)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_prompts', to='courses.lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'AI tutor prompt',
                'verbose_name_plural': 'AI tutor prompts',
                'ordering': ['lesson', 'order', 'id'],
                'indexes': [models.Index(fields=['lesson_slug', 'order'], name='tutor_aitut_lesson__30c122_idx'), models.Index(fields=['cefr_level', 'is_active'], name='tutor_aitut_cefr_le_722b6f_idx')],
            },
        ),
    ]
