# Generated by Django 5.2.14 on 2026-05-19 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_aitutorprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCallEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cefr_level', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('fluency_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vocabulary_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grammar_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pronunciation_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('overall_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('turns_count', models.PositiveSmallIntegerField(default=0)),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='tutor.tutorconversation')),
            ],
            options={
                'verbose_name': 'Voice call evaluation',
                'verbose_name_plural': 'Voice call evaluations',
            },
        ),
    ]
