# Generated by Django 5.2.14 on 2026-05-29 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_question_types_phase3'),
        ('tutor', '0004_voicecallevaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIShortRoleplaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=12)),
                ('turns_count', models.PositiveIntegerField(default=0)),
                ('max_turns', models.PositiveSmallIntegerField(default=5)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('challenge_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_roleplay_sessions', to='courses.challengesession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_roleplay_sessions', to='courses.lessonquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_roleplay_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI roleplay session',
                'verbose_name_plural': 'AI roleplay sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AIShortRoleplayMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=6)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roleplay_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tutor.aishortroleplaysession')),
            ],
            options={
                'verbose_name': 'AI roleplay message',
                'verbose_name_plural': 'AI roleplay messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeAIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('wrong_answer_explanation', 'Wrong answer explanation'), ('speaking_feedback', 'Speaking feedback'), ('roleplay', 'Roleplay turn'), ('end_advice', 'End-of-challenge advice'), ('mistake_explanation', 'Mistake explanation'), ('conversation_enhancement', 'Conversation reply suggestion')], max_length=32)),
                ('prompt_hash', models.CharField(blank=True, max_length=64)),
                ('response_en', models.TextField(blank=True)),
                ('response_ar', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('fallback', 'Fallback'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='success', max_length=10)),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interactions', to='courses.challengeanswer')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interactions', to='courses.lessonquestion')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interactions', to='courses.challengesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_ai_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Challenge AI interaction',
                'verbose_name_plural': 'Challenge AI interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aishortroleplaysession',
            index=models.Index(fields=['user', '-started_at'], name='tutor_aisho_user_id_314ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='aishortroleplaysession',
            index=models.Index(fields=['challenge_session'], name='tutor_aisho_challen_eaa023_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeaiinteraction',
            index=models.Index(fields=['user', '-created_at'], name='tutor_chall_user_id_cd1146_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeaiinteraction',
            index=models.Index(fields=['session', '-created_at'], name='tutor_chall_session_c8c3a6_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeaiinteraction',
            index=models.Index(fields=['interaction_type', '-created_at'], name='tutor_chall_interac_93a229_idx'),
        ),
    ]
