# Generated by Django 5.2.14 on 2026-05-08 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning_core', '0007_adaptiveexercise_adex_assembly_hot_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=80, unique=True)),
                ('target_count', models.PositiveIntegerField()),
                ('generated_count', models.PositiveIntegerField(default=0)),
                ('accepted_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='pending', max_length=10)),
                ('strategy', models.CharField(choices=[('template', 'Template — deterministic substitution'), ('ai', 'AI — LLM-generated end-to-end'), ('hybrid', 'Hybrid — template body + AI explanation/distractors'), ('imported', 'Imported — externally curated')], default='template', max_length=10)),
                ('cefr_level', models.CharField(blank=True, max_length=2)),
                ('skill', models.CharField(blank=True, max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', '-started_at'], name='question_fa_status_e8e2ad_idx'), models.Index(fields=['cefr_level', 'skill'], name='question_fa_cefr_le_50602a_idx'), models.Index(fields=['strategy'], name='question_fa_strateg_882f95_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Stable identifier (e.g. 'gr-A1-presimple-3sg').", max_length=80, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('cefr_level', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], max_length=2)),
                ('skill', models.CharField(blank=True, choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking'), ('pronunciation', 'Pronunciation'), ('comprehension', 'Comprehension')], max_length=20)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('fill_blank', 'Fill in the blank'), ('correction', 'Correction'), ('sentence_ordering', 'Sentence ordering'), ('translation', 'Translation'), ('short_answer', 'Short answer'), ('reading_comprehension', 'Reading comprehension'), ('listening_comprehension', 'Listening comprehension'), ('speaking_prompt', 'Speaking prompt'), ('writing_prompt', 'Writing prompt'), ('vocabulary_matching', 'Vocabulary matching'), ('grammar_transformation', 'Grammar transformation')], max_length=24)),
                ('vocabulary_topic', models.CharField(blank=True, help_text='Free-text vocabulary topic (no model exists yet).', max_length=80)),
                ('difficulty_min', models.FloatField(default=0.0)),
                ('difficulty_max', models.FloatField(default=1.0)),
                ('template_pattern', models.TextField(help_text='Sentence template with {var} placeholders.')),
                ('expected_answer_pattern', models.CharField(help_text='DSL expression resolving to the correct answer.', max_length=200)),
                ('explanation_pattern', models.TextField(blank=True)),
                ('variables_schema', models.JSONField(blank=True, default=dict, help_text='Schema describing each variable (inline lists or bank refs).')),
                ('generation_strategy', models.CharField(choices=[('template', 'Template — deterministic substitution'), ('ai', 'AI — LLM-generated end-to-end'), ('hybrid', 'Hybrid — template body + AI explanation/distractors'), ('imported', 'Imported — externally curated')], default='template', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grammar_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qf_blueprints', to='learning_core.grammartopic')),
            ],
            options={
                'ordering': ['cefr_level', 'skill', 'code'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=160, unique=True)),
                ('cefr_level', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], max_length=2)),
                ('skill', models.CharField(blank=True, choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking'), ('pronunciation', 'Pronunciation'), ('comprehension', 'Comprehension')], max_length=20)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('fill_blank', 'Fill in the blank'), ('correction', 'Correction'), ('sentence_ordering', 'Sentence ordering'), ('translation', 'Translation'), ('short_answer', 'Short answer'), ('reading_comprehension', 'Reading comprehension'), ('listening_comprehension', 'Listening comprehension'), ('speaking_prompt', 'Speaking prompt'), ('writing_prompt', 'Writing prompt'), ('vocabulary_matching', 'Vocabulary matching'), ('grammar_transformation', 'Grammar transformation')], max_length=24)),
                ('vocabulary_topic', models.CharField(blank=True, max_length=80)),
                ('difficulty_score', models.FloatField(default=0.5)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('acceptable_answers', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True)),
                ('feedback_correct', models.TextField(blank=True)),
                ('feedback_wrong', models.TextField(blank=True)),
                ('generated_by', models.CharField(choices=[('template', 'Template'), ('ai', 'AI'), ('hybrid', 'Hybrid'), ('imported', 'Imported')], default='template', max_length=10)),
                ('quality_score', models.PositiveSmallIntegerField(default=0)),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-1 of normalised text — used for dedup.', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('approved_for_training', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grammar_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qf_generated', to='learning_core.grammartopic')),
                ('blueprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_questions', to='question_factory.questionblueprint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionVariableSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variables', models.JSONField(default=dict)),
                ('cefr_level', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], max_length=2)),
                ('skill', models.CharField(blank=True, choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking'), ('pronunciation', 'Pronunciation'), ('comprehension', 'Comprehension')], max_length=20)),
                ('difficulty_score', models.FloatField(default=0.5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_sets', to='question_factory.questionblueprint')),
                ('grammar_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qf_variable_sets', to='learning_core.grammartopic')),
            ],
            options={
                'ordering': ['blueprint', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='questionblueprint',
            index=models.Index(fields=['cefr_level', 'skill'], name='question_fa_cefr_le_b2dc97_idx'),
        ),
        migrations.AddIndex(
            model_name='questionblueprint',
            index=models.Index(fields=['question_type', 'cefr_level'], name='question_fa_questio_411d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='questionblueprint',
            index=models.Index(fields=['generation_strategy'], name='question_fa_generat_891cea_idx'),
        ),
        migrations.AddIndex(
            model_name='questionblueprint',
            index=models.Index(fields=['is_active'], name='question_fa_is_acti_89edd3_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedquestion',
            index=models.Index(fields=['cefr_level', 'skill'], name='question_fa_cefr_le_7c25e0_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedquestion',
            index=models.Index(fields=['question_type', 'cefr_level'], name='question_fa_questio_eddd03_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedquestion',
            index=models.Index(fields=['generated_by'], name='question_fa_generat_cae516_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedquestion',
            index=models.Index(fields=['is_active', 'is_reviewed'], name='question_fa_is_acti_60319e_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedquestion',
            index=models.Index(fields=['approved_for_training'], name='question_fa_approve_d673c7_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedquestion',
            index=models.Index(fields=['quality_score'], name='question_fa_quality_df29a6_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedquestion',
            index=models.Index(fields=['content_hash'], name='question_fa_content_1e1c80_idx'),
        ),
        migrations.AddIndex(
            model_name='questionvariableset',
            index=models.Index(fields=['blueprint', 'is_active'], name='question_fa_bluepri_bf9d71_idx'),
        ),
        migrations.AddIndex(
            model_name='questionvariableset',
            index=models.Index(fields=['cefr_level', 'skill'], name='question_fa_cefr_le_203b97_idx'),
        ),
    ]
