# Generated by Django 5.2.14 on 2026-05-08 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_core', '0007_adaptiveexercise_adex_assembly_hot_idx'),
        ('question_factory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_key', models.CharField(max_length=80, unique=True)),
                ('cefr_level', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], max_length=2)),
                ('skill', models.CharField(blank=True, choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking'), ('pronunciation', 'Pronunciation'), ('comprehension', 'Comprehension')], max_length=20)),
                ('difficulty_score', models.FloatField(default=0.5)),
                ('variable_state', models.JSONField(blank=True, default=dict, help_text='The exact variable bindings used at render time.')),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-1 of normalised text — used for user-level dedup.', max_length=40)),
                ('generated_count', models.PositiveIntegerField(default=1, help_text='How many times this seed has been served (across all users).')),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seeds', to='question_factory.questionblueprint')),
                ('grammar_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qf_seeds', to='learning_core.grammartopic')),
            ],
            options={
                'ordering': ['-last_used_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSeedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(db_index=True, max_length=40)),
                ('answered', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='question_factory.questionseed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qf_seed_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-seen_at'],
            },
        ),
        migrations.AddIndex(
            model_name='questionseed',
            index=models.Index(fields=['blueprint', '-last_used_at'], name='question_fa_bluepri_a0b446_idx'),
        ),
        migrations.AddIndex(
            model_name='questionseed',
            index=models.Index(fields=['cefr_level', 'skill'], name='question_fa_cefr_le_5573d8_idx'),
        ),
        migrations.AddIndex(
            model_name='questionseed',
            index=models.Index(fields=['content_hash'], name='question_fa_content_2bd65c_idx'),
        ),
        migrations.AddIndex(
            model_name='userseedhistory',
            index=models.Index(fields=['user', 'content_hash'], name='question_fa_user_id_210abc_idx'),
        ),
        migrations.AddIndex(
            model_name='userseedhistory',
            index=models.Index(fields=['user', '-seen_at'], name='question_fa_user_id_d0f815_idx'),
        ),
        migrations.AddConstraint(
            model_name='userseedhistory',
            constraint=models.UniqueConstraint(fields=('user', 'seed'), name='qf_user_seed_unique'),
        ),
    ]
