# Generated by Django 5.2.14 on 2026-05-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_factory', '0002_questionseed_userseedhistory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedquestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Generated question', 'verbose_name_plural': 'Generated questions'},
        ),
        migrations.AlterModelOptions(
            name='generationbatch',
            options={'ordering': ['-started_at'], 'verbose_name': 'Generation batch', 'verbose_name_plural': 'Generation batches'},
        ),
        migrations.AlterModelOptions(
            name='questionblueprint',
            options={'ordering': ['cefr_level', 'skill', 'code'], 'verbose_name': 'Question blueprint', 'verbose_name_plural': 'Question blueprints'},
        ),
        migrations.AlterModelOptions(
            name='questionseed',
            options={'ordering': ['-last_used_at'], 'verbose_name': 'Question seed', 'verbose_name_plural': 'Question seeds'},
        ),
        migrations.AlterModelOptions(
            name='questionvariableset',
            options={'ordering': ['blueprint', 'id'], 'verbose_name': 'Question variable set', 'verbose_name_plural': 'Question variable sets'},
        ),
        migrations.AlterModelOptions(
            name='userseedhistory',
            options={'ordering': ['-seen_at'], 'verbose_name': 'User seed history', 'verbose_name_plural': 'User seed histories'},
        ),
    ]
