# Generated by Django 5.2.14 on 2026-05-07 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('name_ar', models.CharField(blank=True, max_length=120)),
                ('description_ar', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('lesson', 'Lesson'), ('quiz', 'Quiz'), ('reading', 'Reading'), ('speaking', 'Speaking'), ('ai_tutor', 'AI Tutor'), ('streak', 'Streak'), ('vocabulary', 'Vocabulary'), ('level', 'Level'), ('subscription', 'Subscription')], max_length=20)),
                ('threshold_value', models.IntegerField(default=0)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('badge_icon', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'threshold_value', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LearnerActivitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('speaking_minutes', models.PositiveIntegerField(default=0)),
                ('ai_chat_minutes', models.PositiveIntegerField(default=0)),
                ('ai_messages_count', models.PositiveIntegerField(default=0)),
                ('listening_minutes', models.PositiveIntegerField(default=0)),
                ('reading_minutes', models.PositiveIntegerField(default=0)),
                ('words_read', models.PositiveIntegerField(default=0)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('quizzes_completed', models.PositiveIntegerField(default=0)),
                ('questions_answered', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('quiz_accuracy', models.FloatField(default=0.0)),
                ('vocabulary_words_learned', models.PositiveIntegerField(default=0)),
                ('writing_attempts', models.PositiveIntegerField(default=0)),
                ('weekly_assessments_completed', models.PositiveIntegerField(default=0)),
                ('current_streak_days', models.PositiveIntegerField(default=0)),
                ('inactive_days', models.PositiveIntegerField(default=0)),
                ('cefr_level', models.CharField(blank=True, max_length=2)),
                ('theta_score', models.FloatField(default=0.0)),
                ('mastery_delta', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MotivationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('achievement', 'Achievement'), ('encouragement', 'Encouragement'), ('streak', 'Streak'), ('comeback', 'Comeback'), ('goal', 'Goal'), ('warning', 'Warning'), ('challenge', 'Challenge'), ('weekly_summary', 'Weekly summary')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2)),
                ('tone', models.CharField(choices=[('energetic', 'Energetic'), ('gentle', 'Gentle'), ('professional', 'Professional'), ('challenging', 'Challenging'), ('supportive', 'Supportive')], default='supportive', max_length=20)),
                ('related_activity', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('sent', 'Sent'), ('dismissed', 'Dismissed'), ('clicked', 'Clicked')], default='generated', max_length=15)),
                ('sent_via', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('both', 'Both'), ('none', 'Not sent')], default='none', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_messages', to='motivation.achievement')),
                ('related_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_messages', to='motivation.learneractivitysnapshot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivation_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MotivationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_motivation_notifications', models.BooleanField(default=True)),
                ('enable_email_motivation', models.BooleanField(default=True)),
                ('enable_streak_reminders', models.BooleanField(default=True)),
                ('enable_weekly_summary', models.BooleanField(default=True)),
                ('preferred_tone', models.CharField(choices=[('energetic', 'Energetic'), ('gentle', 'Gentle'), ('professional', 'Professional'), ('challenging', 'Challenging'), ('supportive', 'Supportive')], default='supportive', max_length=20)),
                ('motivation_frequency', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motivation_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earners', to='motivation.achievement')),
                ('source_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements_unlocked', to='motivation.learneractivitysnapshot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements_earned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_code', models.CharField(max_length=80)),
                ('badge_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges_earned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='UserXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('weekly_xp', models.PositiveIntegerField(default=0)),
                ('monthly_xp', models.PositiveIntegerField(default=0)),
                ('level_number', models.PositiveIntegerField(default=1)),
                ('weekly_xp_reset_at', models.DateField(blank=True, null=True)),
                ('monthly_xp_reset_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='learneractivitysnapshot',
            index=models.Index(fields=['user', '-date'], name='motivation__user_id_6e52f4_idx'),
        ),
        migrations.AddIndex(
            model_name='learneractivitysnapshot',
            index=models.Index(fields=['date'], name='motivation__date_45959c_idx'),
        ),
        migrations.AddConstraint(
            model_name='learneractivitysnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='motivation_unique_user_date'),
        ),
        migrations.AddIndex(
            model_name='motivationmessage',
            index=models.Index(fields=['user', '-created_at'], name='motivation__user_id_b701b6_idx'),
        ),
        migrations.AddIndex(
            model_name='motivationmessage',
            index=models.Index(fields=['message_type'], name='motivation__message_f4c826_idx'),
        ),
        migrations.AddIndex(
            model_name='motivationmessage',
            index=models.Index(fields=['status'], name='motivation__status_f5187f_idx'),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(fields=('user', 'achievement'), name='motivation_unique_user_achievement'),
        ),
        migrations.AddConstraint(
            model_name='userbadge',
            constraint=models.UniqueConstraint(fields=('user', 'badge_code'), name='motivation_unique_user_badge'),
        ),
    ]
