# Generated by Django 5.2.14 on 2026-05-07 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='motivationpreference',
            name='show_on_leaderboard',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('title_ar', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('metric', models.CharField(choices=[('lessons_completed', 'Lessons completed'), ('questions_answered', 'Questions answered'), ('ai_chat_minutes', 'AI tutor minutes'), ('speaking_minutes', 'Speaking minutes'), ('words_read', 'Words read'), ('vocabulary_words_learned', 'Vocabulary words'), ('writing_attempts', 'Writing attempts')], max_length=40)),
                ('target_value', models.PositiveIntegerField()),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('start_at', models.DateField()),
                ('end_at', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_at'],
                'indexes': [models.Index(fields=['kind', 'is_active', 'start_at'], name='motivation__kind_d9bd52_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='motivation.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-updated_at'], name='motivation__user_id_beaef6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'challenge'), name='motivation_unique_user_challenge')],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('xp', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['period', '-period_start', 'rank'],
                'indexes': [models.Index(fields=['period', '-period_start', 'rank'], name='motivation__period_5bf23f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'period', 'period_start'), name='motivation_unique_leaderboard_period')],
            },
        ),
    ]
