# Generated by Django 5.2.14 on 2026-05-08 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motivation', '0002_motivationpreference_show_on_leaderboard_challenge_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['category', 'threshold_value', 'name'], 'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-start_at'], 'verbose_name': 'Challenge', 'verbose_name_plural': 'Challenges'},
        ),
        migrations.AlterModelOptions(
            name='challengeprogress',
            options={'verbose_name': 'Challenge progress', 'verbose_name_plural': 'Challenge progress'},
        ),
        migrations.AlterModelOptions(
            name='leaderboardentry',
            options={'ordering': ['period', '-period_start', 'rank'], 'verbose_name': 'Leaderboard entry', 'verbose_name_plural': 'Leaderboard entries'},
        ),
        migrations.AlterModelOptions(
            name='learneractivitysnapshot',
            options={'ordering': ['-date'], 'verbose_name': 'Learner activity snapshot', 'verbose_name_plural': 'Learner activity snapshots'},
        ),
        migrations.AlterModelOptions(
            name='motivationmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Motivation message', 'verbose_name_plural': 'Motivation messages'},
        ),
        migrations.AlterModelOptions(
            name='motivationpreference',
            options={'verbose_name': 'Motivation preference', 'verbose_name_plural': 'Motivation preferences'},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'ordering': ['-earned_at'], 'verbose_name': 'User achievement', 'verbose_name_plural': 'User achievements'},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-earned_at'], 'verbose_name': 'User badge', 'verbose_name_plural': 'User badges'},
        ),
        migrations.AlterModelOptions(
            name='userxp',
            options={'verbose_name': 'User XP', 'verbose_name_plural': 'User XP'},
        ),
    ]
