# Generated by Django 5.2.14 on 2026-05-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivation', '0004_seed_default_achievements'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEventSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('success', 'Success — lesson / quiz completed'), ('level_up', 'Level up'), ('bonus', 'XP bonus'), ('streak', 'Streak milestone'), ('achievement_unlocked', 'Achievement unlocked')], max_length=32, unique=True)),
                ('audio_url', models.URLField(blank=True, help_text='Public URL to a short MP3/OGG (≤ 4 s).')),
                ('fallback_audio_path', models.CharField(blank=True, help_text='Static path under STATIC_URL when audio_url is empty.', max_length=255)),
                ('message_en', models.CharField(max_length=160)),
                ('message_ar', models.CharField(max_length=160)),
                ('animation', models.CharField(choices=[('confetti', 'Confetti burst'), ('sparkle', 'Sparkle'), ('trophy', 'Trophy pop'), ('flame', 'Flame streak'), ('rocket', 'Rocket'), ('none', 'None')], default='sparkle', max_length=24)),
                ('xp_callout_template_en', models.CharField(blank=True, help_text="Optional callout like '+{xp} XP' shown alongside the toast.", max_length=120)),
                ('xp_callout_template_ar', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game event sound',
                'verbose_name_plural': 'Game event sounds',
                'ordering': ['code'],
            },
        ),
    ]
