# Generated by Django 5.2.14 on 2026-05-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivation', '0006_seed_game_event_sounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='learneractivitysnapshot',
            name='churn_risk_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='learneractivitysnapshot',
            name='engagement_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
