# Generated by Django 5.2.14 on 2026-05-29 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivation', '0007_learneractivitysnapshot_churn_risk_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='UPPER_SNAKE_CASE identifier, e.g. FIRST_CHALLENGE.', max_length=80, unique=True)),
                ('title_en', models.CharField(max_length=120)),
                ('title_ar', models.CharField(blank=True, max_length=120)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('icon_name', models.CharField(default='award', help_text='Lucide icon name.', max_length=40)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('criteria', models.JSONField(blank=True, default=dict, help_text='Free-form criteria the evaluator uses.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Badge definition',
                'verbose_name_plural': 'Badge definitions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('xp', 'Earn XP'), ('minutes', 'Spend minutes'), ('challenges', 'Complete challenges')], default='xp', max_length=16)),
                ('target_value', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily goal',
                'verbose_name_plural': 'Daily goals',
            },
        ),
        migrations.CreateModel(
            name='StudentStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('streak_freeze_count', models.PositiveSmallIntegerField(default=0, help_text='Reserved for Phase 6 — not consumed yet.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student streak',
                'verbose_name_plural': 'Student streaks',
            },
        ),
        migrations.CreateModel(
            name='DailyGoalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('minutes_spent', models.PositiveIntegerField(default=0)),
                ('challenges_completed', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bonus_awarded', models.BooleanField(default=False, help_text='True once the +25 XP daily-goal bonus was credited.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goal_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily goal progress',
                'verbose_name_plural': 'Daily goal progress',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='motivation__user_id_50db79_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='motivation_dailygoal_unique')],
            },
        ),
        migrations.CreateModel(
            name='StreakActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('activity_type', models.CharField(choices=[('challenge_started', 'Challenge started'), ('challenge_completed', 'Challenge completed'), ('lesson_completed', 'Lesson completed'), ('daily_goal_completed', 'Daily goal completed')], max_length=32)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Streak activity',
                'verbose_name_plural': 'Streak activities',
                'ordering': ['-activity_date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-activity_date'], name='motivation__user_id_c30283_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'activity_date', 'activity_type'), name='motivation_streakact_unique')],
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive grant or negative correction.')),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('source_type', models.CharField(choices=[('challenge_answer', 'Challenge answer'), ('challenge_completion', 'Challenge completion bonus'), ('perfect_bonus', 'Perfect challenge bonus'), ('daily_goal_bonus', 'Daily goal bonus'), ('badge_reward', 'Badge reward'), ('lesson_completion', 'Lesson completion'), ('speaking_placeholder', 'Speaking placeholder (self-check)'), ('manual_adjustment', 'Manual adjustment'), ('snapshot', 'Daily activity snapshot')], default='manual_adjustment', max_length=32)),
                ('source_id', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'XP transaction',
                'verbose_name_plural': 'XP transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='motivation__user_id_c19678_idx'), models.Index(fields=['source_type', '-created_at'], name='motivation__source__eda753_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_id', ''), _negated=True), fields=('user', 'source_type', 'source_id'), name='motivation_xp_tx_idempotent')],
            },
        ),
    ]
