# Generated by Django 5.2.14 on 2026-05-31 16:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('other', 'Other')], db_index=True, default='openai', max_length=16)),
                ('model_name', models.CharField(db_index=True, max_length=128)),
                ('input_price_per_1m_tokens', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='USD per 1,000,000 input/prompt tokens.', max_digits=18)),
                ('output_price_per_1m_tokens', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='USD per 1,000,000 output/completion tokens.', max_digits=18)),
                ('audio_input_price_per_minute', models.DecimalField(blank=True, decimal_places=6, help_text='USD per minute of input audio (STT / realtime in).', max_digits=18, null=True)),
                ('audio_output_price_per_minute', models.DecimalField(blank=True, decimal_places=6, help_text='USD per minute of output audio (TTS / realtime out).', max_digits=18, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI model pricing',
                'verbose_name_plural': 'AI model pricing',
                'ordering': ['provider', 'model_name', '-effective_from'],
                'indexes': [models.Index(fields=['provider', 'model_name', 'is_active'], name='ai_usage_ai_provide_a2529c_idx'), models.Index(fields=['provider', 'model_name', 'effective_from'], name='ai_usage_ai_provide_0b4f7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIDailyUsageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('organization', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('system', 'System')], default='student', max_length=16)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('successful_requests', models.PositiveIntegerField(default=0)),
                ('failed_requests', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('total_tokens', models.PositiveBigIntegerField(default=0)),
                ('ai_minutes_used', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('ai_tutor_minutes_used', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('placement_minutes_used', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('content_generation_cost', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('top_feature', models.JSONField(blank=True, default=dict)),
                ('top_model', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI daily usage summary',
                'verbose_name_plural': 'AI daily usage summaries',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'role'], name='ai_usage_ai_date_c66d99_idx'), models.Index(fields=['organization', 'date'], name='ai_usage_ai_organiz_863a47_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'user', 'organization', 'role'), name='unique_ai_daily_summary')],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('system', 'System')], default='student', max_length=16)),
                ('feature', models.CharField(choices=[('placement_written', 'Placement (written)'), ('placement_speaking', 'Placement (speaking)'), ('ai_tutor', 'AI Tutor'), ('lesson_assistant', 'Lesson assistant'), ('vocabulary', 'Vocabulary'), ('library', 'Library'), ('motivation', 'Motivation'), ('content_generation', 'Content generation'), ('challenge_explanation', 'Challenge explanation'), ('challenge_roleplay', 'Challenge roleplay'), ('challenge_end_advice', 'Challenge end advice'), ('reading_listening', 'Reading/listening assistant'), ('other', 'Other')], default='other', max_length=32)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('other', 'Other')], default='openai', max_length=16)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('request_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('session_id', models.CharField(blank=True, default='', max_length=128)),
                ('lesson_id', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_id', models.PositiveIntegerField(blank=True, null=True)),
                ('course_id', models.PositiveIntegerField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('audio_input_seconds', models.PositiveIntegerField(default=0)),
                ('audio_output_seconds', models.PositiveIntegerField(default=0)),
                ('ai_minutes_used', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='success', max_length=12)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI usage log',
                'verbose_name_plural': 'AI usage logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usage_date'], name='ai_usage_ai_usage_d_37cb2c_idx'), models.Index(fields=['user', 'usage_date'], name='ai_usage_ai_user_id_c315a1_idx'), models.Index(fields=['feature', 'usage_date'], name='ai_usage_ai_feature_968543_idx'), models.Index(fields=['model_name', 'usage_date'], name='ai_usage_ai_model_n_f46132_idx'), models.Index(fields=['organization', 'usage_date'], name='ai_usage_ai_organiz_f54984_idx'), models.Index(fields=['status', 'usage_date'], name='ai_usage_ai_status_c0372d_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentDailyAILimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('plan_name', models.CharField(blank=True, default='', max_length=128)),
                ('allowed_minutes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('used_minutes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('remaining_minutes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('is_free_first_day', models.BooleanField(default=False)),
                ('is_exceeded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_daily_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student daily AI limit',
                'verbose_name_plural': 'Student daily AI limits',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='unique_student_daily_ai_limit')],
            },
        ),
    ]
