# Generated by Django 5.2.14 on 2026-06-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_usage', '0003_alter_aiusagelog_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelpricing',
            name='image_price_per_1k_images',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='USD per 1,000 generated images (alt unit).', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='aimodelpricing',
            name='image_price_per_generation',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='USD per generated image.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='aimodelpricing',
            name='image_pricing_unit',
            field=models.CharField(choices=[('per_image', 'Per image'), ('per_1k_images', 'Per 1k images')], default='per_image', help_text='Which image price field to use.', max_length=16),
        ),
    ]
