# Generated by Django 5.2.14 on 2026-06-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_usage', '0005_seed_image_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='feature',
            field=models.CharField(choices=[('placement_written', 'Placement (written)'), ('placement_speaking', 'Placement (speaking)'), ('placement_alternatives', 'Placement (answer suggestions)'), ('ai_tutor', 'AI Tutor'), ('lesson_assistant', 'Lesson assistant'), ('vocabulary', 'Vocabulary'), ('library', 'Library'), ('motivation', 'Motivation'), ('content_generation', 'Content generation'), ('challenge_explanation', 'Challenge explanation'), ('challenge_roleplay', 'Challenge roleplay'), ('challenge_end_advice', 'Challenge end advice'), ('reading_listening', 'Reading/listening assistant'), ('stt', 'Speech-to-text'), ('tts', 'Text-to-speech'), ('media_generation', 'Media generation'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
