from django.urls import path

from . import views
from . import views_content_review

app_name = "teacher_portal"

urlpatterns = [
    path("switch/<str:role>/", views.switch_role, name="switch_role"),
    path("switch-mode/<str:mode>/", views.switch_staff_mode, name="switch_staff_mode"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("courses/", views.courses_list, name="courses"),
    path("courses/create/", views.course_create, name="course_create"),
    path("courses/<int:pk>/", views.course_detail, name="course_detail"),
    path("courses/<int:pk>/edit/", views.course_edit, name="course_edit"),
    path("courses/<int:pk>/delete/", views.course_delete, name="course_delete"),
    path("courses/<int:pk>/archive/", views.course_archive, name="course_archive"),
    path("courses/<int:pk>/submit-review/", views.course_submit_review, name="course_submit_review"),
    path("courses/<int:course_id>/lessons/", views.lessons_list, name="lessons"),
    path("courses/<int:course_id>/lessons/create/", views.lesson_create, name="lesson_create"),
    path("lessons/", views.all_lessons, name="all_lessons"),
    path("lessons/<int:lesson_id>/edit/", views.lesson_edit, name="lesson_edit"),
    path("lessons/<int:lesson_id>/delete/", views.lesson_delete, name="lesson_delete"),
    path("lessons/<int:lesson_id>/submit-review/", views.lesson_submit_review, name="lesson_submit_review"),
    path("lessons/<int:lesson_id>/quiz/", views.lesson_quiz, name="lesson_quiz"),
    path("lessons/<int:lesson_id>/quick-quiz/add/", views.lesson_quick_quiz_add, name="lesson_quick_quiz_add"),
    path("lessons/<int:lesson_id>/quick-quiz/<int:question_id>/delete/", views.lesson_quick_quiz_delete, name="lesson_quick_quiz_delete"),
    path("quizzes/", views.all_quizzes, name="all_quizzes"),
    path("quizzes/<int:quiz_id>/delete/", views.quiz_delete, name="quiz_delete"),
    path("quizzes/<int:quiz_id>/questions/", views.quiz_questions, name="quiz_questions"),
    path("questions/<int:question_id>/edit/", views.question_edit, name="question_edit"),
    path("questions/<int:question_id>/delete/", views.question_delete, name="question_delete"),
    path("students/", views.students_list, name="students"),
    path("groups/", views.student_groups, name="student_groups"),
    path("students/<int:student_id>/", views.student_detail, name="student_detail"),
    path("students/<int:student_id>/notes/", views.student_note_create, name="student_note_create"),
    path("students/<int:student_id>/certificate/<int:course_id>/", views.issue_certificate, name="issue_certificate"),
    path("notes/<int:note_id>/delete/", views.student_note_delete, name="student_note_delete"),
    path("assignments/", views.assignments_list, name="assignments"),
    path("assignments/create/", views.assignment_create, name="assignment_create"),
    path("assignments/<int:assignment_id>/", views.assignment_detail, name="assignment_detail"),
    path("assignments/<int:assignment_id>/delete/", views.assignment_delete, name="assignment_delete"),
    path("assignments/<int:assignment_id>/submit/", views.assignment_submit, name="assignment_submit"),
    path("submissions/<int:submission_id>/review/", views.submission_review, name="submission_review"),
    path("live-sessions/", views.live_sessions_list, name="live_sessions"),
    path("live-sessions/create/", views.live_session_create, name="live_session_create"),
    path("live-sessions/<int:session_id>/cancel/", views.live_session_cancel, name="live_session_cancel"),
    path("analytics/", views.analytics, name="analytics"),
    path("notifications/", views.notifications, name="notifications"),
    path("settings/", views.settings, name="settings"),

    # Phase 11 — Content Review Dashboard
    path("content-review/",
         views_content_review.content_review_list,
         name="content_review_list"),
    path("content-review/lessons/<int:lesson_id>/",
         views_content_review.content_review_detail,
         name="content_review_detail"),
    path("content-review/lessons/<int:lesson_id>/start-review/",
         views_content_review.action_start_review,
         name="content_review_start_review"),
    path("content-review/lessons/<int:lesson_id>/approve/",
         views_content_review.action_approve,
         name="content_review_approve"),
    path("content-review/lessons/<int:lesson_id>/request-changes/",
         views_content_review.action_request_changes,
         name="content_review_request_changes"),
    path("content-review/lessons/<int:lesson_id>/publish/",
         views_content_review.action_publish,
         name="content_review_publish"),
    path("content-review/lessons/<int:lesson_id>/unpublish/",
         views_content_review.action_unpublish,
         name="content_review_unpublish"),
    path("content-review/lessons/<int:lesson_id>/note/",
         views_content_review.action_add_note,
         name="content_review_add_note"),
    path("content-review/lessons/<int:lesson_id>/set-access/",
         views_content_review.action_set_access,
         name="content_review_set_access"),
]
