# Generated by Django 5.2.14 on 2026-05-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='ar', max_length=2),
        ),
    ]
