# Generated by Django 5.2.14 on 2026-05-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='initial_cefr_level',
            field=models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], help_text='Level at onboarding. `cefr_level` is the live current level.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_path',
            field=models.CharField(blank=True, choices=[('placement_test', 'Placement test'), ('beginner_start', 'Started from beginner')], help_text='Which onboarding path the student picked.', max_length=20),
        ),
    ]
