# Generated by Django 5.2.14 on 2026-05-08 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_initial_cefr_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='cefr_level',
            field=models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], max_length=2, null=True, verbose_name='CEFR level'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email verified'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='initial_cefr_level',
            field=models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], help_text='Level at onboarding. `cefr_level` is the live current level.', max_length=2, null=True, verbose_name='Initial CEFR level'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='Onboarding completed'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Onboarding completed at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='onboarding_path',
            field=models.CharField(blank=True, choices=[('placement_test', 'Placement test'), ('beginner_start', 'Started from beginner')], help_text='Which onboarding path the student picked.', max_length=20, verbose_name='Onboarding path'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='placement_completed',
            field=models.BooleanField(default=False, verbose_name='Placement completed'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='ar', max_length=2, verbose_name='Preferred language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], default='student', max_length=10, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Subscription expires'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscription_status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('pending', 'Pending verification'), ('active', 'Active'), ('expired', 'Expired')], default='inactive', max_length=10, verbose_name='Subscription status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
