# Generated by Django 5.2.14 on 2026-05-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_options_alter_profile_cefr_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Set when an admin issues a temporary password.', verbose_name='Must change password on next login'),
        ),
    ]
