# Generated by Django 5.2.14 on 2026-06-01 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_must_change_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_students', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_students', to=settings.AUTH_USER_MODEL, verbose_name='Rejected by'),
        ),
        migrations.AddField(
            model_name='profile',
            name='approval_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='approval_status',
            field=models.CharField(choices=[('pending_email_verification', 'Pending email verification'), ('pending_admin_approval', 'Pending admin approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending_email_verification', max_length=32, verbose_name='Approval status'),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_user_agent',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='profile',
            name='suspicious_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='suspicious_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StudentApprovalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, default='', max_length=32)),
                ('new_status', models.CharField(blank=True, default='', max_length=32)),
                ('action', models.CharField(choices=[('registered', 'Registered'), ('email_verified', 'Email verified'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('reactivated', 'Reactivated'), ('note_added', 'Note added')], max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=400)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_events', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student approval event',
                'verbose_name_plural': 'Student approval events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_st_user_id_07388b_idx'), models.Index(fields=['action'], name='accounts_st_action_6743b3_idx'), models.Index(fields=['new_status'], name='accounts_st_new_sta_3117bc_idx')],
            },
        ),
    ]
