# Generated by Django 5.2.14 on 2026-05-08 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning_core', '0006_adaptiveexercise_acceptable_answers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('placement', 'Placement exam'), ('lesson_quiz', 'Lesson quiz'), ('weekly_assessment', 'Weekly assessment'), ('monthly_assessment', 'Monthly assessment'), ('level_completion', 'Level completion exam'), ('skill_specific', 'Skill-specific exam'), ('weakness_remediation', 'Weakness remediation'), ('speaking_assessment', 'Speaking assessment'), ('writing_assessment', 'Writing assessment'), ('vocabulary_exam', 'Vocabulary exam'), ('grammar_exam', 'Grammar exam')], max_length=24)),
                ('cefr_level', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], max_length=2)),
                ('skill', models.CharField(blank=True, max_length=20)),
                ('total_questions', models.PositiveSmallIntegerField(default=10)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=15)),
                ('is_adaptive', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('percentage', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('expired', 'Expired')], default='in_progress', max_length=12)),
                ('cefr_result', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], max_length=2)),
                ('feedback', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('feedback', models.TextField(blank=True)),
                ('error_analysis', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_answers', to='learning_core.adaptiveexercise')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examattempt')),
            ],
            options={
                'ordering': ['attempt', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('exam_type', models.CharField(choices=[('placement', 'Placement exam'), ('lesson_quiz', 'Lesson quiz'), ('weekly_assessment', 'Weekly assessment'), ('monthly_assessment', 'Monthly assessment'), ('level_completion', 'Level completion exam'), ('skill_specific', 'Skill-specific exam'), ('weakness_remediation', 'Weakness remediation'), ('speaking_assessment', 'Speaking assessment'), ('writing_assessment', 'Writing assessment'), ('vocabulary_exam', 'Vocabulary exam'), ('grammar_exam', 'Grammar exam')], max_length=24)),
                ('cefr_level', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], max_length=2)),
                ('skill', models.CharField(blank=True, max_length=20)),
                ('total_questions', models.PositiveSmallIntegerField(default=10)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=15)),
                ('difficulty_distribution', models.JSONField(blank=True, default=dict)),
                ('skill_distribution', models.JSONField(blank=True, default=dict)),
                ('question_type_distribution', models.JSONField(blank=True, default=dict)),
                ('passing_score', models.PositiveSmallIntegerField(default=70)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['cefr_level', 'exam_type'],
                'indexes': [models.Index(fields=['exam_type', 'cefr_level'], name='exams_examb_exam_ty_c023ac_idx'), models.Index(fields=['is_active'], name='exams_examb_is_acti_86674e_idx')],
                'constraints': [models.UniqueConstraint(fields=('exam_type', 'cefr_level', 'skill'), name='exam_blueprint_unique_signature')],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='blueprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='exams.examblueprint'),
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_questions', to='learning_core.adaptiveexercise')),
            ],
            options={
                'ordering': ['exam', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionGenerationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=80, unique=True)),
                ('target_count', models.PositiveIntegerField()),
                ('generated_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('cefr_level', models.CharField(blank=True, max_length=2)),
                ('skill', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='pending', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', '-started_at'], name='exams_quest_status_1ce20f_idx'), models.Index(fields=['cefr_level', 'skill'], name='exams_quest_cefr_le_043b1d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['user', '-started_at'], name='exams_exama_user_id_734ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam', '-started_at'], name='exams_exama_exam_id_30a821_idx'),
        ),
        migrations.AddConstraint(
            model_name='examanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='examanswer_unique_question_per_attempt'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_type', 'cefr_level'], name='exams_exam_exam_ty_8912ea_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['-created_at'], name='exams_exam_created_66bfd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(fields=('exam', 'question'), name='examquestion_unique_question_per_exam'),
        ),
    ]
