# Generated by Django 5.2.14 on 2026-05-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.AlterModelOptions(
            name='examanswer',
            options={'ordering': ['attempt', 'created_at'], 'verbose_name': 'Exam answer', 'verbose_name_plural': 'Exam answers'},
        ),
        migrations.AlterModelOptions(
            name='examattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'Exam attempt', 'verbose_name_plural': 'Exam attempts'},
        ),
        migrations.AlterModelOptions(
            name='examblueprint',
            options={'ordering': ['cefr_level', 'exam_type'], 'verbose_name': 'Exam blueprint', 'verbose_name_plural': 'Exam blueprints'},
        ),
        migrations.AlterModelOptions(
            name='examquestion',
            options={'ordering': ['exam', 'order'], 'verbose_name': 'Exam question', 'verbose_name_plural': 'Exam questions'},
        ),
        migrations.AlterModelOptions(
            name='questiongenerationbatch',
            options={'ordering': ['-started_at'], 'verbose_name': 'Question generation batch', 'verbose_name_plural': 'Question generation batches'},
        ),
    ]
