from django.urls import path

from . import views
from . import views_student_approval as approvals
from . import views_media_review as media_review


app_name = "platform_admin"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("student-approvals/", approvals.student_approvals, name="student_approvals"),
    path("student-approvals/bulk/", approvals.student_approval_bulk, name="student_approval_bulk"),
    path("student-approvals/<int:pk>/<slug:action>/", approvals.student_approval_action,
         name="student_approval_action"),
    path("media-review/", media_review.media_review, name="media_review"),
    path("media-review/<slug:media_type>/<int:pk>/<slug:action>/", media_review.media_action,
         name="media_action"),
    path("dashboard/academic/", views.dashboard_academic, name="dashboard_academic"),
    path("dashboard/finance/", views.dashboard_finance, name="dashboard_finance"),
    path("dashboard/support/", views.dashboard_support, name="dashboard_support"),
    path("dashboard/ai/", views.dashboard_ai, name="dashboard_ai"),
    path("dashboard/readonly/", views.dashboard_readonly, name="dashboard_readonly"),
    path("students/", views.students_list, name="students"),
    path("students/<int:pk>/", views.student_detail, name="student_detail"),
    path("students/<int:pk>/<slug:action>/", views.student_action, name="student_action"),
    path("teachers/", views.teachers_list, name="teachers"),
    path("teachers/create/", views.teacher_create, name="teacher_create"),
    path("teachers/<int:pk>/", views.teacher_detail, name="teacher_detail"),
    path("teachers/<int:pk>/<slug:action>/", views.teacher_action, name="teacher_action"),
    path("courses/", views.courses_list, name="courses"),
    path("courses/review/", views.courses_review, name="courses_review"),
    path("courses/<int:pk>/", views.course_detail, name="course_detail"),
    path("courses/<int:pk>/<slug:action>/", views.course_action, name="course_action"),
    path("courses/<int:course_pk>/lessons/new/", views.lesson_editor, name="lesson_create"),
    path("courses/<int:course_pk>/lessons/<int:lesson_pk>/edit/", views.lesson_editor, name="lesson_edit"),
    path("payments/", views.payments_list, name="payments"),
    path("payments/export/", views.payments_export, name="payments_export"),
    path("payments/<int:pk>/", views.payment_detail, name="payment_detail"),
    path("payments/<int:pk>/proof/", views.payment_proof, name="payment_proof"),
    path("payments/<int:pk>/<slug:action>/", views.payment_action, name="payment_action"),
    path("ai/", views.ai_overview, name="ai_overview"),
    path("ai/tutor-logs/", views.ai_tutor_logs, name="ai_tutor_logs"),
    path("ai/datasets/", views.ai_dataset_review, name="ai_datasets"),
    path("ai/datasets/<slug:action>/", views.ai_dataset_action, name="ai_dataset_action"),
    path("ai/model-metrics/", views.ai_model_metrics, name="ai_model_metrics"),
    path("analytics/", views.analytics_overview, name="analytics"),
    path("analytics/learning/", views.analytics_learning, name="analytics_learning"),
    path("analytics/payments/", views.analytics_payments, name="analytics_payments"),
    path("analytics/retention/", views.analytics_retention, name="analytics_retention"),
    path("settings/", views.settings_roles, name="settings_roles"),
    path("settings/notifications/", views.settings_notifications, name="settings_notifications"),
    path("settings/gamification/", views.settings_gamification, name="settings_gamification"),
    path("settings/platform/", views.settings_platform, name="settings_platform"),
    path("audit-logs/", views.audit_logs, name="audit_logs"),
    path("plans/", views.plans_list, name="plans"),
    path("plans/create/", views.plan_create, name="plan_create"),
    path("plans/<int:pk>/edit/", views.plan_edit, name="plan_edit"),
    path("plans/<int:pk>/delete/", views.plan_delete, name="plan_delete"),
    path("payment-methods/", views.payment_methods, name="payment_methods"),
    path("payment-methods/new/", views.payment_method_create, name="payment_method_create"),
    path("payment-methods/<int:pk>/edit/", views.payment_method_edit, name="payment_method_edit"),
    path("payment-methods/<int:pk>/<slug:action>/", views.payment_method_action, name="payment_method_action"),
    path("voices/", views.voices_list, name="voices"),
    path("voices/<int:pk>/toggle/", views.voice_toggle_active, name="voice_toggle"),
    path("avatars/<int:pk>/toggle/", views.avatar_toggle_active, name="avatar_toggle"),
    path("avatars/<int:pk>/image/", views.avatar_upload_image, name="avatar_image_upload"),
    path("gamification/sounds/", views.gamification_sounds, name="gamification_sounds"),
    # Placement question bank — CRUD inside the Control Center.
    path("placement-questions/", views.placement_questions, name="placement_questions"),
    path("placement-questions/new/", views.placement_question_create, name="placement_question_create"),
    path("placement-questions/<int:pk>/edit/", views.placement_question_edit, name="placement_question_edit"),
    path("placement-questions/<int:pk>/<slug:action>/", views.placement_question_action, name="placement_question_action"),
]
