# Generated by Django 5.2.14 on 2026-05-08 23:28

import courses.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], max_length=2, unique=True, verbose_name='CEFR code')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Course level',
                'verbose_name_plural': 'Course levels',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('bilingual', 'Bilingual')], default='bilingual', max_length=10, verbose_name='Language')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16, verbose_name='Status')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='courses/covers/%Y/%m/', validators=[courses.validators.validate_image], verbose_name='Cover image')),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='courses/intros/%Y/%m/', validators=[courses.validators.validate_video], verbose_name='Intro video')),
                ('estimated_duration_hours', models.PositiveSmallIntegerField(default=0, verbose_name='Estimated duration (hours)')),
                ('learning_objectives', models.TextField(blank=True, verbose_name='Learning objectives')),
                ('prerequisites', models.TextField(blank=True, verbose_name='Prerequisites')),
                ('is_free', models.BooleanField(default=False, verbose_name='Free')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed at')),
                ('review_notes', models.TextField(blank=True, verbose_name='Review notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_courses', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_courses', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.courselevel', verbose_name='Level')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course unit',
                'verbose_name_plural': 'Course units',
                'ordering': ['course', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('lesson_type', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('mixed', 'Mixed')], default='mixed', max_length=16, verbose_name='Lesson type')),
                ('cefr_level', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], max_length=2, verbose_name='CEFR level')),
                ('skill', models.CharField(blank=True, choices=[('reading', 'Reading'), ('writing', 'Writing'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('mixed', 'Mixed')], max_length=16, verbose_name='Skill')),
                ('grammar_topic', models.CharField(blank=True, max_length=120, verbose_name='Grammar topic')),
                ('vocabulary_topic', models.CharField(blank=True, max_length=120, verbose_name='Vocabulary topic')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='lessons/video/%Y/%m/', validators=[courses.validators.validate_video], verbose_name='Video file')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='lessons/audio/%Y/%m/', validators=[courses.validators.validate_audio], verbose_name='Audio file')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lessons/pdf/%Y/%m/', validators=[courses.validators.validate_document], verbose_name='PDF file')),
                ('content_html', models.TextField(blank=True, verbose_name='Content')),
                ('transcript', models.TextField(blank=True, verbose_name='Transcript')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='Duration (minutes)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published')], default='draft', max_length=16, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.courseunit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['course', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('passing_score', models.PositiveSmallIntegerField(default=70, verbose_name='Passing score (%)')),
                ('time_limit_minutes', models.PositiveSmallIntegerField(default=0, help_text='0 = no limit', verbose_name='Time limit (minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Lesson quiz',
                'verbose_name_plural': 'Lesson quizzes',
            },
        ),
        migrations.CreateModel(
            name='LessonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('fill_blank', 'Fill in the blank'), ('correction', 'Correction'), ('sentence_ordering', 'Sentence ordering'), ('translation', 'Translation'), ('short_answer', 'Short answer'), ('speaking_prompt', 'Speaking prompt'), ('writing_prompt', 'Writing prompt')], max_length=20, verbose_name='Question type')),
                ('question_text', models.TextField(verbose_name='Question text')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Options')),
                ('correct_answer', models.TextField(blank=True, verbose_name='Correct answer')),
                ('explanation', models.TextField(blank=True, verbose_name='Explanation')),
                ('difficulty_score', models.FloatField(default=0.5, verbose_name='Difficulty (0..1)')),
                ('points', models.PositiveSmallIntegerField(default=1, verbose_name='Points')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.lessonquiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Lesson question',
                'verbose_name_plural': 'Lesson questions',
                'ordering': ['quiz', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('link', 'External link'), ('worksheet', 'Worksheet')], max_length=12, verbose_name='Resource type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('file', models.FileField(blank=True, null=True, upload_to='lessons/resources/%Y/%m/', verbose_name='File')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Lesson resource',
                'verbose_name_plural': 'Lesson resources',
                'ordering': ['lesson', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(help_text='e.g. course.publish, lesson.approve', max_length=40, verbose_name='Action type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_targeting', to=settings.AUTH_USER_MODEL, verbose_name='Target user')),
            ],
            options={
                'verbose_name': 'Admin action log',
                'verbose_name_plural': 'Admin action logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', '-created_at'], name='courses_adm_admin_u_ff27d2_idx'), models.Index(fields=['action_type', '-created_at'], name='courses_adm_action__b1e1fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Submitted by')),
            ],
            options={
                'verbose_name': 'Content review log',
                'verbose_name_plural': 'Content review logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='courses_con_content_c9aa4c_idx'), models.Index(fields=['status', '-created_at'], name='courses_con_status_7d8765_idx'), models.Index(fields=['submitted_by', '-created_at'], name='courses_con_submitt_50cdc5_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=12, verbose_name='Status')),
                ('progress_percentage', models.FloatField(default=0.0, verbose_name='Progress %')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Course enrollment',
                'verbose_name_plural': 'Course enrollments',
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['course', 'status'], name='courses_cou_course__4e6f05_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='course_enrollment_unique_user_course')],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', '-created_at'], name='courses_cou_status_41eebb_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level', 'status'], name='courses_cou_level_i_724841_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher', '-created_at'], name='courses_cou_teacher_e90956_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'order'], name='courses_les_course__dc0bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['status', '-created_at'], name='courses_les_status_e526d8_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['created_by', '-created_at'], name='courses_les_created_e22c4e_idx'),
        ),
    ]
