# Generated by Django 5.2.14 on 2026-05-09 00:40

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a .mp4, .webm or .m4v file. Played first if both this and the URL are set.', null=True, upload_to='lessons/video/%Y/%m/', validators=[courses.validators.validate_video], verbose_name='Video file'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo, or a direct .mp4/.webm link. Used when no file is uploaded or the file is missing.', verbose_name='Video URL'),
        ),
    ]
