# Generated by Django 5.2.14 on 2026-05-11 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_video_file_alter_lesson_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_completed', models.BooleanField(default=False)),
                ('quiz_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quiz_passed', models.BooleanField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course lesson progress',
                'verbose_name_plural': 'Course lesson progress',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-completed_at'], name='courses_cou_user_id_19f54e_idx'), models.Index(fields=['lesson'], name='courses_cou_lesson__ad4b68_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'lesson'), name='courselessonprogress_unique_user_lesson')],
            },
        ),
    ]
