# Generated by Django 5.2.14 on 2026-05-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='Arabic description'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='English description'),
        ),
        migrations.AddField(
            model_name='course',
            name='objectives_ar',
            field=models.TextField(blank=True, verbose_name='Arabic objectives'),
        ),
        migrations.AddField(
            model_name='course',
            name='objectives_en',
            field=models.TextField(blank=True, verbose_name='English objectives'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Arabic title'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='English title'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_ar',
            field=models.TextField(blank=True, verbose_name='Arabic content'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='English content'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Arabic title'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='English title'),
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='explanation_ar',
            field=models.TextField(blank=True, verbose_name='Arabic explanation'),
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='explanation_en',
            field=models.TextField(blank=True, verbose_name='English explanation'),
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='question_text_ar',
            field=models.TextField(blank=True, verbose_name='Arabic question text'),
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='question_text_en',
            field=models.TextField(blank=True, verbose_name='English question text'),
        ),
        migrations.AddField(
            model_name='lessonquiz',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Arabic title'),
        ),
        migrations.AddField(
            model_name='lessonquiz',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='English title'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=16, verbose_name='Status'),
        ),
    ]
