# Generated by Django 5.2.14 on 2026-05-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_description_ar_course_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseunit',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='Arabic description'),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='English description'),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Arabic title'),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='English title'),
        ),
    ]
