# Generated by Django 5.2.14 on 2026-05-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courseunit_description_ar_courseunit_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='drip_enabled',
            field=models.BooleanField(default=True, help_text='Release one lesson per day: the next lesson unlocks only after the previous one is completed and a calendar day has passed. Turn off to open every lesson at once.', verbose_name='Daily lesson unlock'),
        ),
    ]
