# Generated by Django 5.2.14 on 2026-05-28 17:31

import courses.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAudioScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_type', models.CharField(choices=[('intro', 'Intro'), ('vocabulary', 'Vocabulary'), ('examples', 'Examples'), ('dialogue', 'Dialogue'), ('listening', 'Listening'), ('quiz', 'Quiz'), ('speaking', 'Speaking')], db_index=True, max_length=20, verbose_name='Script type')),
                ('script_text', models.TextField(help_text='The English copy to be spoken. Use SSML where helpful.', verbose_name='Script text')),
                ('voice_style', models.CharField(choices=[('friendly_teacher', 'Friendly teacher'), ('slow_beginner', 'Slow beginner'), ('dialogue', 'Dialogue (two voices)')], default='friendly_teacher', max_length=20, verbose_name='Voice style')),
                ('accent', models.CharField(default='american', help_text='General American by default. Other values reserved for future.', max_length=20, verbose_name='Accent')),
                ('generated_audio', models.FileField(blank=True, null=True, upload_to='lessons/audio_scripts/%Y/%m/', validators=[courses.validators.validate_audio], verbose_name='Generated audio')),
                ('is_generated', models.BooleanField(default=False, verbose_name='Generated')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_scripts', to='courses.lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Lesson audio script',
                'verbose_name_plural': 'Lesson audio scripts',
                'ordering': ['lesson', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['lesson', 'script_type'], name='courses_les_lesson__dad03d_idx'), models.Index(fields=['is_generated'], name='courses_les_is_gene_f40f4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='LessonChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(max_length=300, verbose_name='Text (English)')),
                ('text_ar', models.CharField(blank=True, help_text='Optional — falls back to English if blank.', max_length=300, verbose_name='Text (Arabic)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='courses.lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Lesson checklist item',
                'verbose_name_plural': 'Lesson checklist items',
                'ordering': ['lesson', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['lesson', 'sort_order'], name='courses_les_lesson__aab736_idx')],
            },
        ),
        migrations.CreateModel(
            name='LessonImagePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('cover', 'Cover'), ('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('quiz', 'Quiz')], db_index=True, max_length=20, verbose_name='Prompt type')),
                ('prompt', models.TextField(help_text='Free-text image generation prompt — keep style guide rules in mind.', verbose_name='Prompt')),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='lessons/image_prompts/%Y/%m/', validators=[courses.validators.validate_image], verbose_name='Generated image')),
                ('is_generated', models.BooleanField(default=False, verbose_name='Generated')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_prompts', to='courses.lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Lesson image prompt',
                'verbose_name_plural': 'Lesson image prompts',
                'ordering': ['lesson', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['lesson', 'prompt_type'], name='courses_les_lesson__9a3d0a_idx'), models.Index(fields=['is_generated'], name='courses_les_is_gene_b6491a_idx')],
            },
        ),
        migrations.CreateModel(
            name='LessonMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document')], db_index=True, max_length=10, verbose_name='Media type')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title (English)')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='Title (Arabic)')),
                ('file', models.FileField(blank=True, help_text='Optional. An empty row is treated as a placeholder.', null=True, upload_to='lessons/media/%Y/%m/', verbose_name='File')),
                ('external_url', models.URLField(blank=True, max_length=500, verbose_name='External URL')),
                ('language', models.CharField(blank=True, choices=[('', 'Universal / language-neutral'), ('en', 'English'), ('ar', 'Arabic')], default='', max_length=2, verbose_name='Language')),
                ('alt_text', models.CharField(blank=True, max_length=300, verbose_name='Alt text')),
                ('transcript', models.TextField(blank=True, verbose_name='Transcript')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Duration (seconds)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('generated_by_ai', models.BooleanField(default=False, verbose_name='Generated by AI')),
                ('generation_prompt', models.TextField(blank=True, help_text='Prompt text used when AI-generated. Empty for uploads.', verbose_name='Generation prompt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='courses.lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Lesson media',
                'verbose_name_plural': 'Lesson media',
                'ordering': ['lesson', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['lesson', 'media_type'], name='courses_les_lesson__a9dc24_idx'), models.Index(fields=['lesson', 'sort_order'], name='courses_les_lesson__3d9531_idx'), models.Index(fields=['is_active'], name='courses_les_is_acti_c3cce6_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], db_index=True, max_length=10, verbose_name='Media type')),
                ('file', models.FileField(blank=True, null=True, upload_to='lessons/questions/%Y/%m/', verbose_name='File')),
                ('external_url', models.URLField(blank=True, max_length=500, verbose_name='External URL')),
                ('alt_text', models.CharField(blank=True, max_length=300, verbose_name='Alt text')),
                ('transcript', models.TextField(blank=True, verbose_name='Transcript')),
                ('language', models.CharField(blank=True, choices=[('', 'Universal / language-neutral'), ('en', 'English'), ('ar', 'Arabic')], default='', max_length=2, verbose_name='Language')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('generation_prompt', models.TextField(blank=True, verbose_name='Generation prompt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='courses.lessonquestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Question media',
                'verbose_name_plural': 'Question media',
                'ordering': ['question', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['question', 'media_type'], name='courses_que_questio_e302eb_idx')],
            },
        ),
    ]
