# Generated by Django 5.2.14 on 2026-05-28 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lesson_media_scripts_and_checklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='Title (Arabic)')),
                ('start_unit_number', models.PositiveSmallIntegerField(verbose_name='Start unit number')),
                ('end_unit_number', models.PositiveSmallIntegerField(verbose_name='End unit number')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions (English)')),
                ('instructions_ar', models.TextField(blank=True, verbose_name='Instructions (Arabic)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course review',
                'verbose_name_plural': 'Course reviews',
                'ordering': ['course', 'start_unit_number'],
            },
        ),
        migrations.CreateModel(
            name='CourseReviewAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Score (%)')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('feedback_ar', models.TextField(blank=True, verbose_name='Feedback (Arabic)')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.coursereview', verbose_name='Review')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_review_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Course review attempt',
                'verbose_name_plural': 'Course review attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseReviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('fill_blank', 'Fill in the blank'), ('correction', 'Correction'), ('sentence_ordering', 'Sentence ordering'), ('translation', 'Translation'), ('short_answer', 'Short answer'), ('speaking_prompt', 'Speaking prompt'), ('writing_prompt', 'Writing prompt')], max_length=20, verbose_name='Question type')),
                ('question_text', models.TextField(verbose_name='Question text')),
                ('question_text_ar', models.TextField(blank=True, verbose_name='Question text (Arabic)')),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('explanation_ar', models.TextField(blank=True)),
                ('skill', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('reading', 'Reading'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('writing', 'Writing')], default='vocabulary', max_length=20, verbose_name='Skill')),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.coursereview', verbose_name='Review')),
            ],
            options={
                'verbose_name': 'Course review question',
                'verbose_name_plural': 'Course review questions',
                'ordering': ['review', 'order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.UniqueConstraint(fields=('course', 'start_unit_number', 'end_unit_number'), name='course_review_unique_range'),
        ),
        migrations.AddIndex(
            model_name='coursereviewattempt',
            index=models.Index(fields=['student', 'review'], name='courses_cou_student_8e318b_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereviewattempt',
            index=models.Index(fields=['review', '-completed_at'], name='courses_cou_review__0017bb_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereviewquestion',
            index=models.Index(fields=['review', 'skill'], name='courses_cou_review__06f00b_idx'),
        ),
    ]
