# Generated by Django 5.2.14 on 2026-05-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonquestion',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Per-question_type payload — sentence_ordering: words/correct_order, frequency_scale: scale_items, table_sentence_builder: columns/rows, listening_match: pairs/audio_status, speaking_sentence_builder: student_prompt/ai_tutor_instruction, question_transform: statement/target_qword.', verbose_name='Type-specific metadata'),
        ),
        migrations.AlterField(
            model_name='coursereviewquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('fill_blank', 'Fill in the blank'), ('correction', 'Correction'), ('sentence_ordering', 'Sentence ordering'), ('translation', 'Translation'), ('short_answer', 'Short answer'), ('speaking_prompt', 'Speaking prompt'), ('writing_prompt', 'Writing prompt'), ('frequency_scale', 'Frequency scale'), ('table_sentence_builder', 'Table sentence builder'), ('listening_match', 'Listening match'), ('speaking_sentence_builder', 'Speaking sentence builder'), ('question_transform', 'Question transform (How often / When)')], max_length=32, verbose_name='Question type'),
        ),
        migrations.AlterField(
            model_name='lessonquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('fill_blank', 'Fill in the blank'), ('correction', 'Correction'), ('sentence_ordering', 'Sentence ordering'), ('translation', 'Translation'), ('short_answer', 'Short answer'), ('speaking_prompt', 'Speaking prompt'), ('writing_prompt', 'Writing prompt'), ('frequency_scale', 'Frequency scale'), ('table_sentence_builder', 'Table sentence builder'), ('listening_match', 'Listening match'), ('speaking_sentence_builder', 'Speaking sentence builder'), ('question_transform', 'Question transform (How often / When)')], max_length=32, verbose_name='Question type'),
        ),
    ]
