# Generated by Django 5.2.14 on 2026-05-29 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_quiz_engine_metadata_and_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed — out of hearts'), ('abandoned', 'Abandoned')], db_index=True, default='started', max_length=12, verbose_name='Status')),
                ('question_ids', models.JSONField(blank=True, default=list, verbose_name='Question id sequence')),
                ('current_question_index', models.PositiveSmallIntegerField(default=0, verbose_name='Current question index (0-based)')),
                ('total_questions', models.PositiveSmallIntegerField(default=0, verbose_name='Total questions in this session')),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('wrong_count', models.PositiveSmallIntegerField(default=0)),
                ('hearts_total', models.PositiveSmallIntegerField(default=5)),
                ('hearts_remaining', models.PositiveSmallIntegerField(default=5)),
                ('xp_earned', models.PositiveIntegerField(default=0, verbose_name='XP earned this session')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_sessions', to='courses.lesson', verbose_name='Lesson')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_sessions', to='courses.lessonquiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Challenge session',
                'verbose_name_plural': 'Challenge sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('xp_awarded', models.PositiveSmallIntegerField(default=0)),
                ('heart_lost', models.BooleanField(default=False)),
                ('feedback_en', models.TextField(blank=True)),
                ('feedback_ar', models.TextField(blank=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_answers', to='courses.lessonquestion', verbose_name='Question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.challengesession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Challenge answer',
                'verbose_name_plural': 'Challenge answers',
                'ordering': ['session', 'answered_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='challengesession',
            index=models.Index(fields=['user', 'lesson'], name='courses_cha_user_id_1b434b_idx'),
        ),
        migrations.AddIndex(
            model_name='challengesession',
            index=models.Index(fields=['status', '-updated_at'], name='courses_cha_status_cd86ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='challengesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['started', 'in_progress'])), fields=('user', 'lesson'), name='challenge_session_one_active_per_user_lesson'),
        ),
        migrations.AddIndex(
            model_name='challengeanswer',
            index=models.Index(fields=['session', 'question'], name='courses_cha_session_227dd0_idx'),
        ),
        migrations.AddConstraint(
            model_name='challengeanswer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='challenge_answer_unique_session_question'),
        ),
    ]
