# Generated by Django 5.2.14 on 2026-05-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_challenge_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereviewquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('fill_blank', 'Fill in the blank'), ('correction', 'Correction'), ('sentence_ordering', 'Sentence ordering'), ('translation', 'Translation'), ('short_answer', 'Short answer'), ('speaking_prompt', 'Speaking prompt'), ('writing_prompt', 'Writing prompt'), ('frequency_scale', 'Frequency scale'), ('table_sentence_builder', 'Table sentence builder'), ('listening_match', 'Listening match'), ('speaking_sentence_builder', 'Speaking sentence builder'), ('question_transform', 'Question transform'), ('tap_choice', 'Tap choice'), ('image_choice', 'Image choice'), ('listen_and_choose', 'Listen and choose'), ('listen_and_type', 'Listen and type'), ('sound_to_word', 'Sound to word'), ('picture_labeling', 'Picture labeling'), ('mini_story_choice', 'Mini story choice'), ('word_bank_sentence', 'Word bank sentence'), ('match_pairs', 'Match pairs'), ('fill_blank_card', 'Fill blank card'), ('conversation_reply', 'Conversation reply'), ('mistake_correction', 'Mistake correction'), ('translate_to_english', 'Translate to English'), ('translate_to_arabic', 'Translate to Arabic'), ('speak_this_sentence', 'Speak this sentence'), ('pronunciation_check', 'Pronunciation check'), ('ai_roleplay_prompt', 'AI roleplay prompt')], max_length=32, verbose_name='Question type'),
        ),
        migrations.AlterField(
            model_name='lessonquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('fill_blank', 'Fill in the blank'), ('correction', 'Correction'), ('sentence_ordering', 'Sentence ordering'), ('translation', 'Translation'), ('short_answer', 'Short answer'), ('speaking_prompt', 'Speaking prompt'), ('writing_prompt', 'Writing prompt'), ('frequency_scale', 'Frequency scale'), ('table_sentence_builder', 'Table sentence builder'), ('listening_match', 'Listening match'), ('speaking_sentence_builder', 'Speaking sentence builder'), ('question_transform', 'Question transform'), ('tap_choice', 'Tap choice'), ('image_choice', 'Image choice'), ('listen_and_choose', 'Listen and choose'), ('listen_and_type', 'Listen and type'), ('sound_to_word', 'Sound to word'), ('picture_labeling', 'Picture labeling'), ('mini_story_choice', 'Mini story choice'), ('word_bank_sentence', 'Word bank sentence'), ('match_pairs', 'Match pairs'), ('fill_blank_card', 'Fill blank card'), ('conversation_reply', 'Conversation reply'), ('mistake_correction', 'Mistake correction'), ('translate_to_english', 'Translate to English'), ('translate_to_arabic', 'Translate to Arabic'), ('speak_this_sentence', 'Speak this sentence'), ('pronunciation_check', 'Pronunciation check'), ('ai_roleplay_prompt', 'AI roleplay prompt')], max_length=32, verbose_name='Question type'),
        ),
    ]
