# Generated by Django 5.2.14 on 2026-05-30 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_question_types_phase3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quality_flags',
            field=models.JSONField(blank=True, default=list, verbose_name='Latest quality flag list'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quality_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Latest quality score (0-100)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('in_review', 'In review'), ('changes_requested', 'Changes requested'), ('approved', 'Approved (not yet published)'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='LessonReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, help_text='Status before this action (empty for notes/quality).', max_length=20)),
                ('to_status', models.CharField(blank=True, help_text='Status after this action (empty when unchanged).', max_length=20)),
                ('action', models.CharField(choices=[('start_review', 'Start review'), ('approve', 'Approve'), ('request_changes', 'Request changes'), ('reject', 'Reject'), ('publish', 'Publish'), ('unpublish', 'Unpublish'), ('archive', 'Archive'), ('note_added', 'Note added'), ('quality_check', 'Quality check')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('quality_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_actions', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_events', to='courses.lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Lesson review event',
                'verbose_name_plural': 'Lesson review events',
                'ordering': ['lesson', '-created_at'],
                'indexes': [models.Index(fields=['lesson', '-created_at'], name='courses_les_lesson__db8b75_idx'), models.Index(fields=['actor', '-created_at'], name='courses_les_actor_i_1cab76_idx'), models.Index(fields=['action'], name='courses_les_action_97843a_idx')],
            },
        ),
    ]
