# Generated by Django 5.2.14 on 2026-06-01 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_usage', '0003_alter_aiusagelog_feature'),
        ('courses', '0014_lesson_approved_at_lesson_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonaudioscript',
            name='ai_usage_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai_usage.aiusagelog'),
        ),
        migrations.AddField(
            model_name='lessonaudioscript',
            name='gen_error_message',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='lessonaudioscript',
            name='gen_model_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='lessonaudioscript',
            name='gen_provider',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='lessonaudioscript',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonaudioscript',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lessonaudioscript',
            name='generation_status',
            field=models.CharField(choices=[('pending_generation', 'Pending generation'), ('generated', 'Generated'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='pending_generation', max_length=20),
        ),
        migrations.AddField(
            model_name='lessonaudioscript',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lessonaudioscript',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonaudioscript',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonimageprompt',
            name='ai_usage_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai_usage.aiusagelog'),
        ),
        migrations.AddField(
            model_name='lessonimageprompt',
            name='gen_error_message',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='lessonimageprompt',
            name='gen_model_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='lessonimageprompt',
            name='gen_provider',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='lessonimageprompt',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonimageprompt',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lessonimageprompt',
            name='generation_status',
            field=models.CharField(choices=[('pending_generation', 'Pending generation'), ('generated', 'Generated'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='pending_generation', max_length=20),
        ),
        migrations.AddField(
            model_name='lessonimageprompt',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lessonimageprompt',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonimageprompt',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
