# Generated by Django 5.2.14 on 2026-06-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_digitalcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='book_page',
            field=models.PositiveIntegerField(blank=True, help_text='Page in the source course book.', null=True, verbose_name='Book page'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='book_reference',
            field=models.CharField(blank=True, help_text='Free-text source reference (book title / edition).', max_length=255, verbose_name='Book reference'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='book_unit_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Source unit number in the course book (e.g. 1–48).', null=True, verbose_name='Book unit number'),
        ),
    ]
