# Generated by Django 5.2.14 on 2026-06-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_lesson_book_page_lesson_book_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='access_override',
            field=models.CharField(choices=[('inherit', 'Inherit from course'), ('free', 'Free — always open'), ('locked', 'Locked — subscription required')], db_index=True, default='inherit', help_text="Per-lesson lock/unlock. 'Inherit' follows the course's free/paid rule.", max_length=12, verbose_name='Access override'),
        ),
    ]
