# Generated by Django 5.2.14 on 2026-05-07 14:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('pronunciation', 'Pronunciation'), ('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=20)),
                ('cefr_level', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'cefr_level', 'name'],
                'indexes': [models.Index(fields=['category', 'cefr_level'], name='learning_co_categor_7810a0_idx'), models.Index(fields=['is_active'], name='learning_co_is_acti_459da7_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'category', 'cefr_level'), name='unique_skill_name_category_level')],
            },
        ),
        migrations.CreateModel(
            name='GrammarTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('cefr_level', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_skills', models.ManyToManyField(blank=True, related_name='grammar_topics', to='learning_core.skill')),
            ],
            options={
                'ordering': ['cefr_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdaptiveExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cefr_level', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('difficulty_score', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('fill_blank', 'Fill in the blank'), ('correction', 'Correction'), ('sentence_building', 'Sentence building'), ('translation', 'Translation'), ('short_answer', 'Short answer')], max_length=20)),
                ('question', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='learning_core.grammartopic')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='learning_core.skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='learning_core.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_masteries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-mastery_score', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentLearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_cefr_level', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('theta_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-3.0), django.core.validators.MaxValueValidator(3.0)])),
                ('learning_speed', models.FloatField(default=1.0)),
                ('confidence_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('placement', 'Placement'), ('quiz', 'Quiz'), ('tutor', 'Tutor'), ('writing', 'Writing'), ('speaking', 'Speaking'), ('exercise', 'Exercise')], max_length=20)),
                ('original_text', models.TextField(blank=True)),
                ('corrected_text', models.TextField(blank=True)),
                ('error_type', models.CharField(choices=[('grammar', 'Grammar'), ('spelling', 'Spelling'), ('vocabulary', 'Vocabulary'), ('punctuation', 'Punctuation'), ('word_order', 'Word order'), ('pronunciation', 'Pronunciation'), ('comprehension', 'Comprehension')], max_length=20)),
                ('severity', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('explanation', models.TextField(blank=True)),
                ('ai_confidence', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grammar_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_errors', to='learning_core.grammartopic')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_errors', to='learning_core.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weakness_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('frequency', models.PositiveIntegerField(default=0)),
                ('severity_average', models.FloatField(default=0.0)),
                ('recency_score', models.FloatField(default=0.0)),
                ('priority_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('improving', 'Improving'), ('resolved', 'Resolved')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grammar_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weaknesses', to='learning_core.grammartopic')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weaknesses', to='learning_core.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority_score', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('practice_skill', 'Practice skill'), ('review_topic', 'Review grammar topic'), ('continue_lesson', 'Continue lesson'), ('ask_tutor', 'Ask AI tutor'), ('retake_placement', 'Retake placement'), ('speaking_drill', 'Speaking drill'), ('writing_drill', 'Writing drill')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('dismissed', 'Dismissed'), ('replaced', 'Replaced')], default='pending', max_length=15)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_recommendations', to=settings.AUTH_USER_MODEL)),
                ('related_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='learning_core.skill')),
                ('related_weakness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='learning_core.userweakness')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning_core.adaptiveexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='learning_co_user_id_e29b10_idx'), models.Index(fields=['is_correct'], name='learning_co_is_corr_125c92_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='grammartopic',
            index=models.Index(fields=['cefr_level'], name='learning_co_cefr_le_cbe814_idx'),
        ),
        migrations.AddIndex(
            model_name='grammartopic',
            index=models.Index(fields=['is_active'], name='learning_co_is_acti_884f73_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptiveexercise',
            index=models.Index(fields=['cefr_level'], name='learning_co_cefr_le_8e1a05_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptiveexercise',
            index=models.Index(fields=['question_type'], name='learning_co_questio_8718f2_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptiveexercise',
            index=models.Index(fields=['difficulty_score'], name='learning_co_difficu_faca1d_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptiveexercise',
            index=models.Index(fields=['generated_by_ai'], name='learning_co_generat_f4d3af_idx'),
        ),
        migrations.AddIndex(
            model_name='skillmastery',
            index=models.Index(fields=['user', 'skill'], name='learning_co_user_id_d012dd_idx'),
        ),
        migrations.AddIndex(
            model_name='skillmastery',
            index=models.Index(fields=['mastery_score'], name='learning_co_mastery_ed0a8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='skillmastery',
            constraint=models.UniqueConstraint(fields=('user', 'skill'), name='unique_user_skill_mastery'),
        ),
        migrations.AddIndex(
            model_name='studentlearningprofile',
            index=models.Index(fields=['current_cefr_level'], name='learning_co_current_8c3642_idx'),
        ),
        migrations.AddIndex(
            model_name='studentlearningprofile',
            index=models.Index(fields=['theta_score'], name='learning_co_theta_s_8914ce_idx'),
        ),
        migrations.AddIndex(
            model_name='usererror',
            index=models.Index(fields=['user', '-created_at'], name='learning_co_user_id_5cbb99_idx'),
        ),
        migrations.AddIndex(
            model_name='usererror',
            index=models.Index(fields=['error_type'], name='learning_co_error_t_07d39d_idx'),
        ),
        migrations.AddIndex(
            model_name='usererror',
            index=models.Index(fields=['source_type'], name='learning_co_source__efa9ce_idx'),
        ),
        migrations.AddIndex(
            model_name='userweakness',
            index=models.Index(fields=['user', 'status'], name='learning_co_user_id_ec56ba_idx'),
        ),
        migrations.AddIndex(
            model_name='userweakness',
            index=models.Index(fields=['priority_score'], name='learning_co_priorit_9c8752_idx'),
        ),
        migrations.AddIndex(
            model_name='userweakness',
            index=models.Index(fields=['weakness_score'], name='learning_co_weaknes_a4e52a_idx'),
        ),
        migrations.AddConstraint(
            model_name='userweakness',
            constraint=models.UniqueConstraint(fields=('user', 'skill', 'grammar_topic'), name='unique_user_skill_topic_weakness'),
        ),
        migrations.AddIndex(
            model_name='learningrecommendation',
            index=models.Index(fields=['user', 'status'], name='learning_co_user_id_c87be6_idx'),
        ),
        migrations.AddIndex(
            model_name='learningrecommendation',
            index=models.Index(fields=['priority'], name='learning_co_priorit_24130d_idx'),
        ),
    ]
