# Generated by Django 5.2.14 on 2026-05-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptiveexercise',
            name='cefr_level',
            field=models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='grammartopic',
            name='cefr_level',
            field=models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='skill',
            name='cefr_level',
            field=models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='studentlearningprofile',
            name='current_cefr_level',
            field=models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], max_length=2),
        ),
    ]
