# Generated by Django 5.2.14 on 2026-05-07 16:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_core', '0002_alter_adaptiveexercise_cefr_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningrecommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('practice_skill', 'Practice skill'), ('review_topic', 'Review grammar topic'), ('continue_lesson', 'Continue lesson'), ('ask_tutor', 'Ask AI tutor'), ('retake_placement', 'Retake placement'), ('speaking_drill', 'Speaking drill'), ('writing_drill', 'Writing drill'), ('weekly_assessment', 'Take weekly assessment')], max_length=30),
        ),
        migrations.CreateModel(
            name='WeeklyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_after_lessons_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=15)),
                ('score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercises', models.ManyToManyField(blank=True, related_name='weekly_assessments', to='learning_core.adaptiveexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='learning_co_user_id_e435ad_idx'), models.Index(fields=['-created_at'], name='learning_co_created_825621_idx')],
            },
        ),
    ]
