# Generated by Django 5.2.14 on 2026-05-07 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_core', '0003_alter_learningrecommendation_recommendation_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyassessment',
            name='kind',
            field=models.CharField(choices=[('daily', 'Daily check-in'), ('weekly', 'Weekly assessment'), ('milestone', 'Milestone')], default='weekly', max_length=15),
        ),
        migrations.AddIndex(
            model_name='weeklyassessment',
            index=models.Index(fields=['user', 'kind', '-created_at'], name='learning_co_user_id_d59099_idx'),
        ),
    ]
