# Generated by Django 5.2.14 on 2026-05-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_core', '0005_alter_adaptiveexercise_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptiveexercise',
            name='acceptable_answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adaptiveexercise',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Deterministic identifier — enables idempotent bulk generation.', max_length=160),
        ),
        migrations.AddField(
            model_name='adaptiveexercise',
            name='estimated_time_seconds',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='adaptiveexercise',
            name='feedback_correct',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adaptiveexercise',
            name='feedback_wrong',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adaptiveexercise',
            name='generated_by',
            field=models.CharField(choices=[('template', 'Template'), ('ai', 'AI'), ('manual', 'Manual'), ('imported', 'Imported')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='adaptiveexercise',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adaptiveexercise',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adaptiveexercise',
            name='language',
            field=models.CharField(default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='adaptiveexercise',
            name='points',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='adaptiveexercise',
            name='quality_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='0..100. Computed by question_quality service.'),
        ),
        migrations.AddField(
            model_name='adaptiveexercise',
            name='text_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-1 of normalised question text — used for duplicate detection.', max_length=40),
        ),
        migrations.AddField(
            model_name='adaptiveexercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='adaptiveexercise',
            index=models.Index(fields=['is_active', 'is_reviewed'], name='learning_co_is_acti_b4f612_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptiveexercise',
            index=models.Index(fields=['cefr_level', 'question_type', 'is_active'], name='learning_co_cefr_le_93e604_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptiveexercise',
            index=models.Index(fields=['generated_by'], name='learning_co_generat_597dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptiveexercise',
            index=models.Index(fields=['quality_score'], name='learning_co_quality_08b022_idx'),
        ),
        migrations.AddConstraint(
            model_name='adaptiveexercise',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('code',), name='adaptive_exercise_unique_code'),
        ),
    ]
