# Generated by Django 5.2.14 on 2026-05-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_core', '0006_adaptiveexercise_acceptable_answers_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adaptiveexercise',
            index=models.Index(condition=models.Q(('is_active', True), ('is_reviewed', True)), fields=['cefr_level', 'question_type'], name='adex_assembly_hot_idx'),
        ),
    ]
