# Generated by Django 5.2.14 on 2026-05-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_core', '0007_adaptiveexercise_adex_assembly_hot_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adaptiveexercise',
            options={'ordering': ['-created_at'], 'verbose_name': 'Adaptive exercise', 'verbose_name_plural': 'Adaptive exercises'},
        ),
        migrations.AlterModelOptions(
            name='exerciseattempt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exercise attempt', 'verbose_name_plural': 'Exercise attempts'},
        ),
        migrations.AlterModelOptions(
            name='grammartopic',
            options={'ordering': ['cefr_level', 'name'], 'verbose_name': 'Grammar topic', 'verbose_name_plural': 'Grammar topics'},
        ),
        migrations.AlterModelOptions(
            name='learningrecommendation',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Learning recommendation', 'verbose_name_plural': 'Learning recommendations'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'cefr_level', 'name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='skillmastery',
            options={'ordering': ['-mastery_score', '-updated_at'], 'verbose_name': 'Skill mastery', 'verbose_name_plural': 'Skill masteries'},
        ),
        migrations.AlterModelOptions(
            name='studentlearningprofile',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Student learning profile', 'verbose_name_plural': 'Student learning profiles'},
        ),
        migrations.AlterModelOptions(
            name='usererror',
            options={'ordering': ['-created_at'], 'verbose_name': 'User error', 'verbose_name_plural': 'User errors'},
        ),
        migrations.AlterModelOptions(
            name='userweakness',
            options={'ordering': ['-priority_score', '-updated_at'], 'verbose_name': 'User weakness', 'verbose_name_plural': 'User weaknesses'},
        ),
        migrations.AlterModelOptions(
            name='weeklyassessment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Weekly assessment', 'verbose_name_plural': 'Weekly assessments'},
        ),
    ]
