# Generated by Django 5.2.14 on 2026-05-29 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_question_types_phase3'),
        ('learning_core', '0008_alter_adaptiveexercise_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasteryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Mastery event',
                'verbose_name_plural': 'Mastery events',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistake_type', models.CharField(choices=[('wrong_choice', 'Wrong choice'), ('spelling', 'Spelling'), ('word_order', 'Word order'), ('grammar', 'Grammar'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('translation', 'Translation'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('user_answer', models.TextField(blank=True)),
                ('correct_answer', models.TextField(blank=True)),
                ('explanation_en', models.TextField(blank=True)),
                ('explanation_ar', models.TextField(blank=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('mastered', models.BooleanField(default=False)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student mistake',
                'verbose_name_plural': 'Student mistakes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['sort_order', 'category', 'cefr_level', 'name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='skill',
            name='code',
            field=models.SlugField(blank=True, help_text="snake_case identifier — e.g. 'greetings'.", max_length=80, null=True, unique=True, verbose_name='Skill code'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='title_ar',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='skill',
            name='title_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skillmastery',
            name='confidence_level',
            field=models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('improving', 'Improving'), ('strong', 'Strong'), ('mastered', 'Mastered')], default='new', max_length=12),
        ),
        migrations.AddField(
            model_name='skillmastery',
            name='current_streak_correct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skillmastery',
            name='current_streak_wrong',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skillmastery',
            name='next_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['code'], name='learning_co_code_c801dc_idx'),
        ),
        migrations.AddIndex(
            model_name='skillmastery',
            index=models.Index(fields=['next_review_at'], name='learning_co_next_re_db8942_idx'),
        ),
        migrations.AddField(
            model_name='masteryevent',
            name='challenge_answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_event', to='courses.challengeanswer'),
        ),
        migrations.AddField(
            model_name='masteryevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentmistake',
            name='challenge_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_mistakes', to='courses.challengeanswer'),
        ),
        migrations.AddField(
            model_name='studentmistake',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_mistakes', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='studentmistake',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mistakes', to='courses.lessonquestion'),
        ),
        migrations.AddField(
            model_name='studentmistake',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_mistakes', to='learning_core.skill'),
        ),
        migrations.AddField(
            model_name='studentmistake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mistakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='masteryevent',
            index=models.Index(fields=['user', '-processed_at'], name='learning_co_user_id_8f30cb_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmistake',
            index=models.Index(fields=['user', 'mastered', 'next_review_at'], name='learning_co_user_id_8203e8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmistake',
            index=models.Index(fields=['user', 'skill'], name='learning_co_user_id_d44848_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmistake',
            index=models.Index(fields=['next_review_at'], name='learning_co_next_re_166481_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentmistake',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='learning_core_unique_user_question_mistake'),
        ),
    ]
