# Generated by Django 5.2.14 on 2026-06-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_core', '0009_masteryevent_studentmistake_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptiveexercise',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('fill_blank', 'Fill in the blank'), ('correction', 'Correction'), ('sentence_building', 'Sentence building'), ('translation', 'Translation'), ('short_answer', 'Short answer'), ('picture_word', 'Picture → word'), ('picture_verb', 'Picture → verb'), ('picture_adjective', 'Picture → adjective')], max_length=32),
        ),
    ]
