# Generated by Django 5.2.14 on 2026-05-09 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='speech/%Y/%m/', verbose_name='Audio file')),
                ('transcript', models.TextField(blank=True, verbose_name='Transcript')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Duration (seconds)')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Confidence')),
                ('source', models.CharField(choices=[('tutor', 'AI Tutor'), ('placement', 'Placement'), ('lesson', 'Lesson'), ('exam', 'Exam')], default='tutor', max_length=15, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_attempts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Speaking attempt',
                'verbose_name_plural': 'Speaking attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='speech_spea_user_id_31d291_idx'), models.Index(fields=['source', '-created_at'], name='speech_spea_source_bacc35_idx')],
            },
        ),
    ]
