# Generated by Django 5.2.14 on 2026-05-17 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_course_description_ar_course_description_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='Arabic title')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='English title')),
                ('instructions_ar', models.TextField(blank=True, verbose_name='Arabic instructions')),
                ('instructions_en', models.TextField(blank=True, verbose_name='English instructions')),
                ('assignment_type', models.CharField(choices=[('writing', 'Writing'), ('speaking', 'Speaking'), ('quiz', 'Quiz'), ('reading', 'Reading'), ('custom', 'Custom')], default='custom', max_length=16, verbose_name='Assignment type')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due date')),
                ('xp_reward', models.PositiveSmallIntegerField(default=0, verbose_name='XP reward')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='courses.course', verbose_name='Course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_assignments', to='courses.lesson', verbose_name='Lesson')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Teacher assignment',
                'verbose_name_plural': 'Teacher assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='Text answer')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='assignments/audio/%Y/%m/')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/files/%Y/%m/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Score')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('needs_revision', 'Needs revision')], db_index=True, default='submitted', max_length=16, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='teacher_portal.teacherassignment', verbose_name='Assignment')),
            ],
            options={
                'verbose_name': 'Student assignment submission',
                'verbose_name_plural': 'Student assignment submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_ar', models.TextField(blank=True, verbose_name='Arabic bio')),
                ('bio_en', models.TextField(blank=True, verbose_name='English bio')),
                ('specialization', models.CharField(blank=True, max_length=160, verbose_name='Specialization')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='teachers/avatars/%Y/%m/')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Teacher profile',
                'verbose_name_plural': 'Teacher profiles',
                'ordering': ['user__email', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='TeacherStudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Note')),
                ('visibility', models.CharField(choices=[('teacher_only', 'Teacher only'), ('student_visible', 'Student visible'), ('academic_admin_visible', 'Academic admin visible')], default='teacher_only', max_length=24, verbose_name='Visibility')),
                ('needs_support', models.BooleanField(default=False, verbose_name='Needs support')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_student_notes', to='courses.course', verbose_name='Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes_received', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes_authored', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Teacher student note',
                'verbose_name_plural': 'Teacher student notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['teacher', '-created_at'], name='teacher_por_teacher_32177e_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['course', 'is_active'], name='teacher_por_course__1ce5e3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassignmentsubmission',
            index=models.Index(fields=['student', '-submitted_at'], name='teacher_por_student_34d082_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassignmentsubmission',
            index=models.Index(fields=['assignment', 'status'], name='teacher_por_assignm_656b6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentassignmentsubmission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_submission_per_assignment_student'),
        ),
        migrations.AddIndex(
            model_name='teacherstudentnote',
            index=models.Index(fields=['teacher', '-created_at'], name='teacher_por_teacher_2c41e3_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherstudentnote',
            index=models.Index(fields=['student', 'course'], name='teacher_por_student_53c695_idx'),
        ),
    ]
