# Generated by Django 5.2.14 on 2026-06-03 15:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='cefr_focus',
            field=models.CharField(blank=True, help_text='Comma-separated levels, e.g. A0,A1,A2. Blank = all levels.', max_length=64, verbose_name='CEFR focus'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='commission_rate',
            field=models.PositiveIntegerField(default=30, help_text='Percent the platform keeps; the teacher receives the remainder.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Platform commission rate (%)'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='hourly_rate_sdg',
            field=models.PositiveIntegerField(default=0, verbose_name='Hourly rate (SDG)'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Featured'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
        migrations.CreateModel(
            name='StudentTeacherRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('cefr_level_at_selection', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_relations', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relations', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Student–teacher relation',
                'verbose_name_plural': 'Student–teacher relations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'is_active'], name='teacher_por_student_c86577_idx')],
            },
        ),
    ]
