# Generated by Django 5.2.14 on 2026-06-03 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_lessonaudioscript_ai_usage_log_and_more'),
        ('teacher_portal', '0002_teacherprofile_cefr_focus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('scheduled_at', models.DateTimeField(verbose_name='Scheduled at')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Duration (minutes)')),
                ('meet_link', models.URLField(blank=True, verbose_name='Google Meet link')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=10, verbose_name='Status')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='courses.course', verbose_name='Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Live session',
                'verbose_name_plural': 'Live sessions',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['teacher', 'scheduled_at'], name='teacher_por_teacher_ee99de_idx'), models.Index(fields=['status', 'scheduled_at'], name='teacher_por_status_ee9124_idx')],
            },
        ),
    ]
