# Generated by Django 5.2.14 on 2026-06-04 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_portal', '0003_livesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentteacherrelation',
            constraint=models.UniqueConstraint(fields=('student', 'teacher'), name='uniq_student_teacher_relation'),
        ),
    ]
