# Generated by Django 5.2.13 on 2026-05-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DictionaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english", models.CharField(db_index=True, max_length=80)),
                ("arabic", models.CharField(db_index=True, max_length=80)),
                (
                    "pos",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("noun", "Noun"),
                            ("verb", "Verb"),
                            ("adj", "Adjective"),
                            ("adv", "Adverb"),
                            ("prep", "Preposition"),
                            ("phrase", "Phrase"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("example_en", models.CharField(blank=True, max_length=300)),
                ("example_ar", models.CharField(blank=True, max_length=300)),
                ("notes", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("curated", "Curated"), ("ai", "AI-generated")],
                        default="curated",
                        max_length=20,
                    ),
                ),
                ("lookup_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["english"],
                "unique_together": {("english", "arabic")},
            },
        ),
    ]
