# Generated by Django 5.2.14 on 2026-05-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionaryentry',
            options={'ordering': ['english'], 'verbose_name': 'Dictionary entry', 'verbose_name_plural': 'Dictionary entries'},
        ),
    ]
