# Generated by Django 5.2.14 on 2026-05-17 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0004_alter_paymentsubmission_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable identifier used by code; never shown to users.', max_length=64, unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_ar', models.CharField(max_length=120)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('price_sdg', models.PositiveIntegerField(default=0, help_text='Monthly price in SDG. 0 means free.')),
                ('currency', models.CharField(default='SDG', max_length=8)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=16)),
                ('ai_tutor_daily_minutes', models.PositiveIntegerField(default=0, help_text='Daily AI-Tutor minute allowance. 0 = AI Tutor blocked.')),
                ('library_audio_daily_minutes', models.PositiveIntegerField(default=0, help_text='Daily natural-reader audio allowance. 0 = blocked.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_free_trial', models.BooleanField(default=False, help_text='If true, this plan is awarded once per user and never renews.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription plan',
                'verbose_name_plural': 'Subscription plans',
                'ordering': ['sort_order', 'ai_tutor_daily_minutes', 'price_sdg'],
            },
        ),
        migrations.CreateModel(
            name='UserDailyQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('ai_tutor_seconds_used', models.PositiveIntegerField(default=0)),
                ('library_seconds_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User daily quota',
                'verbose_name_plural': 'User daily quotas',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_daily_quota')],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.paymentsubmission')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User subscription',
                'verbose_name_plural': 'User subscriptions',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_28ce5e_idx'), models.Index(fields=['end_date'], name='subscriptio_end_dat_d0ae0a_idx')],
            },
        ),
    ]
