# Generated by Django 5.2.14 on 2026-05-18 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_seed_initial_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTrialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_seconds_granted', models.PositiveIntegerField(default=0, help_text='Total trial seconds awarded (typically 5 minutes = 300s).')),
                ('free_seconds_used', models.PositiveIntegerField(default=0)),
                ('is_consumed', models.BooleanField(db_index=True, default=False, help_text='True once the trial bucket is empty.')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='free_trial_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Free trial usage',
                'verbose_name_plural': 'Free trial usages',
            },
        ),
        migrations.CreateModel(
            name='AITutorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('voice_call', 'Voice call'), ('chat', 'Text chat')], default='voice_call', max_length=16)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('killed_quota_exceeded', 'Stopped — quota exceeded')], db_index=True, default='in_progress', max_length=32)),
                ('quota_source', models.CharField(choices=[('subscription', 'Subscription daily quota'), ('free_trial', 'One-shot free trial'), ('none', 'No quota — refused')], default='none', help_text='Where the quota was deducted from at end-of-session.', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('consumed_seconds', models.PositiveIntegerField(default=0)),
                ('remaining_after_seconds', models.PositiveIntegerField(default=0)),
                ('voice', models.CharField(blank=True, max_length=32)),
                ('conversation_id', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tutor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI tutor session',
                'verbose_name_plural': 'AI tutor sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', '-started_at'], name='subscriptio_user_id_b9a1ce_idx'), models.Index(fields=['status'], name='subscriptio_status_597f7d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('user',), name='unique_in_progress_tutor_session_per_user')],
            },
        ),
    ]
