# Generated by Django 5.2.14 on 2026-05-18 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_backfill_trial_for_existing_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_ar', models.CharField(max_length=120)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('neutral', 'Neutral')], default='neutral', max_length=16)),
                ('style', models.CharField(choices=[('casual', 'Casual'), ('professional', 'Professional'), ('energetic', 'Energetic')], default='casual', max_length=24)),
                ('image_url', models.URLField(blank=True)),
                ('lipsync_video_url', models.URLField(blank=True, help_text='Optional looping idle/lipsync video. Sprint 4 wires this.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avatar profile',
                'verbose_name_plural': 'Avatar profiles',
                'ordering': ['sort_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_ar', models.CharField(max_length=120)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('provider_voice_id', models.CharField(help_text="Upstream voice ID (e.g. 'alloy', 'nova') passed to the model.", max_length=64)),
                ('voice_type', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('neutral', 'Neutral')], default='neutral', max_length=16)),
                ('style', models.CharField(choices=[('calm_teacher', 'Calm Teacher'), ('friendly_tutor', 'Friendly Tutor'), ('energetic_coach', 'Energetic Coach'), ('professional', 'Professional Instructor')], default='friendly_tutor', max_length=24)),
                ('accent', models.CharField(choices=[('neutral', 'Neutral English'), ('british', 'British English'), ('american', 'American English'), ('african', 'African English Style'), ('asian', 'Asian English Style'), ('arabic_friendly', 'Arabic-friendly English Tutor')], default='neutral', max_length=24)),
                ('tone', models.CharField(choices=[('normal', 'Normal'), ('calm', 'Calm'), ('energetic', 'Energetic'), ('deep', 'Deep'), ('soft', 'Soft')], default='normal', max_length=16)),
                ('preview_audio_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voice profile',
                'verbose_name_plural': 'Voice profiles',
                'ordering': ['sort_order', 'name_en'],
            },
        ),
        migrations.AddField(
            model_name='aitutorsession',
            name='avatar_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_sessions', to='subscriptions.avatarprofile'),
        ),
        migrations.CreateModel(
            name='UserAIPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.CharField(choices=[('slow', 'Slow'), ('normal', 'Normal'), ('fast', 'Fast')], default='normal', max_length=8)),
                ('pitch', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=8)),
                ('sound_effects_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_preferences', to='subscriptions.avatarprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_preference', to=settings.AUTH_USER_MODEL)),
                ('voice_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_preferences', to='subscriptions.voiceprofile')),
            ],
            options={
                'verbose_name': 'User AI preference',
                'verbose_name_plural': 'User AI preferences',
            },
        ),
        migrations.AddField(
            model_name='aitutorsession',
            name='voice_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_sessions', to='subscriptions.voiceprofile'),
        ),
    ]
