# Generated by Django 5.2.14 on 2026-05-18 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_seed_voices_and_avatars'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextNormalizationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('library_chapter', 'Library chapter'), ('tutor_message', 'Tutor message'), ('ad_hoc', 'Ad hoc')], default='library_chapter', max_length=32)),
                ('source_id', models.PositiveIntegerField(blank=True, help_text='Chapter ID, TutorMessage ID, etc.', null=True)),
                ('language', models.CharField(default='en', max_length=8)),
                ('original_text', models.TextField()),
                ('tts_ready_text', models.TextField()),
                ('applied_rules', models.JSONField(blank=True, default=list)),
                ('original_chars', models.PositiveIntegerField(default=0)),
                ('tts_chars', models.PositiveIntegerField(default=0)),
                ('estimated_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Text normalization log',
                'verbose_name_plural': 'Text normalization logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'source_id', '-created_at'], name='subscriptio_source_e4473b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LibraryAudioSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.PositiveIntegerField(db_index=True)),
                ('chapter_title', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('killed_quota_exceeded', 'Stopped — quota exceeded')], db_index=True, default='in_progress', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('consumed_seconds', models.PositiveIntegerField(default=0)),
                ('remaining_after_seconds', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_audio_sessions', to=settings.AUTH_USER_MODEL)),
                ('voice_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_audio_sessions', to='subscriptions.voiceprofile')),
            ],
            options={
                'verbose_name': 'Library audio session',
                'verbose_name_plural': 'Library audio sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', '-started_at'], name='subscriptio_user_id_97973c_idx'), models.Index(fields=['status'], name='subscriptio_status_09e296_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('user',), name='unique_in_progress_library_audio_per_user')],
            },
        ),
    ]
