# Generated by Django 5.2.14 on 2026-05-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_textnormalizationlog_libraryaudiosession'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatarprofile',
            name='image_file',
            field=models.ImageField(blank=True, help_text="Upload a square photo of the avatar's face — used by the voice-call screen.", null=True, upload_to='avatars/%Y/%m/'),
        ),
    ]
