# Generated by Django 5.2.14 on 2026-05-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_add_hassabu_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Highlight this plan as 'most popular' on the public pricing page."),
        ),
    ]
