# Generated by Django 5.2.14 on 2026-06-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_subscriptionplan_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitutorsession',
            name='source',
            field=models.CharField(choices=[('voice_call', 'Voice call'), ('chat', 'Text chat'), ('placement_voice', 'Placement speaking')], default='voice_call', max_length=16),
        ),
    ]
