# Generated by Django 5.2.14 on 2026-06-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_alter_aitutorsession_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='ai_tutor_session_cap_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Per-session AI-Tutor cap in minutes. 0 = fall back to the global AI_REALTIME_MAX_SESSION_SECONDS setting.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='course_access_enabled',
            field=models.BooleanField(default=True, help_text='Whether an active subscription on this plan unlocks paid courses.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='daily_quiz_enabled',
            field=models.BooleanField(default=True, help_text='Whether this plan unlocks the Daily Quiz.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='library_session_cap_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Per-session Library reading/listening cap in minutes. 0 = fall back to the global LIBRARY_MAX_SESSION_SECONDS setting. Wired in 19.0.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='placement_enabled',
            field=models.BooleanField(default=True, help_text='Whether this plan unlocks the placement test.'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='ai_tutor_daily_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Daily AI-Tutor minute allowance / daily cap. 0 = AI Tutor blocked.'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='library_audio_daily_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Daily natural-reader audio allowance / daily cap. 0 = blocked.'),
        ),
    ]
