# Generated by Django 5.2.14 on 2026-05-11 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLearningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('cefr_level', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], max_length=2)),
                ('plan_type', models.CharField(choices=[('beginner_start', 'Beginner start (A0)'), ('placement_based', 'Placement-based'), ('weakness_review', 'Weakness review'), ('streak_recovery', 'Streak recovery (comeback)'), ('exam_preparation', 'Exam preparation'), ('normal_daily_plan', 'Normal daily plan')], default='normal_daily_plan', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily learning plan',
                'verbose_name_plural': 'Daily learning plans',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyLearningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar_tip', 'Grammar tip'), ('reading', 'Reading'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('writing', 'Writing'), ('quiz', 'Quiz'), ('review_mistake', 'Review mistake'), ('ai_tutor_practice', 'AI tutor practice'), ('motivation', 'Motivation')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('content_text', models.TextField(blank=True)),
                ('question', models.TextField(blank=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('cefr_level', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], max_length=2)),
                ('skill', models.CharField(blank=True, choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('reading', 'Reading'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('writing', 'Writing'), ('pronunciation', 'Pronunciation'), ('mixed', 'Mixed')], max_length=20)),
                ('difficulty_score', models.FloatField(default=0.3)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=2)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='daily_learning.dailylearningplan')),
            ],
            options={
                'verbose_name': 'Daily learning item',
                'verbose_name_plural': 'Daily learning items',
                'ordering': ['daily_plan', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DailyLearningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_items_count', models.PositiveIntegerField(default=0)),
                ('total_items_count', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('streak_updated', models.BooleanField(default=False)),
                ('weaknesses_improved', models.JSONField(blank=True, default=list)),
                ('mistakes_reviewed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='daily_learning.dailylearningplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily learning result',
                'verbose_name_plural': 'Daily learning results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('goal_type', models.CharField(choices=[('complete_lesson', 'Complete a lesson'), ('answer_questions', 'Answer N questions'), ('speaking_minutes', 'Speak N minutes'), ('reading_words', 'Read N words'), ('review_mistakes', 'Review N mistakes'), ('maintain_streak', 'Maintain streak')], max_length=20)),
                ('target_value', models.PositiveIntegerField(default=1)),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('reward_xp', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily goal',
                'verbose_name_plural': 'Daily goals',
                'ordering': ['-date', 'goal_type'],
                'indexes': [models.Index(fields=['user', '-date'], name='daily_learn_user_id_1407f8_idx'), models.Index(fields=['completed'], name='daily_learn_complet_eb7e85_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date', 'goal_type'), name='daily_learning_unique_user_date_goal')],
            },
        ),
        migrations.AddIndex(
            model_name='dailylearningplan',
            index=models.Index(fields=['user', '-date'], name='daily_learn_user_id_e16381_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylearningplan',
            index=models.Index(fields=['status'], name='daily_learn_status_ff54e5_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylearningplan',
            index=models.Index(fields=['plan_type'], name='daily_learn_plan_ty_946bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylearningplan',
            index=models.Index(fields=['cefr_level'], name='daily_learn_cefr_le_950e48_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailylearningplan',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='daily_learning_unique_user_date_plan'),
        ),
        migrations.AddIndex(
            model_name='dailylearningitem',
            index=models.Index(fields=['daily_plan', 'order'], name='daily_learn_daily_p_477aa2_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylearningitem',
            index=models.Index(fields=['item_type'], name='daily_learn_item_ty_8dab8a_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylearningitem',
            index=models.Index(fields=['is_completed'], name='daily_learn_is_comp_07c66a_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylearningresult',
            index=models.Index(fields=['user', '-created_at'], name='daily_learn_user_id_876b53_idx'),
        ),
    ]
