# Generated by Django 5.2.14 on 2026-05-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylearningitem',
            name='audio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='dailylearningitem',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailylearningitem',
            name='item_type',
            field=models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar_tip', 'Grammar tip'), ('reading', 'Reading'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('writing', 'Writing'), ('quiz', 'Quiz'), ('word_order', 'Word order'), ('review_mistake', 'Review mistake'), ('ai_tutor_practice', 'AI tutor practice'), ('motivation', 'Motivation')], max_length=20),
        ),
    ]
