# Generated by Django 5.2.14 on 2026-05-08 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AITrainingExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('error_analysis', 'Error analysis'), ('cefr_prediction', 'CEFR prediction'), ('exercise_generation', 'Exercise generation'), ('answer_explanation', 'Answer explanation'), ('tutor_reply', 'Tutor reply')], max_length=24)),
                ('input', models.JSONField(default=dict)),
                ('output', models.JSONField(default=dict)),
                ('source_type', models.CharField(blank=True, help_text="e.g. 'AdaptiveExercise', 'UserError', 'TutorMessage'.", max_length=40)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('cefr_level', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3 (Advanced communication)')], max_length=2)),
                ('skill', models.CharField(blank=True, max_length=20)),
                ('quality_score', models.PositiveSmallIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=2)),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-1 of (task_type + input + output) — used for dedup.', max_length=40)),
                ('split', models.CharField(blank=True, choices=[('train', 'Train'), ('validation', 'Validation'), ('test', 'Test')], help_text='Deterministic train/val/test bucket (set by exporter).', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_type', 'split'], name='ai_training_task_ty_bef6e0_idx'), models.Index(fields=['task_type', 'is_approved'], name='ai_training_task_ty_b4c2c2_idx'), models.Index(fields=['cefr_level', 'skill'], name='ai_training_cefr_le_b4fae9_idx'), models.Index(fields=['quality_score'], name='ai_training_quality_ebf856_idx')],
                'constraints': [models.UniqueConstraint(fields=('task_type', 'content_hash'), name='aitex_unique_task_hash')],
            },
        ),
        migrations.CreateModel(
            name='DatasetBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('task_type', models.CharField(choices=[('error_analysis', 'Error analysis'), ('cefr_prediction', 'CEFR prediction'), ('exercise_generation', 'Exercise generation'), ('answer_explanation', 'Answer explanation'), ('tutor_reply', 'Tutor reply')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('example_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('private_data_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task_type', '-started_at'], name='ai_training_task_ty_ca8a34_idx'), models.Index(fields=['status'], name='ai_training_status_145a1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DatasetQualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_examples', models.PositiveIntegerField(default=0)),
                ('avg_quality_score', models.FloatField(default=0.0)),
                ('distribution_by_cefr', models.JSONField(blank=True, default=dict)),
                ('distribution_by_skill', models.JSONField(blank=True, default=dict)),
                ('distribution_by_task_type', models.JSONField(blank=True, default=dict)),
                ('duplicates_removed', models.PositiveIntegerField(default=0)),
                ('private_data_filtered', models.PositiveIntegerField(default=0)),
                ('low_quality_filtered', models.PositiveIntegerField(default=0)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_report', to='ai_training.datasetbuild')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('jsonl', 'JSON Lines'), ('csv', 'CSV')], default='jsonl', max_length=8)),
                ('split', models.CharField(default='all', help_text="One of 'train' / 'validation' / 'test' / 'all'.", max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('bytes_written', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='ai_training.datasetbuild')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['build', '-started_at'], name='ai_training_build_i_8d5f63_idx'), models.Index(fields=['status'], name='ai_training_status_61a4ef_idx')],
            },
        ),
    ]
