# Generated by Django 5.2.14 on 2026-05-08 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('task_type', models.CharField(choices=[('error_analysis', 'Error analysis'), ('cefr_prediction', 'CEFR prediction'), ('exercise_generation', 'Exercise generation'), ('answer_explanation', 'Answer explanation'), ('tutor_reply', 'Tutor reply')], max_length=24)),
                ('provider', models.CharField(blank=True, help_text="Provider tested (e.g. 'rules', 'local_llm', 'openai').", max_length=20)),
                ('model_version', models.CharField(blank=True, max_length=80)),
                ('total_examples', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('incorrect_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('mean_absolute_error', models.FloatField(blank=True, help_text='Filled for regression tasks (e.g. difficulty_estimation).', null=True)),
                ('avg_latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='ai_training.datasetbuild')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task_type', '-started_at'], name='ai_training_task_ty_9a7ece_idx'), models.Index(fields=['build', '-started_at'], name='ai_training_build_i_8262cb_idx'), models.Index(fields=['provider'], name='ai_training_provide_1725cb_idx'), models.Index(fields=['status'], name='ai_training_status_d8e6e0_idx')],
            },
        ),
    ]
