# Generated by Django 5.2.14 on 2026-05-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_training', '0002_evaluationrun'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aitrainingexample',
            options={'ordering': ['-created_at'], 'verbose_name': 'Aitraining example', 'verbose_name_plural': 'Aitraining examples'},
        ),
        migrations.AlterModelOptions(
            name='datasetbuild',
            options={'ordering': ['-started_at'], 'verbose_name': 'Dataset build', 'verbose_name_plural': 'Dataset builds'},
        ),
        migrations.AlterModelOptions(
            name='datasetexport',
            options={'ordering': ['-started_at'], 'verbose_name': 'Dataset export', 'verbose_name_plural': 'Dataset exports'},
        ),
        migrations.AlterModelOptions(
            name='datasetqualityreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dataset quality report', 'verbose_name_plural': 'Dataset quality reports'},
        ),
        migrations.AlterModelOptions(
            name='evaluationrun',
            options={'ordering': ['-started_at'], 'verbose_name': 'Evaluation run', 'verbose_name_plural': 'Evaluation runs'},
        ),
    ]
