# Generated by Django 5.2.14 on 2026-05-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_clubevent_level_max_alter_clubevent_level_min'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubevent',
            options={'ordering': ['starts_at'], 'verbose_name': 'Club event', 'verbose_name_plural': 'Club events'},
        ),
        migrations.AlterModelOptions(
            name='clubrsvp',
            options={'ordering': ['-created_at'], 'verbose_name': 'Club rsvp', 'verbose_name_plural': 'Club rsvps'},
        ),
    ]
