# Generated by Django 5.2.14 on 2026-05-18 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_clubevent_options_alter_clubrsvp_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrsvp',
            name='attendance_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubrsvp',
            name='attendance_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_attendance_marks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClubFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=3, help_text="1-5 quick rating of student's participation.")),
                ('feedback_en', models.TextField(blank=True)),
                ('feedback_ar', models.TextField(blank=True)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('is_visible_to_student', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_feedback_written', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='club.clubevent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_feedback_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Club feedback',
                'verbose_name_plural': 'Club feedback entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='club_clubfe_student_c44f5b_idx')],
                'unique_together': {('event', 'student')},
            },
        ),
    ]
