# Generated by Django 5.2.14 on 2026-05-07 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user_registered', 'user_registered'), ('email_verification', 'email_verification'), ('password_reset', 'password_reset'), ('placement_completed', 'placement_completed'), ('weakness_detected', 'weakness_detected'), ('exercises_generated', 'exercises_generated'), ('lesson_completed', 'lesson_completed'), ('weekly_assessment_available', 'weekly_assessment_available'), ('weekly_assessment_result', 'weekly_assessment_result'), ('level_improved', 'level_improved'), ('subscription_expiring', 'subscription_expiring'), ('payment_submitted', 'payment_submitted'), ('payment_approved', 'payment_approved'), ('payment_rejected', 'payment_rejected'), ('inactive_student_reminder', 'inactive_student_reminder'), ('new_student_registered', 'new_student_registered'), ('new_payment_pending', 'new_payment_pending'), ('ai_usage_high', 'ai_usage_high'), ('ai_failure', 'ai_failure'), ('at_risk_student', 'at_risk_student'), ('daily_admin_summary', 'daily_admin_summary'), ('weekly_admin_summary', 'weekly_admin_summary')], max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=15)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The user who caused the event (e.g. an admin approving a payment).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events_actor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='The student/admin the event is about. Null for system events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=120)),
                ('subject', models.CharField(max_length=255)),
                ('template_name', models.CharField(max_length=120)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('attempts_count', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notifications', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='notifications.notificationevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_updates', models.BooleanField(default=True)),
                ('payment_updates', models.BooleanField(default=True)),
                ('weekly_summary', models.BooleanField(default=True)),
                ('admin_alerts', models.BooleanField(default=True, help_text='Only honored for staff/admin recipients.')),
                ('marketing_emails', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user_registered', 'user_registered'), ('email_verification', 'email_verification'), ('password_reset', 'password_reset'), ('placement_completed', 'placement_completed'), ('weakness_detected', 'weakness_detected'), ('exercises_generated', 'exercises_generated'), ('lesson_completed', 'lesson_completed'), ('weekly_assessment_available', 'weekly_assessment_available'), ('weekly_assessment_result', 'weekly_assessment_result'), ('level_improved', 'level_improved'), ('subscription_expiring', 'subscription_expiring'), ('payment_submitted', 'payment_submitted'), ('payment_approved', 'payment_approved'), ('payment_rejected', 'payment_rejected'), ('inactive_student_reminder', 'inactive_student_reminder'), ('new_student_registered', 'new_student_registered'), ('new_payment_pending', 'new_payment_pending'), ('ai_usage_high', 'ai_usage_high'), ('ai_failure', 'ai_failure'), ('at_risk_student', 'at_risk_student'), ('daily_admin_summary', 'daily_admin_summary'), ('weekly_admin_summary', 'weekly_admin_summary')], max_length=64)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2)),
                ('subject', models.CharField(max_length=255)),
                ('template_name', models.CharField(help_text='Path under templates/notifications/emails/ — e.g. welcome.html', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event_type', 'language'), name='unique_template_per_event_language')],
            },
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['event_type', '-created_at'], name='notificatio_event_t_d4510d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['status'], name='notificatio_status_3ddfba_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['user', 'event_type'], name='notificatio_user_id_37a27a_idx'),
        ),
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['status', '-created_at'], name='notificatio_status_46b49c_idx'),
        ),
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['recipient_email'], name='notificatio_recipie_0939b1_idx'),
        ),
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['template_name'], name='notificatio_templat_f08080_idx'),
        ),
    ]
