# Generated by Django 5.2.14 on 2026-05-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificationevent_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='ar', max_length=2),
        ),
    ]
