# Generated by Django 5.2.14 on 2026-05-08 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notificationpreference_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email notification', 'verbose_name_plural': 'Email notifications'},
        ),
        migrations.AlterModelOptions(
            name='emailverificationtoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email verification token', 'verbose_name_plural': 'Email verification tokens'},
        ),
        migrations.AlterModelOptions(
            name='notificationevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification event', 'verbose_name_plural': 'Notification events'},
        ),
        migrations.AlterModelOptions(
            name='notificationpreference',
            options={'verbose_name': 'Notification preference', 'verbose_name_plural': 'Notification preferences'},
        ),
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'verbose_name': 'Notification template', 'verbose_name_plural': 'Notification templates'},
        ),
    ]
