# Generated by Django 5.2.14 on 2026-05-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_emailnotification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationevent',
            name='event_type',
            field=models.CharField(choices=[('user_registered', 'user_registered'), ('email_verification', 'email_verification'), ('password_reset', 'password_reset'), ('placement_completed', 'placement_completed'), ('weakness_detected', 'weakness_detected'), ('exercises_generated', 'exercises_generated'), ('lesson_completed', 'lesson_completed'), ('weekly_assessment_available', 'weekly_assessment_available'), ('weekly_assessment_result', 'weekly_assessment_result'), ('level_improved', 'level_improved'), ('subscription_expiring', 'subscription_expiring'), ('payment_submitted', 'payment_submitted'), ('payment_approved', 'payment_approved'), ('payment_rejected', 'payment_rejected'), ('inactive_student_reminder', 'inactive_student_reminder'), ('daily_plan_ready', 'daily_plan_ready'), ('daily_plan_comeback', 'daily_plan_comeback'), ('daily_plan_streak_reminder', 'daily_plan_streak_reminder'), ('new_student_registered', 'new_student_registered'), ('new_payment_pending', 'new_payment_pending'), ('ai_usage_high', 'ai_usage_high'), ('ai_failure', 'ai_failure'), ('at_risk_student', 'at_risk_student'), ('daily_admin_summary', 'daily_admin_summary'), ('weekly_admin_summary', 'weekly_admin_summary'), ('motivation_message_generated', 'motivation_message_generated'), ('achievement_unlocked', 'achievement_unlocked'), ('badge_earned', 'badge_earned'), ('xp_awarded', 'xp_awarded'), ('streak_milestone', 'streak_milestone'), ('comeback_reminder', 'comeback_reminder'), ('weekly_motivation_summary', 'weekly_motivation_summary')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('user_registered', 'user_registered'), ('email_verification', 'email_verification'), ('password_reset', 'password_reset'), ('placement_completed', 'placement_completed'), ('weakness_detected', 'weakness_detected'), ('exercises_generated', 'exercises_generated'), ('lesson_completed', 'lesson_completed'), ('weekly_assessment_available', 'weekly_assessment_available'), ('weekly_assessment_result', 'weekly_assessment_result'), ('level_improved', 'level_improved'), ('subscription_expiring', 'subscription_expiring'), ('payment_submitted', 'payment_submitted'), ('payment_approved', 'payment_approved'), ('payment_rejected', 'payment_rejected'), ('inactive_student_reminder', 'inactive_student_reminder'), ('daily_plan_ready', 'daily_plan_ready'), ('daily_plan_comeback', 'daily_plan_comeback'), ('daily_plan_streak_reminder', 'daily_plan_streak_reminder'), ('new_student_registered', 'new_student_registered'), ('new_payment_pending', 'new_payment_pending'), ('ai_usage_high', 'ai_usage_high'), ('ai_failure', 'ai_failure'), ('at_risk_student', 'at_risk_student'), ('daily_admin_summary', 'daily_admin_summary'), ('weekly_admin_summary', 'weekly_admin_summary'), ('motivation_message_generated', 'motivation_message_generated'), ('achievement_unlocked', 'achievement_unlocked'), ('badge_earned', 'badge_earned'), ('xp_awarded', 'xp_awarded'), ('streak_milestone', 'streak_milestone'), ('comeback_reminder', 'comeback_reminder'), ('weekly_motivation_summary', 'weekly_motivation_summary')], max_length=64),
        ),
    ]
