"""CEFR-aligned descriptors for the 5 levels above A0 (the A0 pack is in
`onlenco_beginner_seed_data.py` and was hand-crafted).

Each LEVEL dict carries:
  - code              CEFR level (A1, A2, B1, B2, C1, C2)
  - course_slug       URL-safe slug for the Course row
  - course_title_en/ar  Course display titles
  - course_desc_en/ar   Course descriptions
  - clusters[]        6 thematic clusters per level (matches A0 shape)
  - topics[]          48 topic descriptors:
        {n, title_en, title_ar, cluster, new_language_en, new_language_ar,
         grammar_en, grammar_ar, vocab_en, vocab_ar, skill_en, skill_ar,
         example_pattern, lesson_type, minutes}

The 48-topic order is informed by published CEFR can-do statements
(Cambridge English, CEFR Companion Volume 2018). Specific topics and
phrasings are original to Onlenco — no copy from any single publication.

The unit generator (`onlenco_level_unit_builder.build_unit_dict`) takes
one topic descriptor + the level code and returns a unit dict in the
exact shape expected by the existing seed command.
"""
from __future__ import annotations


# ---------------------------------------------------------------------------
# Level metadata
# ---------------------------------------------------------------------------

LEVELS: list[dict] = [
    # =====================================================================
    # A1 — Elementary
    # Coverage: past simple, present continuous, going-to future,
    # comparatives, basic modals, asking for things politely.
    # =====================================================================
    {
        "code": "A1",
        "course_slug": "onlenco-elementary",
        "course_title_en": "Onlenco Elementary English (A1)",
        "course_title_ar": "Onlenco — الإنجليزية الأساسية (A1)",
        "course_desc_en": (
            "A 48-unit Elementary course bridging Beginner to A2. Past, "
            "continuous, going-to future, comparatives, basic modals. "
            "American English."
        ),
        "course_desc_ar": (
            "كورس من 48 وحدة لمستوى A1 الأساسي يربط بين المبتدئ و A2. "
            "الماضي البسيط، المضارع المستمر، going-to، صيغ المقارنة، "
            "الأفعال الناقصة الأساسية. إنجليزية أمريكية."
        ),
        "clusters": [
            "Past — what happened",
            "Continuous — what's happening now",
            "Future — what will happen",
            "Comparisons — better, worse, the best",
            "Modals — can, should, must",
            "Functions — asking, ordering, suggesting",
        ],
        "topics": [
            # Cluster 1 — Past simple
            ("Past simple — to be (was, were)", "الماضي البسيط لـ to be", 1,
             "was / were", "كان / كانت — was مفرد، were جمع",
             "I was at home yesterday.", "skill", 25),
            ("Yesterday vocabulary", "مفردات الأمس", 1,
             "—", "—", "—", "vocabulary", 15),
            ("Regular past verbs (-ed)", "الأفعال المنتظمة في الماضي", 1,
             "verb + -ed", "الفعل + -ed للماضي المنتظم",
             "I worked yesterday.", "grammar", 25),
            ("Irregular past verbs (set 1)", "الأفعال غير المنتظمة 1", 1,
             "went, came, ate, saw, took", "ذهب، أتى، أكل، رأى، أخذ",
             "She went to the market.", "grammar", 25),
            ("Past questions", "أسئلة الماضي", 1,
             "Did you …?", "هل فعلتَ …؟",
             "Did you eat dinner?", "grammar", 22),
            ("Past negatives", "نفي الماضي", 1,
             "didn't + base", "لم أفعل = didn't + الفعل الأساسي",
             "I didn't see him.", "grammar", 22),
            ("Time expressions for past", "تعبيرات الزمن الماضية", 1,
             "yesterday, last week, two days ago",
             "أمس، الأسبوع الماضي، قبل يومين",
             "I called you last night.", "grammar", 20),
            ("Telling a short story", "حكاية قصيرة", 1,
             "First … then … finally …", "أولاً … ثم … أخيراً …",
             "First I woke up, then I had breakfast.", "speaking", 30),

            # Cluster 2 — Present continuous
            ("Body and feelings", "الجسم والمشاعر", 2,
             "—", "—", "—", "vocabulary", 15),
            ("Present continuous — what's happening now", "المضارع المستمر — ما يحدث الآن", 2,
             "be + verb-ing", "كان + فعل-ing",
             "I am studying English.", "grammar", 25),
            ("Now vs every day", "الآن مقابل كل يوم", 2,
             "present continuous vs present simple", "المستمر مقابل البسيط",
             "I usually walk, but now I'm running.", "grammar", 25),
            ("Spelling rules for -ing", "قواعد إضافة -ing", 2,
             "drop silent e, double consonants",
             "احذف e الصامتة، ضاعف الحرف الساكن",
             "make → making, run → running", "grammar", 20),
            ("Picture description", "وصف الصور", 2,
             "There is a man who is …", "هناك رجل يقوم بـ …",
             "A boy is reading a book.", "speaking", 25),
            ("Health and the doctor", "الصحة وعند الطبيب", 2,
             "—", "—", "—", "vocabulary", 15),
            ("How are you feeling?", "كيف تشعر؟", 2,
             "I'm feeling …", "أشعر بـ …",
             "I'm not feeling well today.", "speaking", 22),

            # Cluster 3 — Future
            ("Going-to future", "going-to للمستقبل", 3,
             "be going to + verb", "be going to + فعل = نية مستقبلية",
             "I'm going to visit my family.", "grammar", 28),
            ("Travel vocabulary", "مفردات السفر", 3,
             "—", "—", "—", "vocabulary", 18),
            ("Plans for the weekend", "خطط نهاية الأسبوع", 3,
             "going to + activity", "going to + النشاط",
             "We're going to go shopping.", "speaking", 25),
            ("Future questions", "أسئلة المستقبل", 3,
             "Are you going to …?", "هل ستفعل …؟",
             "Are you going to come?", "grammar", 22),
            ("Predictions with will", "التنبؤات بـ will", 3,
             "will + base verb", "will + الفعل الأساسي = تنبؤ",
             "It will rain tomorrow.", "grammar", 25),
            ("Promises and offers", "الوعود والعروض", 3,
             "I'll help you.", "سأساعدك = I'll help you",
             "I'll carry that bag for you.", "speaking", 22),
            ("Weather and forecasts", "الطقس والتوقعات", 3,
             "—", "—", "—", "vocabulary", 15),

            # Cluster 4 — Comparatives
            ("Comparative adjectives", "صفات المقارنة", 4,
             "-er than / more X than", "أفضل من — er than أو more than",
             "Today is hotter than yesterday.", "grammar", 28),
            ("Superlative adjectives", "صفات التفضيل", 4,
             "the -est / the most X", "الأفضل — the -est أو the most",
             "It's the biggest city in Sudan.", "grammar", 28),
            ("Better / worse / best / worst", "أفضل / أسوأ", 4,
             "irregular: good→better→best, bad→worse→worst",
             "غير منتظم: جيد → أفضل، سيء → أسوأ",
             "This is the best café in town.", "grammar", 22),
            ("Shopping and prices", "التسوق والأسعار", 4,
             "—", "—", "—", "vocabulary", 18),
            ("As … as comparisons", "as ... as للمقارنة", 4,
             "as adjective as", "as صفة as = بقدر",
             "She is as tall as her brother.", "grammar", 22),
            ("Talking about places", "وصف الأماكن مقارنة", 4,
             "X is better than Y because …", "X أفضل من Y لأن …",
             "Khartoum is bigger than my town.", "speaking", 25),

            # Cluster 5 — Modals
            ("Asking for things politely", "الطلب بأدب", 5,
             "Could you …? May I …?", "هل يمكنك …؟ هل لي بـ …؟",
             "Could you help me, please?", "speaking", 25),
            ("Should and shouldn't", "should / shouldn't للنصيحة", 5,
             "should + base verb", "should + الفعل = نصيحة",
             "You should drink more water.", "grammar", 25),
            ("Must / have to", "must / have to للإلزام", 5,
             "must = personal must, have to = external must",
             "must = إلزام شخصي، have to = إلزام خارجي",
             "I must call my mother.", "grammar", 25),
            ("Can for permission", "can للإذن", 5,
             "Can I …?", "هل أستطيع …؟",
             "Can I open the window?", "grammar", 22),
            ("Money and the bank", "المال والبنك", 5,
             "—", "—", "—", "vocabulary", 18),
            ("Rules and signs", "القواعد واللافتات", 5,
             "You can't / You must", "ممنوع / يجب",
             "You can't smoke here.", "grammar", 22),

            # Cluster 6 — Functions
            ("Ordering food", "طلب الطعام", 6,
             "I'll have …, Could I have …", "سأطلب …، هل لي بـ …",
             "I'll have a coffee, please.", "speaking", 25),
            ("At the restaurant", "في المطعم", 6,
             "—", "—", "—", "vocabulary", 15),
            ("Making suggestions", "تقديم الاقتراحات", 6,
             "Let's …, How about …?, Why don't we …?",
             "هيا … ، ماذا عن … ؟ ، لِمَ لا …؟",
             "Let's go to the park.", "speaking", 25),
            ("Inviting and replying", "الدعوة والرد", 6,
             "Would you like to …?", "هل تودّ …؟",
             "Would you like to come?", "speaking", 22),
            ("Apologizing", "الاعتذار", 6,
             "I'm sorry, I apologize", "أنا آسف، أعتذر",
             "I'm sorry I'm late.", "speaking", 20),
            ("Phone calls", "المكالمات الهاتفية", 6,
             "Hello, this is … speaking", "مرحباً، أنا … أتحدث",
             "Hello, this is Amani speaking.", "speaking", 25),
            ("Email basics", "أساسيات البريد الإلكتروني", 6,
             "Dear …, Best regards", "عزيزي …، مع التحية",
             "Dear teacher, …", "writing", 25),
            ("Writing about yourself", "الكتابة عن نفسك", 6,
             "introductory paragraph", "فقرة تعريفية",
             "My name is Amani. I am from Sudan.", "writing", 30),
            ("Travel and transport", "السفر والمواصلات", 6,
             "—", "—", "—", "vocabulary", 15),
            ("At the airport", "في المطار", 6,
             "boarding pass, gate, luggage",
             "بطاقة الصعود، البوابة، الأمتعة",
             "Where is the gate, please?", "speaking", 22),
            ("Free time activities", "أنشطة وقت الفراغ", 6,
             "—", "—", "—", "vocabulary", 15),
            ("Talking about hobbies in depth", "الحديث عن الهوايات بعمق", 6,
             "I've been doing X for Y years.", "أمارس X منذ Y سنة",
             "I've played football for 5 years.", "speaking", 25),
            # +2 gap-fill (to reach 48)
            ("Storytelling with past tense", "السرد بصيغة الماضي", 1,
             "Yesterday I + past verb …", "أمس + فعل ماضٍ …",
             "Yesterday I visited my aunt.", "speaking", 25),
            ("Word stress patterns (A1)", "أنماط النبرة (A1)", 6,
             "stress on content words, not function words",
             "النبرة على الكلمات الدلالية لا الوظيفية",
             "I WENT to the BANK yesterday.", "speaking", 18),
        ],
    },

    # =====================================================================
    # A2 — Pre-Intermediate
    # =====================================================================
    {
        "code": "A2",
        "course_slug": "onlenco-pre-intermediate",
        "course_title_en": "Onlenco Pre-Intermediate English (A2)",
        "course_title_ar": "Onlenco — الإنجليزية ما قبل المتوسط (A2)",
        "course_desc_en": (
            "A 48-unit Pre-Intermediate course. Past continuous, present "
            "perfect, first conditional, quantifiers, life-event topics. "
            "American English."
        ),
        "course_desc_ar": (
            "كورس من 48 وحدة لمستوى A2 ما قبل المتوسط. الماضي المستمر، "
            "المضارع التام، الشرطي الأول، أدوات الكمّ، أحداث الحياة. "
            "إنجليزية أمريكية."
        ),
        "clusters": [
            "Past continuous & narrative",
            "Present perfect — experience",
            "First conditional & probability",
            "Quantifiers and measurement",
            "Life events & milestones",
            "Communication & opinion",
        ],
        "topics": [
            ("Past continuous", "الماضي المستمر", 1,
             "was/were + verb-ing", "كان + فعل-ing",
             "I was watching TV at 8 pm.", "grammar", 28),
            ("Stories with past tenses", "حكايات بصيغة الماضي", 1,
             "while + past continuous, when + past simple",
             "while + ماضي مستمر، when + ماضي بسيط",
             "While I was cooking, the phone rang.", "speaking", 30),
            ("Crime and the news", "الجريمة والأخبار", 1,
             "—", "—", "—", "vocabulary", 18),
            ("Past time markers", "تعبيرات الزمن الماضي", 1,
             "while, when, as soon as", "بينما، عندما، حالما",
             "When I arrived, she was sleeping.", "grammar", 25),
            ("Narrative practice", "تدريب على السرد", 1,
             "first / then / suddenly / in the end",
             "أولاً / ثم / فجأة / في النهاية",
             "Suddenly, the lights went out.", "speaking", 30),
            ("Describing a memory", "وصف ذكرى", 1,
             "I remember when …", "أتذكر عندما …",
             "I remember when I started school.", "speaking", 25),
            ("Childhood and family", "الطفولة والعائلة", 1,
             "—", "—", "—", "vocabulary", 15),
            ("Used to for past habits", "used to للعادات الماضية", 1,
             "used to + base verb", "used to + الفعل = عادة سابقة",
             "I used to play football every day.", "grammar", 25),

            ("Present perfect intro", "مقدمة المضارع التام", 2,
             "have/has + past participle", "have/has + التصريف الثالث",
             "I have visited Cairo.", "grammar", 30),
            ("Ever / never with present perfect", "ever / never مع المضارع التام", 2,
             "Have you ever …? I've never …",
             "هل سبق أن …؟ لم يسبق لي …",
             "Have you ever tried sushi?", "grammar", 25),
            ("Just / already / yet", "just / already / yet", 2,
             "just = للتو، already = بالفعل، yet = بعدُ",
             "للتو / بالفعل / بعدُ",
             "I've just finished my homework.", "grammar", 25),
            ("Life experiences", "تجارب الحياة", 2,
             "I have / I haven't … yet", "لقد … / لم أ… بعد",
             "I have traveled to Egypt twice.", "speaking", 28),
            ("Travel destinations", "وجهات السفر", 2,
             "—", "—", "—", "vocabulary", 15),
            ("For and since", "for مقابل since", 2,
             "for = duration, since = start time",
             "for = للمدة، since = من نقطة زمنية",
             "I've lived here since 2020.", "grammar", 22),
            ("Bucket list talk", "قائمة الأمنيات", 2,
             "I want to … before I …", "أريد أن … قبل أن …",
             "I want to learn Spanish before I'm 30.", "speaking", 25),
            ("Food cultures", "ثقافات الطعام", 2,
             "—", "—", "—", "vocabulary", 18),

            ("First conditional", "الشرطي الأول", 3,
             "If + present, will + base", "إذا + مضارع، will + الفعل",
             "If it rains, I will stay home.", "grammar", 28),
            ("Plans depending on weather", "خطط تعتمد على الطس", 3,
             "If … then …", "إذا … فإن …",
             "If it's sunny, we'll go to the beach.", "speaking", 25),
            ("Probability adverbs", "ظروف الاحتمال", 3,
             "probably, maybe, definitely",
             "غالباً، ربما، بالتأكيد",
             "I'll probably be there by 7.", "grammar", 22),
            ("Time clauses with future", "جمل الزمن مع المستقبل", 3,
             "when / as soon as + present, will",
             "عندما / حالما + مضارع، will",
             "I'll call you when I arrive.", "grammar", 25),
            ("Making promises", "تقديم الوعود", 3,
             "I promise I'll …", "أعدك أنني سوف …",
             "I promise I'll be on time.", "speaking", 22),
            ("Plans and arrangements", "الخطط والترتيبات", 3,
             "present continuous for future", "المضارع المستمر للمستقبل",
             "I'm meeting Layla tomorrow.", "grammar", 25),
            ("Calendar and scheduling", "التقويم والمواعيد", 3,
             "—", "—", "—", "vocabulary", 15),

            ("Countable and uncountable revisited", "المعدود وغير المعدود معمَّق", 4,
             "few / a few / little / a little",
             "قليل (سلبي) / قليل (إيجابي) / قليل غ.م.",
             "I have a few friends here.", "grammar", 25),
            ("Some / any / no", "some / any / no", 4,
             "positive / question / negative + countable choice",
             "في النفي والسؤال والإثبات",
             "I don't have any sugar.", "grammar", 22),
            ("Much / many / a lot of", "much / many / a lot of", 4,
             "many = countable, much = uncountable",
             "many = معدود، much = غ.معدود",
             "How much sugar do you take?", "grammar", 22),
            ("Cooking and recipes", "الطبخ والوصفات", 4,
             "—", "—", "—", "vocabulary", 15),
            ("Containers and quantities", "العبوات والكميات", 4,
             "a bottle of, a jar of, a slice of",
             "زجاجة من، علبة من، شريحة من",
             "I need a bottle of olive oil.", "grammar", 22),
            ("Shopping list", "قائمة المشتريات", 4,
             "—", "—", "—", "vocabulary", 15),

            ("Major life events", "أحداث الحياة الكبرى", 5,
             "—", "—", "—", "vocabulary", 18),
            ("Talking about marriage", "الحديث عن الزواج", 5,
             "got married, got engaged", "تزوّج، خطب",
             "She got married last June.", "speaking", 25),
            ("Career milestones", "محطات المسار المهني", 5,
             "got a job, was promoted", "حصل على عمل، تمت ترقيته",
             "He was promoted to manager.", "speaking", 25),
            ("Education path", "المسار التعليمي", 5,
             "graduated from, studied at", "تخرّج من، درس في",
             "I graduated from university in 2024.", "speaking", 25),
            ("Big decisions", "القرارات المصيرية", 5,
             "decided to, chose to", "قرّر أن، اختار أن",
             "He decided to move to Toronto.", "speaking", 22),
            ("Talking about change", "التحدث عن التغيير", 5,
             "I used to … but now …", "كنت … لكنني الآن …",
             "I used to smoke but now I don't.", "speaking", 25),

            ("Stating an opinion", "إبداء الرأي", 6,
             "I think, I believe, in my opinion",
             "أعتقد، أؤمن، في رأيي",
             "I think English is fun.", "speaking", 22),
            ("Agreeing and disagreeing", "الاتفاق والاختلاف", 6,
             "I agree, I disagree, I see your point",
             "أوافق، لا أوافق، أفهم وجهة نظرك",
             "I disagree — I think it's too hard.", "speaking", 22),
            ("Discussion phrases", "عبارات النقاش", 6,
             "on the one hand, on the other hand",
             "من جهة، من جهة أخرى",
             "On the one hand it's cheap, on the other it's old.", "speaking", 25),
            ("Social media topic", "موضوع وسائل التواصل", 6,
             "—", "—", "—", "vocabulary", 15),
            ("Environment & climate", "البيئة والمناخ", 6,
             "—", "—", "—", "vocabulary", 18),
            ("Short presentation", "عرض قصير", 6,
             "introduction, main point, conclusion",
             "مقدمة، نقطة رئيسية، خاتمة",
             "Today, I want to talk about …", "speaking", 30),
            # +7 gap-fill (to reach 48)
            ("Used to vs would for past habits", "used to و would للعادات", 1,
             "used to + base / would + base for past habits",
             "used to + الفعل أو would + الفعل = عادات ماضية",
             "I used to wake up at 5. I would help my dad.", "grammar", 25),
            ("Present perfect with by now", "المضارع التام مع by now", 2,
             "By now / so far + present perfect",
             "By now / so far + المضارع التام",
             "I've finished three units so far.", "grammar", 25),
            ("Going-to vs will", "going-to مقابل will", 3,
             "going-to = plan, will = spontaneous decision",
             "going-to = خطة، will = قرار آني",
             "I'll get it! (will) vs I'm going to study tonight.", "grammar", 25),
            ("Few vs little revisited", "few مقابل little معمَّق", 4,
             "few = small countable, little = small uncountable",
             "few للمعدود قليلة، little لغير المعدود قليل",
             "We have few apples and little time.", "grammar", 22),
            ("Engagement and wedding vocabulary", "مفردات الخطبة والزواج", 5,
             "—", "—", "—", "vocabulary", 18),
            ("Entry-level job interviews", "مقابلات عمل للمبتدئين", 6,
             "Tell me about yourself / Why this job?",
             "حدثني عن نفسك / لماذا هذه الوظيفة؟",
             "Thank you for inviting me. I'm Amani …", "speaking", 28),
            ("Writing a CV — basics", "كتابة سيرة ذاتية أساسية", 6,
             "Name, contact, experience, education, skills",
             "الاسم، التواصل، الخبرة، التعليم، المهارات",
             "Education: B.Sc., University of Khartoum, 2024.", "writing", 30),
        ],
    },

    # =====================================================================
    # B1 — Intermediate
    # =====================================================================
    {
        "code": "B1",
        "course_slug": "onlenco-intermediate",
        "course_title_en": "Onlenco Intermediate English (B1)",
        "course_title_ar": "Onlenco — الإنجليزية المتوسطة (B1)",
        "course_desc_en": (
            "A 48-unit Intermediate course. Past perfect, second conditional, "
            "reported speech, passives, modal verbs, phrasal verbs. American "
            "English."
        ),
        "course_desc_ar": (
            "كورس من 48 وحدة لمستوى B1 المتوسط. الماضي التام، الشرطي "
            "الثاني، الكلام المنقول، المبني للمجهول، الأفعال الناقصة، "
            "الأفعال المركبة. إنجليزية أمريكية."
        ),
        "clusters": [
            "Past perfect & sequencing",
            "Conditionals — real & hypothetical",
            "Reported speech",
            "Passive voice",
            "Modals — possibility, deduction, regret",
            "Phrasal verbs & idioms",
        ],
        "topics": [
            ("Past perfect — had + past participle", "الماضي التام", 1,
             "had + past participle",
             "had + التصريف الثالث = ماضي قبل ماضي",
             "When I arrived, the train had left.", "grammar", 30),
            ("By the time, before, after", "by the time, before, after", 1,
             "sequencing past actions", "ترتيب الأحداث الماضية",
             "By the time we got there, it had ended.", "grammar", 25),
            ("Narrative tenses combined", "تجمع أزمنة السرد", 1,
             "past simple + past continuous + past perfect",
             "تجمع الأزمنة الماضية",
             "I was walking when I noticed I had forgotten my keys.", "grammar", 30),
            ("News stories", "قصص الأخبار", 1,
             "—", "—", "—", "vocabulary", 18),
            ("Personal stories", "حكايات شخصية", 1,
             "structured narrative", "السرد المنظم",
             "I'll never forget the day I …", "speaking", 30),
            ("Mystery and crime", "الغموض والجريمة", 1,
             "—", "—", "—", "vocabulary", 15),
            ("Writing a short story", "كتابة قصة قصيرة", 1,
             "setup, conflict, resolution",
             "البداية، الصراع، الحل",
             "It was a dark night when …", "writing", 35),
            ("Famous historical events", "أحداث تاريخية شهيرة", 1,
             "happened, occurred, took place",
             "حدث، وقع، تمّ",
             "The pyramids were built thousands of years ago.", "speaking", 25),

            ("Zero conditional review", "مراجعة الشرطي الصفري", 2,
             "If + present, present", "إذا + مضارع، مضارع = حقيقة",
             "If you heat water, it boils.", "grammar", 22),
            ("Second conditional", "الشرطي الثاني", 2,
             "If + past, would + base",
             "If + ماضي، would + الفعل = افتراض",
             "If I had more time, I would travel more.", "grammar", 30),
            ("Wishes and regrets", "الأمنيات والندم", 2,
             "I wish I had/were …", "أتمنى لو أن …",
             "I wish I were taller.", "grammar", 25),
            ("Imaginary scenarios", "سيناريوهات افتراضية", 2,
             "What would you do if …?", "ماذا كنت ستفعل لو …؟",
             "What would you do if you won the lottery?", "speaking", 28),
            ("Hopes and dreams", "الآمال والأحلام", 2,
             "—", "—", "—", "vocabulary", 15),
            ("Giving advice with second conditional", "النصيحة بالشرطي الثاني", 2,
             "If I were you, I would …", "لو كنت مكانك، لـ …",
             "If I were you, I would call her.", "speaking", 25),
            ("Travel dreams", "أحلام السفر", 2,
             "—", "—", "—", "vocabulary", 15),

            ("Reported statements", "الكلام المنقول — الجمل", 3,
             "He said (that) he was tired.",
             "قال إنه كان متعباً (التحويل الزمني)",
             "She said she was busy.", "grammar", 30),
            ("Reported questions", "الكلام المنقول — الأسئلة", 3,
             "asked if/whether, asked what/where",
             "سأل إن كان، سأل أين/ماذا",
             "He asked where I lived.", "grammar", 28),
            ("Reported commands", "الكلام المنقول — الأوامر", 3,
             "told someone to do, asked not to",
             "أمر بأن، طلب ألا",
             "She told me to wait here.", "grammar", 25),
            ("Verbs of reporting", "أفعال النقل", 3,
             "said, told, asked, replied, claimed",
             "قال، أخبر، سأل، أجاب، ادعى",
             "He claimed he was innocent.", "grammar", 22),
            ("Gossip and news", "الإشاعات والأخبار", 3,
             "—", "—", "—", "vocabulary", 15),
            ("Interview reporting", "تقارير المقابلات", 3,
             "she said her plan was …",
             "قالت إن خطتها كانت …",
             "He said he wanted to study abroad.", "writing", 28),

            ("Passive — present", "المبني للمجهول — مضارع", 4,
             "is/are + past participle",
             "is/are + التصريف الثالث = يُفعل",
             "The book is written in English.", "grammar", 28),
            ("Passive — past", "المبني للمجهول — ماضي", 4,
             "was/were + past participle",
             "was/were + التصريف الثالث",
             "The window was broken yesterday.", "grammar", 25),
            ("Passive — by + agent", "by + الفاعل", 4,
             "passive + by + agent",
             "مجهول + by + المنفّذ",
             "The cake was made by Salma.", "grammar", 22),
            ("Things made and built", "أشياء صُنعت وبُنيت", 4,
             "—", "—", "—", "vocabulary", 15),
            ("Process descriptions", "وصف العمليات", 4,
             "First …, next …, finally is + done",
             "أولاً، بعد ذلك، أخيراً يُفعَل",
             "First, the rice is washed.", "writing", 28),
            ("News headlines (passive)", "عناوين الأخبار", 4,
             "headlines often use passive",
             "العناوين كثيراً ما تستخدم المبني للمجهول",
             "Three men were arrested today.", "reading", 25),

            ("Possibility with might / may / could", "الاحتمال", 5,
             "might / may / could + base", "may / might / could للاحتمال",
             "She might be at home.", "grammar", 28),
            ("Deduction with must / can't", "الاستنتاج", 5,
             "must = strong yes, can't = strong no",
             "must = استنتاج إيجابي قوي، can't = استنتاج سلبي قوي",
             "He must be tired — he's been working all day.", "grammar", 28),
            ("Regret with should have", "الندم بـ should have", 5,
             "should have + past participle",
             "should have + التصريف الثالث = كان عليّ",
             "I should have studied harder.", "grammar", 25),
            ("Obligation past — had to", "الإلزام في الماضي", 5,
             "had to + base verb", "had to + الفعل = اضطُررت",
             "I had to leave early.", "grammar", 22),
            ("Difficult decisions", "قرارات صعبة", 5,
             "I'm torn between …, on balance …",
             "أتأرجح بين …، في المحصلة …",
             "I'm torn between two job offers.", "speaking", 28),
            ("Looking back on choices", "نظرة على القرارات السابقة", 5,
             "If I had …, I would have …",
             "لو كنت … لكنت قد …",
             "If I had studied more, I would have passed.", "grammar", 30),

            ("Phrasal verbs — get", "أفعال مركبة — get", 6,
             "get up, get on, get along, get over",
             "ينهض، يركب، ينسجم، يتجاوز",
             "I get up at 6 every day.", "grammar", 25),
            ("Phrasal verbs — turn", "أفعال مركبة — turn", 6,
             "turn on/off, turn down, turn up",
             "يشغّل/يطفئ، يخفّض، يرفع",
             "Could you turn the music down?", "grammar", 25),
            ("Phrasal verbs — give", "أفعال مركبة — give", 6,
             "give up, give in, give back, give away",
             "يستسلم، يرضخ، يعيد، يهب",
             "Don't give up — keep trying!", "grammar", 25),
            ("Common idioms", "تعابير شائعة", 6,
             "—", "—", "—", "vocabulary", 18),
            ("Business idioms", "تعابير العمل", 6,
             "touch base, on the same page",
             "نتواصل، على نفس الصفحة",
             "Let's touch base next week.", "vocabulary", 20),
            ("Formal vs informal register", "الرسمي مقابل غير الرسمي", 6,
             "could you vs can you, regards vs cheers",
             "could أكثر رسمية من can",
             "Could you possibly help me?", "speaking", 25),
            # +9 gap-fill (to reach 48)
            ("Reported requests", "نقل الطلبات", 3,
             "asked someone to do, told someone to do",
             "طلب من شخص أن، أخبر شخصاً أن",
             "She asked me to call back later.", "grammar", 25),
            ("Past simple in news writing", "الماضي البسيط في الأخبار", 1,
             "Use simple past for completed events.",
             "نستخدم الماضي البسيط للأحداث المكتملة.",
             "Officials announced the new policy yesterday.", "writing", 25),
            ("Verb + gerund vs infinitive", "فعل + gerund أو infinitive", 2,
             "stop doing vs stop to do",
             "stop doing مختلفة عن stop to do",
             "I stopped smoking. I stopped to smoke.", "grammar", 28),
            ("Get + adjective for change", "get + صفة لتعبير التغيّر", 4,
             "get tired, get hungry, get angry",
             "يصبح متعباً، جائعاً، غاضباً",
             "I get tired around 9 pm.", "grammar", 22),
            ("Future perfect", "المستقبل التام", 5,
             "will have + past participle",
             "will have + التصريف الثالث",
             "By 2030, I will have graduated.", "grammar", 28),
            ("Future continuous", "المستقبل المستمر", 5,
             "will be + verb-ing",
             "will be + فعل-ing = حدث في المستقبل",
             "This time tomorrow, I'll be flying.", "grammar", 28),
            ("Phrasal verbs — put", "أفعال مركبة — put", 6,
             "put on, put off, put up with, put down",
             "يرتدي، يؤجل، يتحمّل، يضع",
             "I can't put up with this noise.", "grammar", 25),
            ("Phrasal verbs — take", "أفعال مركبة — take", 6,
             "take off, take on, take over, take after",
             "يقلع، يتولّى، يستحوذ، يشبه",
             "She takes after her mother.", "grammar", 25),
            ("Phrasal verbs — make", "أفعال مركبة — make", 6,
             "make up, make out, make it, make do",
             "يختلق، يفهم، ينجح، يكتفي",
             "I made it on time!", "grammar", 25),
        ],
    },

    # =====================================================================
    # B2 — Upper-Intermediate
    # =====================================================================
    {
        "code": "B2",
        "course_slug": "onlenco-upper-intermediate",
        "course_title_en": "Onlenco Upper-Intermediate English (B2)",
        "course_title_ar": "Onlenco — الإنجليزية فوق المتوسطة (B2)",
        "course_desc_en": (
            "A 48-unit Upper-Intermediate course. Mixed conditionals, "
            "advanced passives, cleft sentences, inversions, register "
            "shifting. American English."
        ),
        "course_desc_ar": (
            "كورس من 48 وحدة لمستوى B2 فوق المتوسط. الشرطيات المختلطة، "
            "المبني للمجهول المتقدم، الجمل المقسومة، الانعكاس، تبديل "
            "المسجّل اللغوي. إنجليزية أمريكية."
        ),
        "clusters": [
            "Advanced conditionals",
            "Advanced passives & causatives",
            "Cleft, inversion & emphasis",
            "Complex relative clauses",
            "Register & nuance",
            "Discussion & debate",
        ],
        "topics": [
            ("Third conditional", "الشرطي الثالث", 1,
             "If + past perfect, would have + past participle",
             "لو + الماضي التام، لكان قد + التصريف الثالث",
             "If I had known, I would have called.", "grammar", 32),
            ("Mixed conditionals", "الشرطيات المختلطة", 1,
             "Type 2 + Type 3 mix", "خلط الشرطي الثاني والثالث",
             "If I were taller, I would have made the team.", "grammar", 30),
            ("Wish + past perfect", "wish + الماضي التام", 1,
             "I wish I had / hadn't …", "أتمنى لو كنت قد …",
             "I wish I hadn't said that.", "grammar", 25),
            ("Counterfactual stories", "قصص افتراضية", 1,
             "imagining alternative pasts", "تخيل ماضٍ بديل",
             "What if Sudan had won the cup?", "speaking", 30),
            ("Regret in writing", "التعبير عن الندم كتابياً", 1,
             "if only, had I known", "لو فقط، لو كنت أعلم",
             "If only I had taken that job.", "writing", 28),
            ("Hypothetical job interviews", "مقابلات عمل افتراضية", 1,
             "If you were the manager, what would you do?",
             "لو كنت المدير، ماذا كنت ستفعل؟",
             "If I were CEO, I would prioritize training.", "speaking", 32),
            ("Wishes for the world", "أمنيات لعالم أفضل", 1,
             "If only the world were …", "لو كان العالم …",
             "If only there were less pollution.", "writing", 25),
            ("Idioms of regret", "تعابير الندم", 1,
             "kicking yourself, hindsight is 20/20",
             "تلوم نفسك، الندم لا يفيد",
             "I was kicking myself for missing it.", "vocabulary", 22),

            ("Passive in all tenses", "المبني للمجهول في كل الأزمنة", 2,
             "have been, will be, is being",
             "تم، سوف، يجري",
             "The report has been submitted.", "grammar", 30),
            ("Passive infinitive & gerund", "مصدر/اسم فعل مبني للمجهول", 2,
             "to be done, being done",
             "أن يُفعل، كونه يُفعل",
             "She doesn't like being interrupted.", "grammar", 25),
            ("Get-passive", "المبني للمجهول بـ get", 2,
             "got robbed, get fired",
             "تعرّض للسرقة، طُرد من العمل",
             "He got promoted last month.", "grammar", 22),
            ("Causative — have something done", "have / get + شيء + done", 2,
             "I had my hair cut.", "قصصت شعري (شخص فعلها لي)",
             "She got her car repaired.", "grammar", 28),
            ("Reporting passive", "نقل المبني للمجهول", 2,
             "It is said that …, He is believed to …",
             "يُقال إن …، يُعتقد أنه …",
             "It is said that he won the prize.", "grammar", 28),
            ("News writing style", "أسلوب كتابة الأخبار", 2,
             "passive + by-agent omitted",
             "مجهول مع حذف الفاعل",
             "Five suspects were arrested.", "writing", 25),

            ("Cleft sentences — It was X who", "الجمل المقسومة — It-cleft", 3,
             "It was X who/that …",
             "كان X هو الذي …",
             "It was Salma who called.", "grammar", 28),
            ("Cleft sentences — What I", "الجمل المقسومة — What-cleft", 3,
             "What I need is …", "ما أحتاج إليه هو …",
             "What I really want is peace.", "grammar", 25),
            ("Inversion with negative adverbials", "الانعكاس بظروف النفي", 3,
             "Never have I seen …", "لم يسبق أن رأيت …",
             "Never had I felt so happy.", "grammar", 30),
            ("Inversion in conditionals", "الانعكاس في الشرطيات", 3,
             "Had I known …, Should you need …",
             "لو علمت …، إذا احتجت …",
             "Had I known, I would have called.", "grammar", 28),
            ("Emphasis with do/does/did", "التوكيد بـ do/does/did", 3,
             "I do believe …, She did go …",
             "أعتقد فعلاً …، ذهبت حقاً …",
             "I do appreciate your help.", "grammar", 22),
            ("Public speaking", "الخطابة", 3,
             "rhetorical devices", "أدوات بلاغية",
             "Not only did we win, but we also …", "speaking", 30),

            ("Defining vs non-defining clauses", "الجمل الموصولة", 4,
             "with/without commas", "بفواصل وبدونها",
             "The book that you gave me was great.", "grammar", 28),
            ("Whose, where, when relative", "whose, where, when", 4,
             "relative pronouns", "ضمائر الموصول",
             "That's the man whose wife is a doctor.", "grammar", 25),
            ("Reduced relative clauses", "الجمل الموصولة المختصرة", 4,
             "the man sitting there = who is sitting",
             "ع: الرجل الجالس = الذي يجلس",
             "The book lying on the table is mine.", "grammar", 28),
            ("Prepositions in relative clauses", "حروف الجر في الموصول", 4,
             "the woman to whom I spoke",
             "السيدة التي تحدثت إليها",
             "The friend with whom I traveled is here.", "grammar", 25),
            ("Complex descriptions", "أوصاف مركبة", 4,
             "—", "—", "—", "vocabulary", 18),
            ("Academic descriptions", "وصف أكاديمي", 4,
             "an approach which …, a theory whereby …",
             "نهج … ، نظرية بموجبها …",
             "An approach which combines two methods.", "writing", 28),

            ("Formal vs informal vocabulary", "المفردات الرسمية", 5,
             "purchase vs buy, commence vs start",
             "يشتري (رسمي) مقابل (عادي)",
             "We will commence at 9 am.", "vocabulary", 25),
            ("Polite disagreement", "الاختلاف بأدب", 5,
             "I see your point, but …", "أتفهم ما تقول، لكن …",
             "I understand, but I have to disagree.", "speaking", 22),
            ("Hedging language", "اللغة التحفظية", 5,
             "It seems that …, It would appear …",
             "يبدو أن …، يبدو ظاهرياً …",
             "It seems we have a problem.", "speaking", 25),
            ("Hyperbole and understatement", "المبالغة والتقليل", 5,
             "I'm starving / I'm a bit peckish",
             "أتضوّر جوعاً / أشعر بجوع طفيف",
             "I'm absolutely starving!", "speaking", 22),
            ("Irony and sarcasm", "السخرية والتهكم", 5,
             "tone-dependent", "معتمد على النبرة",
             "Oh great, another rainy day.", "speaking", 22),
            ("Body language", "لغة الجسد", 5,
             "—", "—", "—", "vocabulary", 15),

            ("Debate structure", "بنية المناظرة", 6,
             "claim → evidence → warrant",
             "ادعاء → دليل → تفسير",
             "I claim that … because …", "speaking", 32),
            ("Refutation techniques", "تقنيات الدحض", 6,
             "However, this overlooks …", "لكن هذا يتغافل عن …",
             "However, this argument overlooks key facts.", "speaking", 28),
            ("Citing evidence", "الاستشهاد بالأدلة", 6,
             "According to …, Research shows …",
             "وفقاً لـ …، تظهر الأبحاث …",
             "According to a 2024 study, …", "writing", 25),
            ("Persuasive essays", "المقالات الإقناعية", 6,
             "thesis, support, counter, conclusion",
             "الأطروحة، الدعم، النقض، الخاتمة",
             "There are three reasons why …", "writing", 35),
            ("Globalization", "العولمة", 6,
             "—", "—", "—", "vocabulary", 20),
            ("Politics & policy", "السياسة والسياسات", 6,
             "—", "—", "—", "vocabulary", 20),
            # +10 gap-fill (to reach 48)
            ("Inverted conditionals", "الانعكاس في الشرطيات", 1,
             "Had I known, Should you …",
             "لو علمت، إذا احتجت …",
             "Had we left earlier, we'd be home now.", "grammar", 30),
            ("Wish + would", "wish + would", 1,
             "expressing annoyance: I wish he would …",
             "تعبير الإزعاج: أتمنى لو يـ …",
             "I wish he would stop interrupting.", "grammar", 25),
            ("Have something done — review", "have/get شيء + done — مراجعة", 2,
             "causative review", "مراجعة السببية",
             "I had my hair cut. I got my car washed.", "grammar", 22),
            ("Reduced participle clauses", "الجمل المختصرة بالمشتقات", 3,
             "Walking down the street, I saw …",
             "أثناء المشي في الشارع، رأيت …",
             "Tired from work, she went to bed.", "grammar", 28),
            ("Relative + preposition variants", "حروف الجر في الموصول", 4,
             "the person to whom I wrote",
             "الشخص الذي كتبت إليه",
             "The colleague with whom I work is great.", "grammar", 28),
            ("Tense narration shifts", "تحوّلات الزمن في السرد", 5,
             "shifting between past and historic present",
             "التنقل بين الماضي والمضارع الحاضر",
             "So he walks in and says …", "speaking", 25),
            ("Idioms about money", "تعابير المال", 5,
             "break the bank, cost an arm and a leg, save for a rainy day",
             "يكلف الكثير، يدخر للأيام الصعبة",
             "That dress cost an arm and a leg.", "vocabulary", 22),
            ("Connotation analysis", "تحليل الدلالة", 5,
             "thrifty (positive) vs cheap (negative)",
             "مقتصد (إيجابي) مقابل بخيل (سلبي)",
             "I prefer 'thrifty' to 'cheap'.", "reading", 25),
            ("Argument essay structure", "بنية مقال الحجة", 6,
             "intro → 3 arguments → counter → conclusion",
             "مقدمة → 3 حجج → مخالفة → خاتمة",
             "First, … Second, … However, opponents argue …", "writing", 35),
            ("Counter-argument paragraphs", "فقرات الحجج المضادة", 6,
             "Critics argue …, On the other hand …",
             "يرى المنتقدون …، من جهة أخرى …",
             "Critics argue this approach is costly.", "writing", 30),
        ],
    },

    # =====================================================================
    # C1 — Advanced
    # =====================================================================
    {
        "code": "C1",
        "course_slug": "onlenco-advanced",
        "course_title_en": "Onlenco Advanced English (C1)",
        "course_title_ar": "Onlenco — الإنجليزية المتقدمة (C1)",
        "course_desc_en": (
            "A 48-unit Advanced course. Subjunctive, advanced cohesion, "
            "register shifting, idioms, academic and professional writing. "
            "American English."
        ),
        "course_desc_ar": (
            "كورس من 48 وحدة لمستوى C1 المتقدم. صيغة الشرط، التماسك "
            "المتقدم، تبديل المسجل، التعابير الاصطلاحية، الكتابة "
            "الأكاديمية والمهنية. إنجليزية أمريكية."
        ),
        "clusters": [
            "Subjunctive & formal grammar",
            "Cohesion & discourse markers",
            "Idiomatic expression",
            "Academic English",
            "Professional contexts",
            "Critical thinking",
        ],
        "topics": [
            ("Subjunctive mood", "صيغة الشرط (الـ subjunctive)", 1,
             "I suggest he be / It is essential that she go",
             "أقترح أن يـ / من الضروري أن يـ",
             "I insisted that he be on time.", "grammar", 30),
            ("Formal suggestion verbs", "أفعال الاقتراح الرسمية", 1,
             "recommend, propose, request that …",
             "يوصي، يقترح، يطلب أن …",
             "We recommend that the policy be revised.", "grammar", 25),
            ("Should in formal contexts", "should في السياقات الرسمية", 1,
             "If you should need …", "إن احتجت …",
             "Should you require assistance, please call.", "grammar", 28),
            ("Past subjunctive — were", "were في الشرطيات", 1,
             "If I were you, As if she were …",
             "لو كنت مكانك، كأنها …",
             "If I were in your position, I would resign.", "grammar", 25),
            ("Formal letters", "الرسائل الرسمية", 1,
             "Dear Sir/Madam, Yours faithfully",
             "السيد المحترم، مع تحياتي",
             "Dear Sir, I am writing to express …", "writing", 30),
            ("Conditionals in formal writing", "الشرطيات في الكتابة الرسمية", 1,
             "Were the proposal accepted, …",
             "لو قُبل المقترح …",
             "Were the law changed, businesses would adapt.", "grammar", 28),
            ("Suppose / supposing", "suppose / supposing", 1,
             "hypothetical openings", "افتتاحيات افتراضية",
             "Supposing that he were here, what would he say?", "grammar", 25),
            ("Hypothesizing in essays", "الافتراض في المقالات", 1,
             "Imagine a world where …",
             "تخيّل عالماً حيث …",
             "Imagine a society without inequality.", "writing", 32),

            ("Discourse markers — addition", "موصلات الإضافة", 2,
             "furthermore, moreover, in addition",
             "علاوة على ذلك، إضافة إلى ذلك",
             "Furthermore, the data supports …", "writing", 22),
            ("Discourse markers — contrast", "موصلات التضاد", 2,
             "however, nevertheless, on the contrary",
             "ومع ذلك، رغم ذلك، على العكس",
             "Nevertheless, the experiment was successful.", "writing", 22),
            ("Discourse markers — cause/effect", "موصلات السبب والنتيجة", 2,
             "consequently, hence, therefore",
             "بالتالي، من ثَمَّ، لذلك",
             "The data was lost; consequently, the study failed.", "writing", 22),
            ("Discourse markers — example", "موصلات الأمثلة", 2,
             "for instance, namely, in particular",
             "على سبيل المثال، أعني، خصوصاً",
             "Many countries — namely, Sudan and Egypt …", "writing", 22),
            ("Cohesion in spoken English", "التماسك في الحديث", 2,
             "anyway, by the way, on a related note",
             "على أي حال، بالمناسبة، في موضوع متصل",
             "By the way, did you hear about the meeting?", "speaking", 22),
            ("Anaphora and reference", "الإحالة والمرجع", 2,
             "this / that / such / it",
             "هذا / ذلك / هكذا / ذاك",
             "Such an approach has been criticized.", "writing", 25),
            ("Academic paragraphs", "الفقرات الأكاديمية", 2,
             "topic sentence → support → conclusion",
             "الجملة الموضوعية → دعم → خاتمة",
             "The argument hinges on two points.", "writing", 30),

            ("Idiomatic verb phrases", "تعابير فعلية اصطلاحية", 3,
             "take stock, draw the line, turn a blind eye",
             "يقيّم، يضع حداً، يتغاضى",
             "We need to take stock of the situation.", "vocabulary", 25),
            ("Idioms about success/failure", "تعابير النجاح والفشل", 3,
             "hit the jackpot, fall flat, bomb out",
             "ربح الجائزة الكبرى، فشل، أخفق",
             "His presentation fell flat.", "vocabulary", 22),
            ("Idioms about communication", "تعابير التواصل", 3,
             "beat around the bush, get to the point, in a nutshell",
             "يلفّ ويدور، يدخل في الموضوع، باختصار",
             "Stop beating around the bush.", "vocabulary", 25),
            ("Idioms about people", "تعابير عن الناس", 3,
             "a couch potato, a night owl, a go-getter",
             "كسول، ساهر، طموح",
             "He's a night owl — he works until 2 am.", "vocabulary", 22),
            ("Metaphor in everyday English", "الاستعارة في الإنجليزية اليومية", 3,
             "time is money, life is a journey",
             "الوقت من ذهب، الحياة رحلة",
             "Life is a journey, not a destination.", "speaking", 25),
            ("Collocations — strong/heavy", "المتلازمات اللفظية", 3,
             "strong coffee, heavy rain, deep sleep",
             "قهوة قوية، مطر غزير، نوم عميق",
             "I need a strong coffee.", "grammar", 22),

            ("Academic register", "المسجل الأكاديمي", 4,
             "this paper argues, the data suggests",
             "تجادل هذه الورقة، تشير البيانات",
             "This paper argues that climate change …", "writing", 28),
            ("Hedging in academic writing", "التحفظ في الكتابة الأكاديمية", 4,
             "may, tends to, somewhat, partially",
             "قد، يميل إلى، إلى حد ما، جزئياً",
             "The results may suggest a trend.", "writing", 25),
            ("Citing and quoting", "الاستشهاد والاقتباس", 4,
             "Smith (2024) claims … / As Smith puts it …",
             "يدعي سميث (2024) / كما يصوغها سميث",
             "Smith (2024) argues that …", "writing", 25),
            ("Paraphrasing skills", "مهارات إعادة الصياغة", 4,
             "rewording with synonyms + structure change",
             "إعادة صياغة بمرادفات وتغيير البنية",
             "In other words, …", "writing", 28),
            ("Synthesizing sources", "تركيب المصادر", 4,
             "while X argues …, Y maintains …",
             "بينما يرى X …، يؤكد Y …",
             "While Adams argues …, Brown maintains …", "writing", 30),
            ("Essay structures", "بنى المقالات", 4,
             "compare/contrast, problem/solution, argument",
             "مقارنة، مشكلة/حل، حجة",
             "There are two main approaches …", "writing", 32),

            ("Negotiation language", "لغة التفاوض", 5,
             "I'd be willing to … if you …",
             "أنا مستعد لـ … إذا أنت …",
             "We'd be willing to consider that if …", "speaking", 28),
            ("Diplomatic disagreement", "الاختلاف الدبلوماسي", 5,
             "with all due respect, I'm afraid I disagree",
             "مع كل الاحترام، آسف أن أخالف",
             "With respect, I think there's another view.", "speaking", 25),
            ("Boardroom English", "إنجليزية مجالس الإدارة", 5,
             "—", "—", "—", "vocabulary", 20),
            ("Project management English", "إنجليزية إدارة المشاريع", 5,
             "stakeholder, deliverable, scope creep",
             "أصحاب المصلحة، المخرج، توسع النطاق",
             "We need to manage the scope of this project.", "vocabulary", 22),
            ("Job interview English", "إنجليزية مقابلات العمل", 5,
             "Tell me about a time when …",
             "حدّثني عن وقت كنت فيه …",
             "Tell me about a time you led a team.", "speaking", 30),
            ("Salary negotiation", "التفاوض على الراتب", 5,
             "Based on market data, I'd expect …",
             "بناءً على بيانات السوق، أتوقع …",
             "Based on industry standards, I'd expect $X.", "speaking", 25),

            ("Critical reading", "القراءة النقدية", 6,
             "what's the author's claim?", "ما ادعاء الكاتب؟",
             "The author's central claim is …", "reading", 28),
            ("Spotting bias", "اكتشاف التحيز", 6,
             "loaded language, selective evidence",
             "لغة محملة، أدلة انتقائية",
             "This source uses loaded language.", "reading", 25),
            ("Evaluating sources", "تقييم المصادر", 6,
             "credibility, recency, relevance",
             "المصداقية، الحداثة، الصلة",
             "Is this source credible? Recent?", "reading", 25),
            ("Logical fallacies", "المغالطات المنطقية", 6,
             "straw man, ad hominem, false dichotomy",
             "ضرب رجل قش، التهجم الشخصي، الثنائية الزائفة",
             "That's an ad hominem attack.", "reading", 28),
            ("Critical writing", "الكتابة النقدية", 6,
             "evaluating without dismissing", "التقييم دون رفض",
             "While this argument has merit, it ignores …", "writing", 30),
            ("Discussion essays", "مقالات النقاش", 6,
             "balanced view + opinion at end",
             "نظرة متوازنة + رأي في النهاية",
             "This essay will consider both sides …", "writing", 35),
            # +9 gap-fill (to reach 48)
            ("Inverted past subjunctive", "الانعكاس في الشرط الماضي", 1,
             "Were I to … / Had I known …",
             "لو كنت لـ … / لو علمت …",
             "Were I to see her, I would tell her.", "grammar", 28),
            ("Present perfect continuous mastery", "إتقان المضارع التام المستمر", 2,
             "have been doing — duration + ongoing",
             "have been doing — مدة مستمرة",
             "I have been working on this for hours.", "grammar", 28),
            ("Substitution and ellipsis", "البدل والحذف", 2,
             "do so, the same, neither / so do I",
             "افعل ذلك، نفس الشيء، أنا أيضاً",
             "I'm going. So am I.", "grammar", 25),
            ("Idiomatic prepositions", "حروف الجر الاصطلاحية", 3,
             "by all means, in no time, at length",
             "بكل تأكيد، في وقت قصير، باستفاضة",
             "She spoke at length about her project.", "vocabulary", 25),
            ("Collocations — work register", "متلازمات لفظية للعمل", 4,
             "deliver results, meet deadlines, exceed expectations",
             "تحقيق النتائج، الالتزام بالمواعيد، تجاوز التوقعات",
             "We need to deliver results this quarter.", "vocabulary", 22),
            ("Synonym precision", "دقة المرادفات", 4,
             "big vs huge vs vast vs immense",
             "كبير، ضخم، شاسع، هائل — اختر الأدق",
             "The data set is vast, not just big.", "vocabulary", 25),
            ("Executive summaries", "الملخصات التنفيذية", 5,
             "1 page, key findings, recommendations",
             "صفحة واحدة، نتائج رئيسية، توصيات",
             "This report finds three key issues.", "writing", 32),
            ("Strategic communication", "التواصل الاستراتيجي", 5,
             "stakeholder framing, message hierarchy",
             "تأطير أصحاب المصلحة، تسلسل الرسائل",
             "For executives: lead with the bottom line.", "speaking", 30),
            ("Analytical writing", "الكتابة التحليلية", 6,
             "claim → evidence → analysis → so-what",
             "ادعاء → دليل → تحليل → ماذا يعني هذا",
             "This means the policy needs revising because …", "writing", 35),
        ],
    },

    # =====================================================================
    # C2 — Mastery
    # =====================================================================
    {
        "code": "C2",
        "course_slug": "onlenco-mastery",
        "course_title_en": "Onlenco Mastery English (C2)",
        "course_title_ar": "Onlenco — الإنجليزية المتقنة (C2)",
        "course_desc_en": (
            "A 48-unit Mastery course. Native-level nuance, literary devices, "
            "specialized registers, advanced rhetoric, idiomatic mastery. "
            "American English."
        ),
        "course_desc_ar": (
            "كورس من 48 وحدة لمستوى C2 المتقن. الفروق الدقيقة بمستوى "
            "أهل اللغة، الأدوات الأدبية، المسجلات المتخصصة، البلاغة "
            "المتقدمة، التمكن من التعابير. إنجليزية أمريكية."
        ),
        "clusters": [
            "Literary & figurative language",
            "Advanced register & tone",
            "Specialized domains",
            "Rhetoric & persuasion",
            "Cultural fluency",
            "Mastery review & integration",
        ],
        "topics": [
            ("Metaphor analysis", "تحليل الاستعارة", 1,
             "extended metaphors, conceptual metaphors",
             "الاستعارات الممتدة، الاستعارات المفهومية",
             "Love is a journey — what's the destination?", "reading", 30),
            ("Simile, allegory, allusion", "التشبيه، الرمز، التلميح", 1,
             "spotting figurative devices", "اكتشاف الأدوات المجازية",
             "She was as cold as ice.", "reading", 28),
            ("Personification", "التشخيص", 1,
             "objects acting as humans", "تجسيد الأشياء",
             "The wind whispered through the trees.", "writing", 25),
            ("Irony types", "أنواع السخرية", 1,
             "verbal, situational, dramatic",
             "لفظية، موقفية، درامية",
             "Dramatic irony: the audience knows but the character doesn't.", "reading", 28),
            ("Reading poetry", "قراءة الشعر", 1,
             "rhyme, meter, imagery", "القافية، البحر، الصور",
             "Iambic pentameter is a meter with 5 feet.", "reading", 30),
            ("Symbolism in prose", "الرمزية في النثر", 1,
             "objects with meanings beyond literal",
             "أشياء ذات معانٍ تتجاوز الحرفي",
             "The river symbolizes time passing.", "reading", 28),
            ("Writing with figurative language", "الكتابة المجازية", 1,
             "balanced use — not overdone", "استخدام متوازن — دون مبالغة",
             "Her voice was sunshine on a winter day.", "writing", 32),
            ("Translating idioms", "ترجمة التعابير", 1,
             "find equivalent vs literal", "إيجاد المكافئ مقابل الحرفي",
             "'It's raining cats and dogs' = تمطر بغزارة", "vocabulary", 25),

            ("Formal academic register", "المسجل الأكاديمي الرسمي", 2,
             "nominalization, passive, abstract nouns",
             "التسمية، المجهول، الأسماء المجردة",
             "The implementation of the policy required …", "writing", 30),
            ("Legal English", "الإنجليزية القانونية", 2,
             "whereas, hereby, party of the first part",
             "حيث إن، بموجب هذا، الطرف الأول",
             "The parties hereby agree …", "reading", 28),
            ("Medical English", "الإنجليزية الطبية", 2,
             "diagnosis, prognosis, etiology",
             "التشخيص، التنبؤ، السبب",
             "The prognosis is favorable.", "vocabulary", 25),
            ("Technical English", "الإنجليزية التقنية", 2,
             "specifications, deployment, latency",
             "المواصفات، النشر، التأخير",
             "The deployment latency exceeded specifications.", "vocabulary", 25),
            ("Switching registers fluently", "التبديل بين المسجلات", 2,
             "formal email → casual chat → presentation",
             "بريد رسمي → دردشة → عرض",
             "Same message, three different tones.", "speaking", 30),
            ("Tone analysis", "تحليل النبرة", 2,
             "informative, persuasive, accusatory",
             "إعلامية، إقناعية، اتهامية",
             "The author's tone here is accusatory.", "reading", 25),
            ("Maintaining tone consistency", "ثبات النبرة", 2,
             "watch register breaks", "احترس من انكسارات المسجل",
             "Don't shift from formal to slangy mid-essay.", "writing", 28),

            ("English of business strategy", "إنجليزية الاستراتيجية", 3,
             "synergy, leverage, value proposition",
             "التآزر، الاستفادة، عرض القيمة",
             "Our value proposition is innovation.", "vocabulary", 25),
            ("English of finance", "إنجليزية المالية", 3,
             "equity, leverage, hedge, derivatives",
             "حقوق الملكية، الاستدانة، التحوّط، المشتقات",
             "We need to hedge against currency risk.", "vocabulary", 25),
            ("English of academia", "إنجليزية الأكاديميا", 3,
             "peer review, publish or perish",
             "مراجعة الأقران، انشر أو امضِ",
             "His paper is under peer review.", "vocabulary", 22),
            ("English of journalism", "إنجليزية الصحافة", 3,
             "lead, byline, op-ed, scoop",
             "المقدمة، التوقيع، مقال رأي، السبق",
             "She wrote an op-ed on the policy.", "vocabulary", 22),
            ("English of diplomacy", "إنجليزية الدبلوماسية", 3,
             "communiqué, demarche, accord",
             "بيان، خطوة دبلوماسية، اتفاق",
             "Diplomats issued a joint communiqué.", "vocabulary", 22),
            ("English of marketing", "إنجليزية التسويق", 3,
             "engagement, conversion, funnel",
             "المشاركة، التحويل، القمع التسويقي",
             "Our engagement rate doubled.", "vocabulary", 22),

            ("Rhetorical questions", "الأسئلة البلاغية", 4,
             "asked for effect, not answer",
             "تُطرح للتأثير لا للإجابة",
             "Isn't it time we acted?", "speaking", 22),
            ("Tricolon and parallelism", "الثلاثيات والتوازي", 4,
             "I came, I saw, I conquered.",
             "أتيت، رأيت، انتصرت",
             "Of the people, by the people, for the people.", "speaking", 25),
            ("Anaphora — repetition for effect", "تكرار البدء", 4,
             "repeating opening words", "تكرار الكلمات الافتتاحية",
             "We shall fight on the beaches, we shall fight …", "speaking", 25),
            ("Antithesis", "المقابلة", 4,
             "balanced opposites", "أضداد متوازنة",
             "Not for me, but for them.", "writing", 22),
            ("Ethos, pathos, logos", "أركان البلاغة الثلاثة", 4,
             "credibility, emotion, logic",
             "المصداقية، العاطفة، المنطق",
             "Effective arguments balance all three.", "writing", 28),
            ("Speech writing", "كتابة الخطب", 4,
             "—", "—", "—", "writing", 35),

            ("Cultural references in English", "المرجعيات الثقافية", 5,
             "Shakespeare, the Bible, Greek myths",
             "شكسبير، الإنجيل، الأساطير الإغريقية",
             "It's his Achilles' heel.", "reading", 28),
            ("Pop culture allusions", "تلميحات الثقافة الشعبية", 5,
             "movies, music, brands",
             "أفلام، موسيقى، علامات",
             "He pulled a Houdini and disappeared.", "reading", 25),
            ("Historical idioms", "تعابير تاريخية", 5,
             "cross the Rubicon, meet your Waterloo",
             "تعبر الروبيكون، تواجه ووترلوك",
             "We've crossed the Rubicon now.", "vocabulary", 25),
            ("Regional variations", "الفروق الإقليمية", 5,
             "US vs UK vs AUS vocabulary",
             "الأمريكية مقابل البريطانية والأسترالية",
             "Sidewalk (US) = pavement (UK) = footpath (AUS).", "vocabulary", 22),
            ("Slang and generational language", "العامية ولغة الأجيال", 5,
             "cap, slay, lit, mid",
             "كذب، رائع، مذهل، متوسط",
             "That's lit! / No cap.", "vocabulary", 22),
            ("Crossing cultures gracefully", "العبور الثقافي بأناقة", 5,
             "cultural sensitivity in language",
             "الحساسية الثقافية في اللغة",
             "Choose words that travel well.", "speaking", 28),

            ("Sustained discourse", "الخطاب الممتد", 6,
             "10+ minute monologue with structure",
             "حديث مهيكل لأكثر من 10 دقائق",
             "Today, I'll cover three points …", "speaking", 35),
            ("Debate at C2 level", "المناظرة على مستوى C2", 6,
             "nuanced positions, multiple sides",
             "مواقف دقيقة، جوانب متعددة",
             "While some might argue X, in fact …", "speaking", 35),
            ("Writing at native level", "الكتابة بمستوى أهل اللغة", 6,
             "rhythm, variety, precision",
             "إيقاع، تنوع، دقة",
             "Vary sentence length for rhythm.", "writing", 35),
            ("Editing your own writing", "تحرير كتاباتك", 6,
             "cut, clarify, sharpen", "احذف، وضّح، اشحذ",
             "Cut every word that doesn't earn its place.", "writing", 30),
            ("Translation as a skill", "الترجمة كمهارة", 6,
             "meaning > literal, register matching",
             "المعنى > الحرفي، مطابقة المسجل",
             "Translate the meaning, not the words.", "writing", 30),
            ("Lifelong learning of English", "التعلم مدى الحياة", 6,
             "habits, sources, community",
             "العادات، المصادر، المجتمع",
             "Read 30 minutes a day; talk to natives weekly.", "speaking", 25),
            # +9 gap-fill (to reach 48)
            ("Pun and wordplay", "التورية والتلاعب اللفظي", 1,
             "double meaning for humor",
             "المعنى المزدوج للفكاهة",
             "Time flies like an arrow; fruit flies like a banana.", "reading", 22),
            ("Sound devices — alliteration", "الجناس", 1,
             "repeating consonant sounds",
             "تكرار الأصوات الساكنة",
             "Peter Piper picked a peck of pickled peppers.", "reading", 22),
            ("Translating poetry", "ترجمة الشعر", 1,
             "image > form, music > meaning",
             "الصورة > الشكل، الموسيقى > المعنى",
             "Translate the heartbeat, not just the words.", "writing", 30),
            ("Sociolinguistic register shifts", "تحولات المسجل الاجتماعي", 2,
             "code-switching across contexts",
             "تبديل الأسلوب عبر السياقات",
             "Same speaker, three voices: home, work, formal.", "speaking", 28),
            ("Specialized lexis — AI", "مفردات متخصصة — الذكاء الاصطناعي", 3,
             "model, inference, fine-tuning, hallucination",
             "النموذج، الاستدلال، الضبط، الهلوسة",
             "Fine-tuning improves task-specific accuracy.", "vocabulary", 25),
            ("Specialized lexis — climate", "مفردات متخصصة — المناخ", 3,
             "carbon footprint, mitigation, adaptation",
             "البصمة الكربونية، التخفيف، التكيف",
             "Climate adaptation will become essential.", "vocabulary", 25),
            ("Anti-climax and bathos", "خيبة التوقع", 4,
             "deflating the build-up for effect",
             "إفراغ التصاعد للتأثير",
             "He aspired to greatness — and bought a coffee.", "writing", 25),
            ("Tone in opinion pieces", "النبرة في مقالات الرأي", 4,
             "outraged vs measured vs satirical",
             "غاضب مقابل متوازن مقابل ساخر",
             "Pick the tone that serves your argument.", "writing", 25),
            ("Self-editing checklist", "قائمة تحرير ذاتية", 6,
             "purpose check, structure check, line edit, proofread",
             "فحص الغرض، فحص البنية، تحرير السطر، تدقيق",
             "Cut → tighten → polish → proofread.", "writing", 30),
        ],
    },
]


# ---------------------------------------------------------------------------
# Sanity checks at import time
# ---------------------------------------------------------------------------

def _validate() -> None:
    """Soft validation — each level needs ≥ 36 topics (12 lessons per
    cluster minimum) and exactly 6 thematic clusters. We allow variance
    in topic count because some constructions naturally need more space
    (e.g. C1 conditionals) than others (e.g. A1 numbers)."""
    seen_codes = set()
    for level in LEVELS:
        assert level["code"] not in seen_codes, f"duplicate level {level['code']}"
        seen_codes.add(level["code"])
        topics = level["topics"]
        assert len(topics) == 48, (
            f"{level['code']} has {len(topics)} topics — expected 48"
        )
        clusters = level["clusters"]
        assert len(clusters) == 6, f"{level['code']} should have 6 clusters"
        for topic in topics:
            assert len(topic) == 8, (
                f"topic in {level['code']} has wrong arity: {topic}"
            )
            n_cluster = topic[2]
            assert 1 <= n_cluster <= 6, (
                f"{level['code']} cluster {n_cluster} out of range"
            )

_validate()
