"""Data and content templates for the Onlenco Beginner 48-unit seed.

This module is the single source of truth for the **text** of the Beginner
course. The management command `seed_onlenco_beginner_48_units` reads from
here and persists the rows. We keep data and templates inline (no JSON, no
YAML) so a Django dev can grep one file and see exactly what ships.

Every piece of copy here is **original to Onlenco**. The methodology is
inspired by published A1 syllabi (Cambridge / EFE / Cutting Edge) — see
`Docs/onlenco_beginner_48_prompts_pack/ONLENCO_BEGINNER_METHOD_SPEC.md`
section 7 — but no example sentence, character name, illustration prompt,
or audio script reuses text from any specific source publication.

Pronouns and characters: the 10 Onlenco students (Amani, Yusuf, Noor,
Kareem, Salma, Omar, Layla, Tarek, Hala, Rashid) — see §11 of the method
spec.
"""
from __future__ import annotations

from html import escape


# ---------------------------------------------------------------------------
# Per-unit dictionaries. The keys map directly to the seed templates below.
# Keep entries compact — the content builder fills in the verbose HTML and
# audio scripts from these short cues.
# ---------------------------------------------------------------------------

UNITS: list[dict] = [
    # ===== Cluster 1 — Identity & relationships =====
    {
        "n": 1, "review_group": "R1",
        "title_en": "Introducing Yourself", "title_ar": "التعريف بنفسك",
        "cefr": "A0", "minutes": 25, "lesson_type": "speaking",
        "new_language_en": '"to be" with names — "I am ..." / "My name is ..."',
        "new_language_ar": "فعل to be مع الأسماء — \"I am ...\" أو \"My name is ...\".",
        "vocabulary_en": "Greetings (Hello, Hi); the English alphabet A–Z.",
        "vocabulary_ar": "تحيات (Hello، Hi)؛ الأبجدية الإنجليزية A–Z.",
        "skill_en": "Greet someone and state your own name in English.",
        "skill_ar": "تحيّ شخصًا وقل اسمك بالإنجليزية.",
        "grammar_en": '1st-person singular of "to be": I am.',
        "grammar_ar": "صيغة المتكلم المفرد لـ to be: I am.",
        "pronunciation_en": 'Contraction /aɪm/ for "I\'m".',
        "pronunciation_ar": "النطق المختصر /aɪm/ للكلمة \"I'm\".",
        "image_idea": "Two friendly characters (Amani and Yusuf) waving at each other on a sunny school courtyard, flat Onlenco illustration on a soft green background, no text in image.",
        "speaking_goal_en": "Record a 15-second self-introduction using a greeting and your name.",
        "speaking_goal_ar": "سجّل تعريفًا قصيرًا بنفسك (15 ثانية) باستخدام تحية واسمك.",
        "listening_goal_en": "Identify 3 names that are spelled aloud, letter by letter.",
        "listening_goal_ar": "حدّد 3 أسماء يتم تهجئتها حرفًا حرفًا.",
        "quiz_goal_en": "8 mixed items: match greetings, fill am/is gaps, spell-from-audio.",
        "ai_tutor_goal_en": "2-min drill — the tutor asks the student's name three times, varying greetings.",
        "ai_tutor_goal_ar": "تدريب لدقيقتين — يطلب المعلم الذكي اسم الطالب 3 مرات بتحيات مختلفة.",
        "examples": [
            ("Hello! I'm Amani.", "مرحبًا! أنا أماني."),
            ("Hi! My name is Yusuf.", "أهلًا! اسمي يوسف."),
            ("My name is Hala.", "اسمي هالة."),
            ("I am Rashid.", "أنا راشد."),
        ],
        "dialogue": [
            ("Amani", "Hi! I'm Amani."),
            ("Yusuf", "Hello! My name is Yusuf."),
            ("Amani", "Nice to meet you, Yusuf."),
            ("Yusuf", "Nice to meet you too."),
        ],
        "checklist": [
            ("I can greet someone in English.", "أستطيع التحية بالإنجليزية."),
            ("I can say my own name.", "أستطيع قول اسمي."),
            ("I can spell my name aloud.", "أستطيع تهجئة اسمي بصوت."),
        ],
        "arabic_tip": "في الإنجليزية، \"I am\" تختصر دائمًا إلى \"I'm\" في الحديث الطبيعي. تدرّب على القولين.",
        "common_mistake_ar": "بعض المبتدئين يقولون \"My name Amani\" بدون \"is\". الصواب: \"My name is Amani.\"",
    },
    {
        "n": 2, "review_group": "R1",
        "title_en": "Countries", "title_ar": "البلدان",
        "cefr": "A0", "minutes": 15, "lesson_type": "vocabulary",
        "new_language_en": "(vocabulary unit — no new construction)",
        "new_language_ar": "(وحدة مفردات — لا قاعدة جديدة)",
        "vocabulary_en": "16 countries: USA, UK, Canada, Mexico, Brazil, Egypt, Sudan, Morocco, Tunisia, Saudi Arabia, UAE, Jordan, Lebanon, Turkey, India, China.",
        "vocabulary_ar": "16 دولة: الولايات المتحدة، المملكة المتحدة، كندا، المكسيك، البرازيل، مصر، السودان، المغرب، تونس، السعودية، الإمارات، الأردن، لبنان، تركيا، الهند، الصين.",
        "skill_en": "Name the country someone is from.",
        "skill_ar": "تسمية البلد الذي ينتمي إليه شخص ما.",
        "grammar_en": "—",
        "grammar_ar": "—",
        "pronunciation_en": "Stress in country names (e.g. MO-rocco, BRA-zil).",
        "pronunciation_ar": "تركيز النبرة في أسماء البلدان (مثال MO-rocco، BRA-zil).",
        "image_idea": "A 4×4 flat tile grid of country shapes; each tile carries the dominant hue of its country's flag, no flag details, no characters.",
        "speaking_goal_en": "Say 8 country names out loud, matching reference recordings.",
        "speaking_goal_ar": "انطق 8 من أسماء البلدان مطابقًا للتسجيل المرجعي.",
        "listening_goal_en": "Pick the country named from a 4-option grid.",
        "listening_goal_ar": "اختر اسم البلد المسموع من بين 4 خيارات.",
        "quiz_goal_en": "8 items: match flag-colour ↔ country, audio→name picker.",
        "ai_tutor_goal_en": "Quickfire 'Where is this place?' — student names the country shown.",
        "ai_tutor_goal_ar": "تدريب سريع: \"أين هذا المكان؟\" — يسمّي الطالب البلد المعروض.",
        "examples": [
            ("This is Sudan.", "هذه السودان."),
            ("This is Egypt.", "هذه مصر."),
            ("This is Canada.", "هذه كندا."),
            ("This is Brazil.", "هذه البرازيل."),
        ],
        "dialogue": [
            ("Noor", "Where is this?"),
            ("Kareem", "It's Jordan."),
            ("Noor", "And this one?"),
            ("Kareem", "It's Turkey."),
        ],
        "checklist": [
            ("I can name 10 countries in English.", "أستطيع تسمية 10 بلدان بالإنجليزية."),
            ("I recognise country names when I hear them.", "أتعرّف على أسماء البلدان عند سماعها."),
        ],
        "arabic_tip": "حاول استخدام الاسم الإنجليزي للبلد بدلًا من الترجمة عند تقديم نفسك.",
        "common_mistake_ar": "بعض البلدان لها اسم مختلف بالإنجليزية (مثل Egypt وليس Misr). تعلّم الاسم الإنجليزي.",
    },
    {
        "n": 3, "review_group": "R1",
        "title_en": "Talking About Yourself", "title_ar": "التحدّث عن نفسك",
        "cefr": "A0", "minutes": 25, "lesson_type": "speaking",
        "new_language_en": '"to be" + age and nationality — "I am 19. I am Sudanese."',
        "new_language_ar": "to be مع العمر والجنسية — \"I am 19. I am Sudanese.\"",
        "vocabulary_en": "Numbers 1–30; nationalities (Sudanese, Saudi, Egyptian, American, British, …).",
        "vocabulary_ar": "الأرقام 1–30؛ الجنسيات (سوداني، سعودي، مصري، أمريكي، بريطاني، …).",
        "skill_en": "Say your age and nationality.",
        "skill_ar": "قل عمرك وجنسيتك.",
        "grammar_en": "Adjective form of nationalities; \"to be\" + age pattern.",
        "grammar_ar": "صيغة الصفة للجنسيات؛ نمط to be + العمر.",
        "pronunciation_en": "Stress on nationality endings (-ESE, -AN, -ISH).",
        "pronunciation_ar": "النبرة على نهايات الجنسيات (-ESE، -AN، -ISH).",
        "image_idea": "Noor and Salma sitting at a small café table, each holding a sign with their age in numerals (no flags, signs are text-only).",
        "speaking_goal_en": "Record a 20-second self-introduction adding age and nationality on top of Unit 1.",
        "speaking_goal_ar": "سجّل تعريفًا بنفسك (20 ثانية) مضيفًا العمر والجنسية لما تعلمته في الوحدة 1.",
        "listening_goal_en": "Match each speaker to their age and country in a small table.",
        "listening_goal_ar": "اربط كل متحدث بعمره وبلده في جدول صغير.",
        "quiz_goal_en": "8 items: fill am/is, hear-and-pick nationality, recognise numbers 1–30.",
        "ai_tutor_goal_en": "Tutor asks 'How old are you?' and 'Where are you from?'; student answers; tutor confirms.",
        "ai_tutor_goal_ar": "يسأل المعلم \"How old are you?\" و \"Where are you from?\"، يجيب الطالب ثم يؤكد المعلم.",
        "examples": [
            ("I'm 19 years old.", "عمري 19 سنة."),
            ("She is Sudanese.", "هي سودانية."),
            ("Kareem is 25.", "كريم عمره 25."),
            ("I am American.", "أنا أمريكي."),
        ],
        "dialogue": [
            ("Salma", "How old are you?"),
            ("Noor", "I'm 17. And you?"),
            ("Salma", "I'm 30. Where are you from?"),
            ("Noor", "I'm from Egypt."),
        ],
        "checklist": [
            ("I can say my age.", "أستطيع قول عمري."),
            ("I can say my nationality.", "أستطيع قول جنسيتي."),
            ("I understand numbers 1–30.", "أفهم الأرقام من 1 إلى 30."),
        ],
        "arabic_tip": "لا تستخدم \"have\" مع العمر بالإنجليزية. قل \"I am 19\" وليس \"I have 19 years\".",
        "common_mistake_ar": "الجنسية ليست نفس البلد — \"Sudan\" بلد، و \"Sudanese\" جنسية.",
    },
    {
        "n": 4, "review_group": "R1",
        "title_en": "Family and Pets", "title_ar": "العائلة والحيوانات الأليفة",
        "cefr": "A0", "minutes": 18, "lesson_type": "vocabulary",
        "new_language_en": "(vocabulary unit)",
        "new_language_ar": "(وحدة مفردات)",
        "vocabulary_en": "Family (mother, father, brother, sister, son, daughter, grandparents, aunt, uncle, cousin); 10 pets (cat, dog, fish, parrot, rabbit, hamster, turtle, sheep, chicken, horse).",
        "vocabulary_ar": "العائلة (أم، أب، أخ، أخت، ابن، ابنة، الجدّان، خالة/عمة، خال/عم، ابن العم/الخال)؛ 10 حيوانات أليفة (قطة، كلب، سمكة، ببغاء، أرنب، هامستر، سلحفاة، خروف، دجاجة، حصان).",
        "skill_en": "Name family members and pets.",
        "skill_ar": "تسمية أفراد العائلة والحيوانات الأليفة.",
        "grammar_en": "—",
        "grammar_ar": "—",
        "pronunciation_en": "Schwa in -er and -her endings (mother, father, brother).",
        "pronunciation_ar": "صوت الشوا في نهايات -er و-her (mother، father، brother).",
        "image_idea": "A relationship tree of Hala's family on the left + a horizontal row of pet pictograms on the right, no DK trade dress.",
        "speaking_goal_en": "Record yourself naming 6 family members from prompted images.",
        "speaking_goal_ar": "سجّل تسمية 6 من أفراد العائلة من صور مقترحة.",
        "listening_goal_en": "Drag heard words into 'family' vs 'pet' buckets.",
        "listening_goal_ar": "اسحب الكلمات المسموعة إلى \"عائلة\" أو \"حيوان أليف\".",
        "quiz_goal_en": "8 items: image→word, audio→word, sort into family vs pet.",
        "ai_tutor_goal_en": "Tutor names a family member; student replies with a full sentence (\"My brother is …\").",
        "ai_tutor_goal_ar": "يسمّي المعلم فردًا من العائلة، فيرد الطالب بجملة كاملة (\"My brother is …\").",
        "examples": [
            ("She is my sister.", "هي أختي."),
            ("This is my dog.", "هذا كلبي."),
            ("They are my parents.", "هما والداي."),
            ("That is my cat.", "تلك قطتي."),
        ],
        "dialogue": [
            ("Tarek", "Who is this?"),
            ("Layla", "She's my mother."),
            ("Tarek", "And the cat?"),
            ("Layla", "That's my cat, Misha."),
        ],
        "checklist": [
            ("I can name family members in English.", "أستطيع تسمية أفراد العائلة."),
            ("I can name common pets.", "أستطيع تسمية الحيوانات الأليفة الشائعة."),
        ],
        "arabic_tip": "بالإنجليزية، \"cousin\" تعني ابن/ابنة العم أو الخال أو الخالة أو العمة — كلمة واحدة لكل هؤلاء.",
        "common_mistake_ar": "لا تنطق صوت /h/ في \"hour\". لكن انطقه دائمًا في \"horse\" و\"hamster\".",
    },
    {
        "n": 5, "review_group": "R1",
        "title_en": "Things You Have", "title_ar": "الأشياء التي لديك",
        "cefr": "A0", "minutes": 30, "lesson_type": "grammar",
        "new_language_en": "Possessive adjectives (my, your, his, her, its, our, their); this / that.",
        "new_language_ar": "ضمائر الملكية (my، your، his، her، its، our، their)؛ this و that.",
        "vocabulary_en": "Personal items (phone, key, bag, book, pen, notebook, wallet, ID card).",
        "vocabulary_ar": "أشياء شخصية (هاتف، مفتاح، حقيبة، كتاب، قلم، دفتر، محفظة، بطاقة هوية).",
        "skill_en": "Talk about who things belong to.",
        "skill_ar": "تحدّث عمّن تعود إليه الأشياء.",
        "grammar_en": "Possessive adjective + noun; this/that before singular nouns.",
        "grammar_ar": "صفة ملكية + اسم؛ this/that قبل الأسماء المفردة.",
        "pronunciation_en": "Distinguish his /hɪz/ from he's /hiːz/.",
        "pronunciation_ar": "ميّز بين his /hɪz/ و he's /hiːz/.",
        "image_idea": "Kareem holding up a notebook and pointing at a phone on his desk; speech bubble shows 'This is my notebook.'",
        "speaking_goal_en": "Hold up 4 objects on camera and say 'This is my X.' for each.",
        "speaking_goal_ar": "ارفع 4 أشياء أمام الكاميرا وقل \"This is my X.\" لكل منها.",
        "listening_goal_en": "Match each heard sentence to the correct owner from a small line-up.",
        "listening_goal_ar": "اربط كل جملة مسموعة بالمالك الصحيح من بين عدة أشخاص.",
        "quiz_goal_en": "8 items: possessive picker, this/that picker, cross-out incorrect form.",
        "ai_tutor_goal_en": "Show-and-tell drill — tutor names objects; student replies with 'This is my …'",
        "ai_tutor_goal_ar": "تدريب \"اعرض واحكِ\" — يسمّي المعلم الأشياء، يرد الطالب \"This is my …\".",
        "examples": [
            ("This is my phone.", "هذا هاتفي."),
            ("That is her bag.", "تلك حقيبتها."),
            ("This is our classroom.", "هذا فصلنا."),
            ("That is their car.", "تلك سيارتهم."),
        ],
        "dialogue": [
            ("Omar", "Is this your pen?"),
            ("Hala", "Yes, it's my pen."),
            ("Omar", "And that book?"),
            ("Hala", "That's her book — Layla's."),
        ],
        "checklist": [
            ("I can use my, your, his, her.", "أستخدم my و your و his و her."),
            ("I can use this and that.", "أستخدم this و that."),
            ("I can name 6 personal items.", "أستطيع تسمية 6 أشياء شخصية."),
        ],
        "arabic_tip": "في الإنجليزية، الضمير يدل على المالك (his = ضمير المذكر، her = ضمير المؤنث) — حتى لو كان الشيء مذكرًا أو مؤنثًا نحويًا.",
        "common_mistake_ar": "لا تقل \"This my phone\" بدون \"is\". الصواب: \"This is my phone.\"",
    },
    {
        "n": 6, "review_group": "R1",
        "title_en": "Using Apostrophes", "title_ar": "استخدام علامة الملكية",
        "cefr": "A0", "minutes": 25, "lesson_type": "grammar",
        "new_language_en": "Possessive 's — 'Layla's book', 'my parents' house'.",
        "new_language_ar": "علامة الملكية 's — \"Layla's book\"، \"my parents' house\".",
        "vocabulary_en": "Re-uses family and pets from U4.",
        "vocabulary_ar": "يعيد استخدام مفردات العائلة والحيوانات من الوحدة 4.",
        "skill_en": "Show ownership with apostrophe-s.",
        "skill_ar": "إظهار الملكية باستخدام 's.",
        "grammar_en": "Singular 's vs plural-ending s' (after plural nouns).",
        "grammar_ar": "'s للمفرد مقابل s' بعد الجمع.",
        "pronunciation_en": "Voiced /z/ after vowels (Layla's) vs voiceless /s/ after voiceless consonants (Kareem's).",
        "pronunciation_ar": "صوت /z/ المجهور بعد الحروف الصوتية، و/s/ المهموس بعد الصامتة.",
        "image_idea": "Side-by-side panels — left: Layla holds her book; right: a small group of friends near a shared car (Layla's book vs their car).",
        "speaking_goal_en": "Say 5 ownership sentences chosen from a chart.",
        "speaking_goal_ar": "انطق 5 جمل ملكية مختارة من جدول.",
        "listening_goal_en": "Identify the owner in 6 spoken sentences.",
        "listening_goal_ar": "حدّد المالك في 6 جمل منطوقة.",
        "quiz_goal_en": "8 items: rewrite ownership, choose 's vs s'.",
        "ai_tutor_goal_en": "Quick possession Q&A: 'Whose phone is this?' → 'It's Omar's.'",
        "ai_tutor_goal_ar": "أسئلة وأجوبة ملكية سريعة: \"Whose phone is this?\" → \"It's Omar's.\"",
        "examples": [
            ("Layla's book is on the desk.", "كتاب ليلى على الطاولة."),
            ("This is Omar's phone.", "هذا هاتف عمر."),
            ("My parents' house is small.", "بيت والديّ صغير."),
            ("Kareem's car is new.", "سيارة كريم جديدة."),
        ],
        "dialogue": [
            ("Rashid", "Whose bag is this?"),
            ("Amani", "It's Hala's bag."),
            ("Rashid", "And these books?"),
            ("Amani", "They're the students' books."),
        ],
        "checklist": [
            ("I can use 's for one owner.", "أستخدم 's لمالك واحد."),
            ("I can use s' for plural owners.", "أستخدم s' لعدّة مالكين."),
        ],
        "arabic_tip": "علامة الـ apostrophe (') مهمة جدًا — \"Omars\" (بدون apostrophe) تعني جمع، و \"Omar's\" تعني مِلك عمر.",
        "common_mistake_ar": "لا تكتب \"its\" بـ apostrophe إلا إذا كنت تقصد \"it is\". مِلك \"it\" يُكتب \"its\".",
    },
    {
        "n": 7, "review_group": "R1",
        "title_en": "Everyday Things", "title_ar": "أشياء يومية",
        "cefr": "A0", "minutes": 15, "lesson_type": "vocabulary",
        "new_language_en": "(vocabulary unit)",
        "new_language_ar": "(وحدة مفردات)",
        "vocabulary_en": "16 daily objects: laptop, charger, glasses, umbrella, keys, water bottle, lunchbox, headphones, watch, scarf, wallet, sunglasses, tissues, mask, ID, sneakers.",
        "vocabulary_ar": "16 شيئًا يوميًا: لابتوب، شاحن، نظارات، مظلة، مفاتيح، قارورة ماء، صندوق غداء، سماعات، ساعة، وشاح، محفظة، نظارات شمسية، مناديل، كمامة، بطاقة هوية، حذاء رياضي.",
        "skill_en": "Name objects you carry every day.",
        "skill_ar": "تسمية الأشياء التي تحملها يوميًا.",
        "grammar_en": "—", "grammar_ar": "—",
        "pronunciation_en": "Stress in compound nouns (WAter bottle, HEADphones).",
        "pronunciation_ar": "النبرة في الأسماء المركبة (WAter bottle، HEADphones).",
        "image_idea": "Flat illustration grid of 16 everyday items on a soft neutral background, no people.",
        "speaking_goal_en": "Tour your bag on camera, naming 5 items in 30 seconds.",
        "speaking_goal_ar": "اجعل جولة سريعة في حقيبتك أمام الكاميرا، وسمِّ 5 أشياء في 30 ثانية.",
        "listening_goal_en": "Mark which items the speaker says they have.",
        "listening_goal_ar": "ضع علامة على الأشياء التي يقول المتحدث إنها معه.",
        "quiz_goal_en": "8 items: image→word, word→image, hear→name.",
        "ai_tutor_goal_en": "Listing drill — 'Tell me 5 things in your bag.'",
        "ai_tutor_goal_ar": "تدريب على القوائم — \"اذكر 5 أشياء في حقيبتك.\"",
        "examples": [
            ("I have my laptop.", "معي لابتوبي."),
            ("She has a water bottle.", "معها قارورة ماء."),
            ("These are my keys.", "هذه مفاتيحي."),
            ("That is his charger.", "هذا شاحنه."),
        ],
        "dialogue": [
            ("Yusuf", "What's in your bag?"),
            ("Salma", "My laptop, headphones, and a charger."),
            ("Yusuf", "Do you have your ID?"),
            ("Salma", "Yes, it's in my wallet."),
        ],
        "checklist": [
            ("I can name 10 everyday objects.", "أستطيع تسمية 10 أشياء يومية."),
        ],
        "arabic_tip": "كثير من الكلمات اليومية مركبة — \"water bottle\" كلمتان لكنها فكرة واحدة.",
        "common_mistake_ar": "\"keys\" دائمًا بالجمع لأن الناس يحملون أكثر من مفتاح عادةً.",
    },
    {
        "n": 8, "review_group": "R1",
        "title_en": "Talking About Your Things", "title_ar": "التحدث عن أشيائك",
        "cefr": "A0", "minutes": 25, "lesson_type": "grammar",
        "new_language_en": "these / those (plurals of this/that); determiners → possessive pronouns (my → mine, your → yours, …).",
        "new_language_ar": "these و those (جمع this و that)؛ ضمائر الملكية (my → mine، your → yours، …).",
        "vocabulary_en": "Re-uses everyday-things from U7.",
        "vocabulary_ar": "يعيد استخدام مفردات الأشياء اليومية من الوحدة 7.",
        "skill_en": "Talk about who plural things belong to.",
        "skill_ar": "تحدّث عمّن تعود إليه الأشياء بالجمع.",
        "grammar_en": "Plural demonstratives; 'These books are mine.' pattern.",
        "grammar_ar": "الإشارات للجمع؛ نمط \"These books are mine.\"",
        "pronunciation_en": "Voiced /ð/ in these/those — soft tongue tap.",
        "pronunciation_ar": "الـ /ð/ المجهورة في these/those — لمسة لسان لطيفة.",
        "image_idea": "Two adjacent desks — Tarek's covered in books, Hala's with chargers and headphones — labelled with 'these'/'those' arrows.",
        "speaking_goal_en": "Build 12 correct sentences from a slot chart and say them out loud.",
        "speaking_goal_ar": "ابنِ 12 جملة صحيحة من جدول وقلها بصوت.",
        "listening_goal_en": "Sort heard nouns into two characters' bags (Tarek's vs Hala's).",
        "listening_goal_ar": "صنّف الكلمات المسموعة إلى حقيبتي تارق وهالة.",
        "quiz_goal_en": "8 items: sentence-builder, mine vs my picker, listen-and-group.",
        "ai_tutor_goal_en": "Practice swapping 'my X' → 'X is mine.' across 8 prompts.",
        "ai_tutor_goal_ar": "تدريب على تحويل \"my X\" → \"X is mine.\" لـ 8 محفّزات.",
        "examples": [
            ("These are my books.", "هذه كتبي."),
            ("Those books are mine.", "تلك الكتب لي."),
            ("These are his sneakers.", "هذه أحذيته الرياضية."),
            ("Those headphones are yours.", "تلك السماعات لك."),
        ],
        "dialogue": [
            ("Tarek", "Are these books yours?"),
            ("Hala", "No, they're not mine. They're Layla's."),
            ("Tarek", "And those headphones?"),
            ("Hala", "Those are mine."),
        ],
        "checklist": [
            ("I can use these and those.", "أستخدم these و those."),
            ("I can use mine, yours, his, hers.", "أستخدم mine و yours و his و hers."),
            ("I can talk about who things belong to.", "أستطيع التحدث عن مَن يملك الأشياء."),
        ],
        "arabic_tip": "لاحظ الفرق: \"my book\" (صفة ملكية + اسم)، و\"the book is mine\" (ضمير ملكية وحده).",
        "common_mistake_ar": "بعد ضمير الملكية (mine، yours، hers…) لا نضع اسمًا. لا تقل \"mine book\" — قل \"my book\" أو \"the book is mine\".",
    },
    # ===== Cluster 2 — Daily life & routines =====
    {
        "n": 9, "review_group": "R2",
        "title_en": "Jobs", "title_ar": "المهن",
        "cefr": "A0", "minutes": 18, "lesson_type": "vocabulary",
        "new_language_en": "(vocabulary unit)",
        "new_language_ar": "(وحدة مفردات)",
        "vocabulary_en": "16 jobs: doctor, nurse, dentist, teacher, engineer, chef, driver, farmer, police officer, fire fighter, actor, artist, hairdresser, vet, sales assistant, construction worker.",
        "vocabulary_ar": "16 مهنة: طبيب، ممرّض، طبيب أسنان، معلّم، مهندس، طاهٍ، سائق، مزارع، شرطي، رجل إطفاء، ممثل، فنان، حلّاق، طبيب بيطري، بائع، عامل بناء.",
        "skill_en": "Name common jobs.",
        "skill_ar": "تسمية المهن الشائعة.",
        "grammar_en": "—", "grammar_ar": "—",
        "pronunciation_en": "-er ending (teacher, farmer, driver) — schwa.",
        "pronunciation_ar": "نهاية -er (teacher، farmer، driver) — صوت الشوا.",
        "image_idea": "16-tile grid of stylised silhouettes per job, neutral background, no faces.",
        "speaking_goal_en": "Record yourself naming 6 jobs from prompted images.",
        "speaking_goal_ar": "سجّل نفسك تسمّي 6 مهن من صور مقترحة.",
        "listening_goal_en": "Pick the job heard from a 4-image grid.",
        "listening_goal_ar": "اختر المهنة المسموعة من شبكة 4 صور.",
        "quiz_goal_en": "8 items: image→job, audio→job, job→workplace match.",
        "ai_tutor_goal_en": "'What is this person's job?' drill across 10 images.",
        "ai_tutor_goal_ar": "تدريب \"ما مهنة هذا الشخص؟\" عبر 10 صور.",
        "examples": [
            ("She is a doctor.", "هي طبيبة."),
            ("He is a teacher.", "هو معلّم."),
            ("Tarek is a chef.", "تارق طاهٍ."),
            ("Salma is a pharmacist.", "سلمى صيدلانية."),
        ],
        "dialogue": [
            ("Amani", "What does Omar do?"),
            ("Layla", "He's a software developer."),
            ("Amani", "And Kareem?"),
            ("Layla", "He's an architect."),
        ],
        "checklist": [
            ("I can name 10 jobs in English.", "أستطيع تسمية 10 مهن بالإنجليزية."),
        ],
        "arabic_tip": "بعض المهن لا تتغير حسب الجنس بالإنجليزية — \"doctor\" تستخدم للذكر والأنثى.",
        "common_mistake_ar": "نقول \"He is a doctor\" مع \"a\" قبل المهنة. لا تنسَ \"a\".",
    },
    {
        "n": 10, "review_group": "R2",
        "title_en": "Talking About Your Job", "title_ar": "التحدّث عن مهنتك",
        "cefr": "A0", "minutes": 30, "lesson_type": "speaking",
        "new_language_en": "'I am / He is' + a job — 'I am a police officer.'",
        "new_language_ar": "\"I am / He is\" + المهنة — \"I am a police officer.\"",
        "vocabulary_en": "8 workplaces (school, hospital, office, restaurant, farm, construction site, store, laboratory); inside vs outside.",
        "vocabulary_ar": "8 أماكن عمل (مدرسة، مستشفى، مكتب، مطعم، مزرعة، موقع بناء، متجر، مختبر)؛ inside و outside.",
        "skill_en": "Describe your job and where you work.",
        "skill_ar": "صف مهنتك ومكان عملك.",
        "grammar_en": "Article a/an before a job.",
        "grammar_ar": "أداة a/an قبل المهنة.",
        "pronunciation_en": "a /ə/ (schwa) before a job.",
        "pronunciation_ar": "a /ə/ (شوا) قبل المهنة.",
        "image_idea": "Yusuf in a small tech office at his desk, name tag visible, soft greens.",
        "speaking_goal_en": "Record 'I am a/an X. I work in/at Y.' using your real or future job.",
        "speaking_goal_ar": "سجّل \"I am a/an X. I work in/at Y.\" باستخدام مهنتك الحالية أو المستقبلية.",
        "listening_goal_en": "Match each speaker to their workplace.",
        "listening_goal_ar": "اربط كل متحدث بمكان عمله.",
        "quiz_goal_en": "8 items: a vs an, job-from-audio, fill-gaps with 'to be'.",
        "ai_tutor_goal_en": "'What do you do? / Where do you work?' mini-dialogue.",
        "ai_tutor_goal_ar": "حوار قصير: \"What do you do?\" / \"Where do you work?\".",
        "examples": [
            ("I am a teacher.", "أنا معلّم."),
            ("She is an engineer.", "هي مهندسة."),
            ("He works at a hospital.", "هو يعمل في مستشفى."),
            ("They work in an office.", "هم يعملون في مكتب."),
        ],
        "dialogue": [
            ("Rashid", "What do you do, Amani?"),
            ("Amani", "I'm a student. I want to be a doctor."),
            ("Rashid", "Where do you study?"),
            ("Amani", "At the university in Khartoum."),
        ],
        "checklist": [
            ("I can say what my job is.", "أستطيع قول مهنتي."),
            ("I can say where I work.", "أستطيع قول مكان عملي."),
        ],
        "arabic_tip": "نستخدم \"an\" (وليس \"a\") قبل الكلمات التي تبدأ بصوت متحرك — \"an engineer\"، \"an artist\".",
        "common_mistake_ar": "\"work in\" مع المباني (in a hospital)، \"work at\" مع المنظمات أو الأماكن المحددة (at Google، at the bank).",
    },
    {
        "n": 11, "review_group": "R2",
        "title_en": "Telling the Time", "title_ar": "قول الوقت",
        "cefr": "A0", "minutes": 25, "lesson_type": "speaking",
        "new_language_en": "Time expressions — 'It's 3 o'clock', 'half past 7', 'quarter to 9'; am/pm.",
        "new_language_ar": "تعبيرات الوقت — \"It's 3 o'clock\"، \"half past 7\"، \"quarter to 9\"؛ am/pm.",
        "vocabulary_en": "Hours 1–12; o'clock, half, quarter, past, to.",
        "vocabulary_ar": "الساعات 1–12؛ o'clock، half، quarter، past، to.",
        "skill_en": "Ask and tell the time in English.",
        "skill_ar": "اسأل وأخبر عن الوقت بالإنجليزية.",
        "grammar_en": "'It's' + time.",
        "grammar_ar": "\"It's\" + الوقت.",
        "pronunciation_en": "Reduction of o'clock → /əˈklɑk/.",
        "pronunciation_ar": "اختزال o'clock → /əˈklɑk/.",
        "image_idea": "A row of stylised analogue clocks set to varied times against a soft background.",
        "speaking_goal_en": "Read 6 clock faces shown in the lesson.",
        "speaking_goal_ar": "اقرأ 6 ساعات معروضة في الدرس.",
        "listening_goal_en": "Drag time labels onto matching clock faces.",
        "listening_goal_ar": "اسحب بطاقات الوقت إلى ساعاتها المطابقة.",
        "quiz_goal_en": "8 items: clock→words, words→clock, am/pm.",
        "ai_tutor_goal_en": "'What time is it?' asked 5 times with varied clocks.",
        "ai_tutor_goal_ar": "\"What time is it?\" تُسأل 5 مرات لساعات مختلفة.",
        "examples": [
            ("It's 3 o'clock.", "الساعة الثالثة تمامًا."),
            ("It's half past 7.", "الساعة السابعة والنصف."),
            ("It's quarter to 9.", "الساعة التاسعة إلا الربع."),
            ("It's 6:15 am.", "الساعة 6:15 صباحًا."),
        ],
        "dialogue": [
            ("Hala", "What time is it?"),
            ("Omar", "It's quarter past 4."),
            ("Hala", "When does the bus come?"),
            ("Omar", "At half past 4."),
        ],
        "checklist": [
            ("I can read times on a clock.", "أستطيع قراءة الوقت على الساعة."),
            ("I can ask 'What time is it?'.", "أستطيع السؤال عن الوقت."),
        ],
        "arabic_tip": "بالعربية نقول \"الساعة السابعة والنصف\"، وبالإنجليزية \"half past seven\" — لاحظ ترتيب الكلمات.",
        "common_mistake_ar": "\"It's\" ضرورية قبل الوقت. لا تقل \"3 o'clock\" وحدها — قل \"It's 3 o'clock.\"",
    },
    {
        "n": 12, "review_group": "R2",
        "title_en": "Daily Routines", "title_ar": "الروتين اليومي",
        "cefr": "A0", "minutes": 18, "lesson_type": "vocabulary",
        "new_language_en": "(vocabulary unit)",
        "new_language_ar": "(وحدة مفردات)",
        "vocabulary_en": "12 routine verbs: wake up, get up, take a shower, have breakfast, go to work, start work, finish work, come home, have dinner, watch TV, study, go to bed.",
        "vocabulary_ar": "12 فعلًا روتينيًا: يستيقظ، ينهض، يستحم، يفطر، يذهب للعمل، يبدأ العمل، ينهي العمل، يعود للمنزل، يتعشى، يشاهد التلفاز، يدرس، ينام.",
        "skill_en": "Name daily activities.",
        "skill_ar": "تسمية الأنشطة اليومية.",
        "grammar_en": "—", "grammar_ar": "—",
        "pronunciation_en": "Phrasal verb stress (WAKE up, GO to bed).",
        "pronunciation_ar": "النبرة على الفعل في الأفعال المركبة (WAKE up، GO to bed).",
        "image_idea": "Strip of 12 icons of a person doing each action, ordered by time of day.",
        "speaking_goal_en": "Say 8 routine actions out loud.",
        "speaking_goal_ar": "انطق 8 أفعال روتينية بصوت.",
        "listening_goal_en": "Order heard activities along a timeline.",
        "listening_goal_ar": "رتّب الأنشطة المسموعة على خط زمني.",
        "quiz_goal_en": "8 items: image→verb, audio→verb, order by time of day.",
        "ai_tutor_goal_en": "'What do you do in the morning?' listing drill.",
        "ai_tutor_goal_ar": "تدريب على القوائم: \"ماذا تفعل في الصباح؟\".",
        "examples": [
            ("I wake up at 6.", "أستيقظ الساعة 6."),
            ("She takes a shower.", "هي تستحم."),
            ("They have breakfast at 7.", "هم يفطرون الساعة 7."),
            ("He goes to bed at 11.", "هو ينام الساعة 11."),
        ],
        "dialogue": [
            ("Noor", "When do you wake up?"),
            ("Yusuf", "At 6 o'clock."),
            ("Noor", "And when do you go to bed?"),
            ("Yusuf", "Usually at 11."),
        ],
        "checklist": [
            ("I can name 8 daily routines.", "أستطيع تسمية 8 من أنشطة الروتين اليومي."),
        ],
        "arabic_tip": "بالإنجليزية، \"have breakfast/lunch/dinner\" — لاحظ استخدام فعل \"have\" مع الوجبات.",
        "common_mistake_ar": "لا تقل \"I take breakfast\" — قل \"I have breakfast\".",
    },
    {
        "n": 13, "review_group": "R2",
        "title_en": "Describing Your Day", "title_ar": "وصف يومك",
        "cefr": "A1", "minutes": 35, "lesson_type": "grammar",
        "new_language_en": "Present simple — 'I wake up at 7. He starts work at 9.'",
        "new_language_ar": "المضارع البسيط — \"I wake up at 7. He starts work at 9.\"",
        "vocabulary_en": "Re-uses routine verbs from U12.",
        "vocabulary_ar": "يعيد استخدام أفعال الروتين من الوحدة 12.",
        "skill_en": "Talk about your daily routine.",
        "skill_ar": "تحدّث عن روتينك اليومي.",
        "grammar_en": "3rd-person -s (she works, he watches).",
        "grammar_ar": "إضافة -s مع الضمير الثالث المفرد (she works, he watches).",
        "pronunciation_en": "-s endings: /s/, /z/, /ɪz/ rules.",
        "pronunciation_ar": "نهايات -s: قواعد /s/ و/z/ و/ɪz/.",
        "image_idea": "Vertical timeline showing Rashid's day from morning to night, one icon per stage.",
        "speaking_goal_en": "Record a 30-second description of your typical day.",
        "speaking_goal_ar": "سجّل وصفًا (30 ثانية) ليومك المعتاد.",
        "listening_goal_en": "Fill 4 time-blanks in a transcript while listening.",
        "listening_goal_ar": "املأ 4 فراغات للوقت في النص أثناء الاستماع.",
        "quiz_goal_en": "8 items: fill-gaps with verb+s, time placement, hear→verb.",
        "ai_tutor_goal_en": "Tutor asks 3 'What time do you …?' and gives feedback.",
        "ai_tutor_goal_ar": "يطرح المعلم 3 أسئلة \"متى تفعل …؟\" ويعطي تغذية راجعة.",
        "examples": [
            ("I wake up at 7 am.", "أستيقظ الساعة 7 صباحًا."),
            ("She starts work at 9.", "هي تبدأ العمل الساعة 9."),
            ("He has dinner at 8 pm.", "هو يتعشى الساعة 8 مساءً."),
            ("They go to bed at 11.", "هم ينامون الساعة 11."),
        ],
        "dialogue": [
            ("Layla", "What does Kareem do every day?"),
            ("Tarek", "He wakes up at 6 and goes to work at 8."),
            ("Layla", "When does he come home?"),
            ("Tarek", "At 6 pm."),
        ],
        "checklist": [
            ("I can use the present simple.", "أستخدم المضارع البسيط."),
            ("I can talk about my daily routine.", "أستطيع التحدث عن روتيني اليومي."),
            ("I add -s with he and she.", "أضيف -s مع he و she."),
        ],
        "arabic_tip": "المضارع البسيط بالإنجليزية يصف الأشياء التي تحدث كل يوم — كأنه \"حقيقة عامة\" أو عادة.",
        "common_mistake_ar": "لا تنسَ إضافة -s مع he/she/it في المضارع البسيط. \"He works\" وليس \"He work\".",
    },
    {
        "n": 14, "review_group": "R2",
        "title_en": "Describing Your Week", "title_ar": "وصف أسبوعك",
        "cefr": "A1", "minutes": 28, "lesson_type": "grammar",
        "new_language_en": "Days + prepositions — 'on Monday', 'on weekdays', 'at the weekend'.",
        "new_language_ar": "الأيام + حروف الجر — \"on Monday\"، \"on weekdays\"، \"at the weekend\".",
        "vocabulary_en": "Days of the week; weekday vs weekend.",
        "vocabulary_ar": "أيام الأسبوع؛ يوم العمل مقابل عطلة نهاية الأسبوع.",
        "skill_en": "Talk about your weekly routine.",
        "skill_ar": "تحدّث عن روتينك الأسبوعي.",
        "grammar_en": "Preposition on with days.",
        "grammar_ar": "حرف الجر on مع الأيام.",
        "pronunciation_en": "Wednesday /ˈwɛnz.deɪ/ (silent d).",
        "pronunciation_ar": "Wednesday /ˈwɛnz.deɪ/ (الـ d لا تُنطق).",
        "image_idea": "A 7-cell calendar strip, each day's cell containing a tiny activity icon.",
        "speaking_goal_en": "Record 5 sentences about your week using 'on …'.",
        "speaking_goal_ar": "سجّل 5 جمل عن أسبوعك باستخدام \"on …\".",
        "listening_goal_en": "Mark which days a speaker is busy.",
        "listening_goal_ar": "ضع علامة على الأيام التي يكون فيها المتحدث مشغولًا.",
        "quiz_goal_en": "8 items: preposition picker, day spelling, weekly schedule build.",
        "ai_tutor_goal_en": "'What do you do on Saturday?' — Q&A loop across 4 days.",
        "ai_tutor_goal_ar": "\"ماذا تفعل يوم السبت؟\" — حلقة أسئلة وأجوبة عبر 4 أيام.",
        "examples": [
            ("On Monday, I study English.", "يوم الإثنين أدرس الإنجليزية."),
            ("She works on weekdays.", "هي تعمل في أيام الأسبوع."),
            ("They rest at the weekend.", "هم يستريحون في عطلة نهاية الأسبوع."),
            ("I see my family on Friday.", "أرى عائلتي يوم الجمعة."),
        ],
        "dialogue": [
            ("Salma", "What do you do on Sunday?"),
            ("Rashid", "I usually play soccer."),
            ("Salma", "And on Wednesday?"),
            ("Rashid", "I study English with my tutor."),
        ],
        "checklist": [
            ("I can name the 7 days.", "أستطيع تسمية الأيام السبعة."),
            ("I can use on with days.", "أستخدم on مع الأيام."),
        ],
        "arabic_tip": "بالإنجليزية، أيام الأسبوع تبدأ بحرف كبير: Monday، Tuesday، إلخ.",
        "common_mistake_ar": "نقول \"on Monday\" وليس \"in Monday\". \"in\" تُستخدم مع الأشهر والسنوات، و\"on\" مع الأيام والتواريخ.",
    },
    {
        "n": 15, "review_group": "R2",
        "title_en": "Negatives with To Be", "title_ar": "النفي مع to be",
        "cefr": "A1", "minutes": 22, "lesson_type": "grammar",
        "new_language_en": "'I am not', 'he is not', contractions (isn't, aren't).",
        "new_language_ar": "\"I am not\"، \"he is not\"، الاختصارات (isn't، aren't).",
        "vocabulary_en": "Re-uses jobs and nationalities.",
        "vocabulary_ar": "يعيد استخدام مفردات المهن والجنسيات.",
        "skill_en": "Say what things are not.",
        "skill_ar": "قل ما ليست الأشياء عليه.",
        "grammar_en": "Adding 'not' after 'to be'.",
        "grammar_ar": "إضافة \"not\" بعد \"to be\".",
        "pronunciation_en": "Contraction isn't /ˈɪz.ənt/.",
        "pronunciation_ar": "الاختصار isn't /ˈɪz.ənt/.",
        "image_idea": "Side-by-side panels: wrong assumption ('She is a chef') vs reality ('She is a doctor').",
        "speaking_goal_en": "Correct 5 false statements about classmates aloud.",
        "speaking_goal_ar": "صحّح 5 عبارات خاطئة عن زملائك بصوت.",
        "listening_goal_en": "Mark each statement true/false from short audio.",
        "listening_goal_ar": "ضع علامة صحيح/خطأ على كل عبارة من تسجيل قصير.",
        "quiz_goal_en": "8 items: make negative, full vs contraction, T/F from audio.",
        "ai_tutor_goal_en": "'Are you …?' questions where the student replies 'No, I am not.'",
        "ai_tutor_goal_ar": "أسئلة \"Are you …?\" يرد الطالب \"No, I am not.\"",
        "examples": [
            ("I am not a teacher.", "لست معلّمًا."),
            ("She isn't from Egypt.", "هي ليست من مصر."),
            ("They aren't at home.", "هم ليسوا في البيت."),
            ("He is not 30 years old.", "هو ليس بعمر 30 سنة."),
        ],
        "dialogue": [
            ("Kareem", "Is Yusuf a doctor?"),
            ("Amani", "No, he isn't. He's an engineer."),
            ("Kareem", "Is Salma from Sudan?"),
            ("Amani", "No, she isn't. She's from Morocco."),
        ],
        "checklist": [
            ("I can use 'not' with 'to be'.", "أستخدم not مع to be."),
            ("I can use contractions isn't, aren't.", "أستخدم isn't و aren't."),
        ],
        "arabic_tip": "الاختصار شائع جدًا في الحديث: \"isn't\" أكثر طبيعية من \"is not\" في المحادثة العادية.",
        "common_mistake_ar": "بعض المبتدئين يقولون \"I no am\" — هذا خطأ. الصحيح: \"I am not\" أو \"I'm not\".",
    },
    {
        "n": 16, "review_group": "R2",
        "title_en": "More Negatives", "title_ar": "المزيد من النفي",
        "cefr": "A1", "minutes": 28, "lesson_type": "grammar",
        "new_language_en": "Present simple negative — 'I do not work outside.', 'He does not live in Khartoum.'",
        "new_language_ar": "نفي المضارع البسيط — \"I do not work outside.\"، \"He does not live in Khartoum.\"",
        "vocabulary_en": "Re-uses routine and place vocab.",
        "vocabulary_ar": "يعيد استخدام مفردات الروتين والأماكن.",
        "skill_en": "Say what you don't do.",
        "skill_ar": "قل ما لا تفعله.",
        "grammar_en": "don't/doesn't + base form; 3rd-person rule reversed in negation.",
        "grammar_ar": "don't/doesn't + الفعل الأساسي؛ قاعدة الضمير الثالث تنعكس في النفي.",
        "pronunciation_en": "doesn't /ˈdʌz.ənt/.",
        "pronunciation_ar": "doesn't /ˈdʌz.ənt/.",
        "image_idea": "Single character doing an activity on the left; right panel crossed out — the activity they don't do.",
        "speaking_goal_en": "Record 4 sentences about things you don't do daily.",
        "speaking_goal_ar": "سجّل 4 جمل عن أشياء لا تفعلها يوميًا.",
        "listening_goal_en": "Mark whether the speaker does or doesn't do each item.",
        "listening_goal_ar": "ضع علامة على ما يفعله أو لا يفعله المتحدث.",
        "quiz_goal_en": "8 items: don't/doesn't fill-gaps, fix verb form, listen-and-group.",
        "ai_tutor_goal_en": "'Do you …?' questions leading to 'No, I don't.' answers.",
        "ai_tutor_goal_ar": "أسئلة \"Do you …?\" تؤدي إلى \"No, I don't.\"",
        "examples": [
            ("I don't work on Sundays.", "لا أعمل أيام الأحد."),
            ("She doesn't drink coffee.", "هي لا تشرب القهوة."),
            ("They don't live in Cairo.", "هم لا يعيشون في القاهرة."),
            ("He doesn't watch TV.", "هو لا يشاهد التلفاز."),
        ],
        "dialogue": [
            ("Hala", "Do you cook every day?"),
            ("Tarek", "No, I don't. I cook on weekends only."),
            ("Hala", "Does Salma drive?"),
            ("Tarek", "No, she doesn't."),
        ],
        "checklist": [
            ("I can say what I don't do.", "أستطيع قول ما لا أفعله."),
            ("I can use don't and doesn't.", "أستخدم don't و doesn't."),
        ],
        "arabic_tip": "في النفي للمضارع البسيط، \"-s\" تنتقل من الفعل إلى \"does\": \"He works\" → \"He doesn't work\" (لاحظ \"work\" بدون s).",
        "common_mistake_ar": "خطأ شائع: \"He doesn't works.\" الصحيح: \"He doesn't work.\" بعد doesn't نضع الفعل الأساسي بدون -s.",
    },
    {
        "n": 17, "review_group": "R2",
        "title_en": "Simple Questions", "title_ar": "الأسئلة البسيطة",
        "cefr": "A1", "minutes": 28, "lesson_type": "grammar",
        "new_language_en": "Yes/no questions — 'Are you a student?', 'Does he work outside?'",
        "new_language_ar": "أسئلة نعم/لا — \"Are you a student?\"، \"Does he work outside?\"",
        "vocabulary_en": "Re-uses jobs and routines.",
        "vocabulary_ar": "يعيد استخدام مفردات المهن والروتين.",
        "skill_en": "Ask simple yes/no questions.",
        "skill_ar": "اطرح أسئلة نعم/لا بسيطة.",
        "grammar_en": "Inversion with 'to be'; do/does + subject for present simple.",
        "grammar_ar": "قلب الترتيب مع to be؛ do/does + الفاعل في المضارع البسيط.",
        "pronunciation_en": "Rising intonation at end of yes/no questions.",
        "pronunciation_ar": "نبرة صاعدة في نهاية أسئلة نعم/لا.",
        "image_idea": "Two characters facing each other; one's speech bubble has a question mark glyph emphasised.",
        "speaking_goal_en": "Ask 5 yes/no questions about a partner's day.",
        "speaking_goal_ar": "اطرح 5 أسئلة نعم/لا عن يوم شخص آخر.",
        "listening_goal_en": "Distinguish question vs statement from intonation.",
        "listening_goal_ar": "ميّز بين السؤال والجملة الخبرية من النبرة.",
        "quiz_goal_en": "8 items: turn statement → question, pick correct auxiliary, intonation match.",
        "ai_tutor_goal_en": "Student must produce 6 yes/no questions about the tutor.",
        "ai_tutor_goal_ar": "على الطالب أن ينتج 6 أسئلة نعم/لا عن المعلم.",
        "examples": [
            ("Are you a student?", "هل أنت طالب؟"),
            ("Is she from Lebanon?", "هل هي من لبنان؟"),
            ("Do you work on Mondays?", "هل تعمل يوم الإثنين؟"),
            ("Does he speak English?", "هل يتحدث الإنجليزية؟"),
        ],
        "dialogue": [
            ("Omar", "Is Layla from Tunisia?"),
            ("Amani", "Yes, she is."),
            ("Omar", "Does she speak French?"),
            ("Amani", "Yes, she does."),
        ],
        "checklist": [
            ("I can ask yes/no questions.", "أستطيع طرح أسئلة نعم/لا."),
            ("I use rising intonation.", "أرفع نبرة صوتي في نهاية السؤال."),
        ],
        "arabic_tip": "بالعربية نستخدم \"هل\" في بداية السؤال — بالإنجليزية نقلب ترتيب الفاعل والفعل بدلًا من ذلك.",
        "common_mistake_ar": "\"You are a student?\" مفهومة لكنها ليست طبيعية. الأفضل: \"Are you a student?\" — اقلب الترتيب.",
    },
    {
        "n": 18, "review_group": "R2",
        "title_en": "Answering Questions", "title_ar": "الإجابة عن الأسئلة",
        "cefr": "A1", "minutes": 25, "lesson_type": "grammar",
        "new_language_en": "Short answers — 'Yes, I am.', 'No, I'm not.', 'Yes, he does.', 'No, he doesn't.'",
        "new_language_ar": "الإجابات القصيرة — \"Yes, I am.\"، \"No, I'm not.\"، \"Yes, he does.\"، \"No, he doesn't.\"",
        "vocabulary_en": "Re-uses jobs and routines.",
        "vocabulary_ar": "يعيد استخدام مفردات المهن والروتين.",
        "skill_en": "Give natural short answers, not just 'yes/no'.",
        "skill_ar": "أعطِ إجابات قصيرة طبيعية، ليس فقط \"yes/no\".",
        "grammar_en": "Echo auxiliary in the short answer.",
        "grammar_ar": "تكرار الفعل المساعد في الإجابة القصيرة.",
        "pronunciation_en": "Stress falls on the auxiliary ('Yes, I DO.').",
        "pronunciation_ar": "النبرة تقع على الفعل المساعد (\"Yes, I DO.\").",
        "image_idea": "Chat-bubble exchange between Omar and Layla — question + matched short answer.",
        "speaking_goal_en": "Respond to 8 prompted yes/no questions with full short answers.",
        "speaking_goal_ar": "أجب عن 8 أسئلة نعم/لا بإجابات قصيرة كاملة.",
        "listening_goal_en": "Map heard short answers to the questions they answer.",
        "listening_goal_ar": "اربط الإجابات القصيرة المسموعة بأسئلتها.",
        "quiz_goal_en": "8 items: choose short answer, fix auxiliary, match Q to A.",
        "ai_tutor_goal_en": "Drill 6 personal yes/no Qs requiring the student to use the right auxiliary.",
        "ai_tutor_goal_ar": "تدريب على 6 أسئلة نعم/لا شخصية يستخدم فيها الطالب الفعل المساعد الصحيح.",
        "examples": [
            ("Yes, I am.", "نعم، أنا كذلك."),
            ("No, I'm not.", "لا، لست كذلك."),
            ("Yes, she does.", "نعم، هي تفعل."),
            ("No, they don't.", "لا، هم لا يفعلون."),
        ],
        "dialogue": [
            ("Rashid", "Are you tired?"),
            ("Noor", "Yes, I am."),
            ("Rashid", "Do you want some water?"),
            ("Noor", "No, I don't. Thanks."),
        ],
        "checklist": [
            ("I give natural short answers.", "أعطي إجابات قصيرة طبيعية."),
            ("I echo the right auxiliary.", "أكرر الفعل المساعد الصحيح."),
        ],
        "arabic_tip": "بالإنجليزية، \"yes/no\" وحدها أحيانًا تبدو فظّة. أضف الفعل المساعد لتبدو أكثر أدبًا.",
        "common_mistake_ar": "لا تقل \"Yes, I do\" للسؤال \"Are you a doctor?\" — السؤال يستخدم \"to be\" فالجواب \"Yes, I am.\"",
    },
    {
        "n": 19, "review_group": "R2",
        "title_en": "Asking Questions", "title_ar": "طرح الأسئلة",
        "cefr": "A1", "minutes": 30, "lesson_type": "grammar",
        "new_language_en": "WH-questions — 'What do you do?', 'Where does she work?', 'When do they study?', 'Who is he?', 'Why are you tired?'",
        "new_language_ar": "أسئلة WH — \"What do you do?\"، \"Where does she work?\"، \"When do they study?\"، \"Who is he?\"، \"Why are you tired?\"",
        "vocabulary_en": "Five question words: what, where, when, who, why.",
        "vocabulary_ar": "خمس كلمات استفهام: what، where، when، who، why.",
        "skill_en": "Ask for details, not just yes/no.",
        "skill_ar": "اطرح أسئلة عن تفاصيل، ليس فقط نعم/لا.",
        "grammar_en": "WH + auxiliary + subject + base verb.",
        "grammar_ar": "WH + الفعل المساعد + الفاعل + الفعل الأساسي.",
        "pronunciation_en": "Falling intonation at end of WH questions.",
        "pronunciation_ar": "نبرة هابطة في نهاية أسئلة WH.",
        "image_idea": "Five coloured chat bubbles, one per WH-word, around a central listener.",
        "speaking_goal_en": "Ask 6 WH-questions to learn 3 facts about a partner.",
        "speaking_goal_ar": "اطرح 6 أسئلة WH لمعرفة 3 حقائق عن شخص آخر.",
        "listening_goal_en": "Match each heard WH question to its category.",
        "listening_goal_ar": "اربط كل سؤال WH مسموع بفئته (what/where/when/who/why).",
        "quiz_goal_en": "8 items: pick WH word, build the question, listen-and-sort.",
        "ai_tutor_goal_en": "Tutor invites student to ask 4 WH-questions to fill an info gap.",
        "ai_tutor_goal_ar": "يدعو المعلم الطالب لطرح 4 أسئلة WH لسد فجوة معلومات.",
        "examples": [
            ("What do you do?", "ماذا تعمل؟"),
            ("Where does she live?", "أين تعيش؟"),
            ("When do you study?", "متى تدرس؟"),
            ("Why are they late?", "لماذا هم متأخرون؟"),
        ],
        "dialogue": [
            ("Yusuf", "Where do you work, Salma?"),
            ("Salma", "At a pharmacy in Marrakech."),
            ("Yusuf", "When does it open?"),
            ("Salma", "At 9 every morning."),
        ],
        "checklist": [
            ("I can ask WH-questions.", "أستطيع طرح أسئلة WH."),
            ("I know what, where, when, who, why.", "أعرف what و where و when و who و why."),
            ("I use falling intonation.", "أهبط بنبرة صوتي."),
        ],
        "arabic_tip": "كلمات الاستفهام WH تأتي دائمًا في أول السؤال، تمامًا مثل \"ماذا\" و\"أين\" و\"متى\" بالعربية.",
        "common_mistake_ar": "خطأ شائع: \"Where you live?\" — الصحيح: \"Where do you live?\" مع إضافة \"do\".",
    },
]


# ---------------------------------------------------------------------------
# Compact remaining-units (20–48). Same shape as above but with the most
# verbose strings trimmed — each still produces a full lesson via the
# `build_unit_content()` templater. Trimmed for file length; the templater
# fills sensible defaults when a field is shorter.
# ---------------------------------------------------------------------------

def _u(n, review, title_en, title_ar, cefr, minutes, lesson_type, **kwargs):
    """Compact unit constructor with safe defaults for the optional fields."""
    base = {
        "n": n, "review_group": review,
        "title_en": title_en, "title_ar": title_ar,
        "cefr": cefr, "minutes": minutes, "lesson_type": lesson_type,
        "new_language_en": "",
        "new_language_ar": "",
        "vocabulary_en": "", "vocabulary_ar": "",
        "skill_en": "", "skill_ar": "",
        "grammar_en": "—", "grammar_ar": "—",
        "pronunciation_en": "", "pronunciation_ar": "",
        "image_idea": "",
        "speaking_goal_en": "", "speaking_goal_ar": "",
        "listening_goal_en": "", "listening_goal_ar": "",
        "quiz_goal_en": "8 mixed items aligned with the new construction.",
        "ai_tutor_goal_en": "", "ai_tutor_goal_ar": "",
        "examples": [], "dialogue": [], "checklist": [],
        "arabic_tip": "",
        "common_mistake_ar": "",
    }
    base.update(kwargs)
    return base


UNITS.extend([
    # ===== Cluster 3 — Places & directions =====
    _u(20, "R3", "Around Town", "في أرجاء المدينة", "A1", 18, "vocabulary",
       new_language_en="(vocabulary unit)", new_language_ar="(وحدة مفردات)",
       vocabulary_en="18 places in town (bank, supermarket, school, hospital, pharmacy, mosque, church, post office, library, park, café, restaurant, gas station, bus stop, train station, museum, hotel, bakery).",
       vocabulary_ar="18 مكانًا في المدينة (بنك، سوبرماركت، مدرسة، مستشفى، صيدلية، مسجد، كنيسة، مكتب بريد، مكتبة، حديقة، مقهى، مطعم، محطة وقود، موقف باص، محطة قطار، متحف، فندق، مخبز).",
       skill_en="Name common places in a town.", skill_ar="تسمية الأماكن الشائعة في المدينة.",
       image_idea="18-tile flat illustration grid of place icons on a soft pastel background.",
       speaking_goal_en="Tour your neighbourhood on a mental map, name 8 places aloud.",
       examples=[("There is a school here.","هناك مدرسة هنا."),("That is a hospital.","ذلك مستشفى."),("This is my favourite café.","هذا مقهاي المفضل."),("The library is closed.","المكتبة مغلقة.")],
       dialogue=[("Layla","Is there a bank near here?"),("Omar","Yes, on Main Street."),("Layla","And a pharmacy?"),("Omar","Next to the bank.")],
       checklist=[("I can name 10 places in a town.","أستطيع تسمية 10 أماكن في المدينة.")],
       arabic_tip="بعض الأماكن لها اسمان: \"shop\" بريطاني و\"store\" أمريكي. نستخدم store في Onlenco.",
       common_mistake_ar="\"library\" تعني المكتبة العامة، أما \"bookstore\" فهي محل بيع الكتب."),

    _u(21, "R3", "Talking About Your Town", "التحدث عن مدينتك", "A1", 28, "grammar",
       new_language_en="There is / there are.", new_language_ar="There is / there are.",
       vocabulary_en="Town buildings; numbers 1–20 for counting.", vocabulary_ar="مباني المدينة؛ الأرقام 1–20 للعدّ.",
       skill_en="Describe what is in your town.", skill_ar="صف ما يوجد في مدينتك.",
       grammar_en="Singular vs plural noun → is/are.", grammar_ar="مفرد أم جمع → is/are.",
       pronunciation_en="Linking 'there's a' → /ðerz.ə/.",
       image_idea="Top-down stylised map of a fictional town with labelled landmarks.",
       speaking_goal_en="Record 6 sentences about your neighbourhood using 'there is/are'.",
       examples=[("There is a park near my house.","هناك حديقة قرب منزلي."),("There are two schools.","هناك مدرستان."),("There is one bank.","هناك بنك واحد."),("There aren't any cafés here.","لا توجد مقاهٍ هنا.")],
       dialogue=[("Hala","Tell me about your town."),("Yusuf","There is a market and there are three mosques."),("Hala","Are there any parks?"),("Yusuf","Yes, there are two big parks.")],
       checklist=[("I can use there is and there are.","أستخدم there is و there are."),("I can describe my town.","أستطيع وصف مدينتي.")],
       arabic_tip="\"There is\" و\"there are\" تترجم بالعربية إلى \"يوجد/توجد\" أو \"هناك\".",
       common_mistake_ar="بعد \"there is\" نضع اسمًا مفردًا، وبعد \"there are\" اسمًا جمعًا."),

    _u(22, "R3", "Using A, An, and The", "استخدام a / an / the", "A1", 25, "grammar",
       new_language_en="a / an / the.", new_language_ar="a / an / the.",
       vocabulary_en="Re-uses town places.", vocabulary_ar="يعيد استخدام مفردات الأماكن.",
       skill_en="Use the correct article.", skill_ar="استخدم الأداة الصحيحة.",
       grammar_en="a before consonant sound, an before vowel sound, the for known reference.",
       grammar_ar="a قبل الحرف الساكن، an قبل الحرف المتحرك، the للإشارة لشيء معروف.",
       pronunciation_en="the /ðiː/ before vowels vs /ðə/ before consonants.",
       image_idea="Three café scenes labelled 'a café' / 'an old café' / 'the café'.",
       speaking_goal_en="Read 8 sentences aloud picking the right article.",
       examples=[("I see a dog.","أرى كلبًا."),("She has an apple.","لديها تفاحة."),("The teacher is here.","المعلّم هنا."),("That is an old book.","ذاك كتاب قديم.")],
       dialogue=[("Tarek","Is this the bank?"),("Salma","No, it's a pharmacy."),("Tarek","And the supermarket?"),("Salma","Next to the school.")],
       checklist=[("I use a before consonants.","أستخدم a قبل الحروف الساكنة."),("I use an before vowels.","أستخدم an قبل الحروف المتحركة."),("I use the for known things.","أستخدم the للأشياء المعروفة.")],
       arabic_tip="بالعربية، \"الـ\" تساوي \"the\". لكن لا يوجد ما يماثل \"a/an\" بالضبط — هذا فرق مهم.",
       common_mistake_ar="لا نقول \"a apple\" — نقول \"an apple\" لأن \"apple\" تبدأ بصوت متحرك."),

    _u(23, "R3", "Orders and Directions", "الأوامر والاتجاهات", "A1", 30, "speaking",
       new_language_en="Imperatives — 'Turn left.', 'Go straight.', 'Don't stop.'",
       new_language_ar="صيغة الأمر — \"Turn left.\"، \"Go straight.\"، \"Don't stop.\"",
       vocabulary_en="Direction verbs (turn, go, take, cross, stop, walk, follow); left/right/straight/here/there.",
       vocabulary_ar="أفعال الاتجاه (turn، go، take، cross، stop، walk، follow)؛ left/right/straight/here/there.",
       skill_en="Give and follow directions.", skill_ar="أعطِ اتجاهات واتّبعها.",
       grammar_en="Bare imperative; negative imperative with don't.",
       grammar_ar="صيغة الأمر المجردة؛ النفي بـ don't.",
       image_idea="Simple street grid with one route highlighted by green dashes.",
       speaking_goal_en="Give a 30-second set of directions on a map.",
       examples=[("Turn right at the bank.","اتجه يمينًا عند البنك."),("Go straight for two blocks.","اذهب مباشرة لمسافة شارعين."),("Don't cross the bridge.","لا تعبر الجسر."),("Take the second left.","خذ الشارع الثاني يسارًا.")],
       dialogue=[("Noor","How do I get to the museum?"),("Kareem","Go straight, then turn left."),("Noor","Is it far?"),("Kareem","No, it's near the bank.")],
       checklist=[("I can give simple directions.","أستطيع إعطاء اتجاهات بسيطة."),("I can follow spoken directions.","أستطيع متابعة اتجاهات منطوقة.")],
       arabic_tip="صيغة الأمر بالإنجليزية بسيطة جدًا — استخدم الفعل الأساسي بدون فاعل: \"Go!\" \"Stop!\".",
       common_mistake_ar="لا تستخدم \"to\" مع الأمر. خطأ: \"To turn right.\" صحيح: \"Turn right.\""),

    _u(24, "R3", "Joining Sentences", "ربط الجمل", "A1", 22, "grammar",
       new_language_en="and / but.", new_language_ar="and / but.",
       vocabulary_en="Re-uses town, job, family vocab.", vocabulary_ar="يعيد استخدام مفردات المدينة والمهن والعائلة.",
       skill_en="Combine 2 short sentences into one.", skill_ar="ادمج جملتين قصيرتين في واحدة.",
       grammar_en="Coordinator placement; comma before but in longer sentences.",
       grammar_ar="موقع حرف العطف؛ فاصلة قبل but في الجمل الطويلة.",
       image_idea="Two-panel composition — left 'She's a teacher' + right 'She's a runner' joined by 'and'.",
       speaking_goal_en="Combine 6 sentence pairs out loud using and/but.",
       examples=[("Yusuf is a developer and Hala is a designer.","يوسف مطوّر وهالة مصمّمة."),("I like tea but I don't like coffee.","أحب الشاي لكن لا أحب القهوة."),("She works hard and she studies.","هي تعمل بجد وتدرس."),("He is fast but he is tired.","هو سريع لكنه متعب.")],
       dialogue=[("Layla","Where do you work?"),("Rashid","I study and I work part-time."),("Layla","Is it tiring?"),("Rashid","Yes, but I like it.")],
       checklist=[("I can join sentences with and.","أستطيع ربط الجمل بـ and."),("I can contrast with but.","أستطيع المعارضة بـ but.")],
       arabic_tip="\"and\" تساوي \"و\"، و\"but\" تساوي \"لكن\" — قواعد مماثلة في الترتيب.",
       common_mistake_ar="بعد \"but\" نواصل الفكرة بفعل أو فاعل — \"I like tea, but coffee.\" غير مكتمل."),

    _u(25, "R3", "Describing Places", "وصف الأماكن", "A1", 25, "grammar",
       new_language_en="Adjectives — 'a small park', 'an old library'.",
       new_language_ar="الصفات — \"a small park\"، \"an old library\".",
       vocabulary_en="10 adjectives (small, big, old, new, busy, quiet, clean, dirty, beautiful, modern).",
       vocabulary_ar="10 صفات (صغير، كبير، قديم، جديد، مزدحم، هادئ، نظيف، متسخ، جميل، حديث).",
       skill_en="Describe places using adjectives.", skill_ar="صف الأماكن باستخدام الصفات.",
       grammar_en="Adjective before noun; opinion-size-age order.",
       grammar_ar="الصفة قبل الاسم؛ ترتيب الرأي-الحجم-العمر.",
       image_idea="Side-by-side scenes — 'a small park' vs 'a big park' / 'an old café' vs 'a modern café'.",
       speaking_goal_en="Describe 5 places in your town using 2 adjectives each.",
       examples=[("Khartoum is a big city.","الخرطوم مدينة كبيرة."),("This is a small mosque.","هذا مسجد صغير."),("The library is quiet.","المكتبة هادئة."),("That café is busy.","ذلك المقهى مزدحم.")],
       dialogue=[("Omar","Is your neighbourhood nice?"),("Amani","Yes, it's quiet and clean."),("Omar","And your favourite café?"),("Amani","It's small but beautiful.")],
       checklist=[("I can use adjectives before nouns.","أستخدم الصفات قبل الأسماء."),("I can describe places.","أستطيع وصف الأماكن.")],
       arabic_tip="بالإنجليزية، الصفة دائمًا قبل الاسم: \"a big house\". بالعربية، عكس ذلك: \"بيت كبير\".",
       common_mistake_ar="لا تجمع الصفة بالإنجليزية. \"two big houses\" وليس \"two bigs houses\"."),

    _u(26, "R3", "Giving Reasons", "إعطاء الأسباب", "A1", 22, "grammar",
       new_language_en="because.", new_language_ar="because.",
       vocabulary_en="Re-uses jobs, places, routines.", vocabulary_ar="يعيد استخدام مفردات المهن والأماكن والروتين.",
       skill_en="Give a reason for a fact.", skill_ar="أعطِ سببًا لحقيقة.",
       grammar_en="Main clause + because + subordinate clause.",
       grammar_ar="جملة رئيسية + because + جملة فرعية.",
       image_idea="Cause-effect dual panel — top 'She is happy.', bottom 'She has a new job.'",
       speaking_goal_en="Give 4 'because' answers to 'Why …?' prompts.",
       examples=[("I'm tired because I work at night.","أنا متعب لأنني أعمل ليلًا."),("She is happy because she has a new job.","هي سعيدة لأن لديها وظيفة جديدة."),("He doesn't drink coffee because he can't sleep.","هو لا يشرب القهوة لأنه لا يستطيع النوم."),("They study English because they want to travel.","هم يدرسون الإنجليزية لأنهم يريدون السفر.")],
       dialogue=[("Hala","Why are you late?"),("Tarek","Because the bus was late."),("Hala","And why aren't you tired?"),("Tarek","Because I slept early.")],
       checklist=[("I can give reasons with because.","أستطيع إعطاء أسباب بـ because.")],
       arabic_tip="\"because\" تساوي \"لأن\" — تأتي قبل السبب مباشرة.",
       common_mistake_ar="لا تضع نقطة قبل \"because\" — هي تربط جملتين في جملة واحدة."),

    # ===== Cluster 4 — Possessions & home =====
    _u(27, "R4", "Around the House", "في أرجاء المنزل", "A1", 18, "vocabulary",
       new_language_en="(vocabulary unit)", new_language_ar="(وحدة مفردات)",
       vocabulary_en="12 rooms: kitchen, living room, bedroom, bathroom, garage, garden, balcony, hallway, dining room, office, attic, basement.",
       vocabulary_ar="12 غرفة: مطبخ، غرفة معيشة، غرفة نوم، حمّام، كراج، حديقة، شرفة، ممر، غرفة طعام، مكتب، علّية، قبو.",
       skill_en="Name rooms.", skill_ar="تسمية الغرف.",
       image_idea="Flat floor plan of a small fictional apartment with labelled rooms.",
       speaking_goal_en="Walk through your home in 30s naming rooms.",
       examples=[("This is the kitchen.","هذا هو المطبخ."),("My bedroom is small.","غرفة نومي صغيرة."),("The balcony is sunny.","الشرفة مشمسة."),("Our living room has a sofa.","غرفة معيشتنا فيها أريكة.")],
       dialogue=[("Yusuf","Where is the bathroom?"),("Salma","Next to the kitchen."),("Yusuf","And the office?"),("Salma","Upstairs.")],
       checklist=[("I can name 8 rooms in a house.","أستطيع تسمية 8 غرف في المنزل.")],
       arabic_tip="\"living room\" تساوي \"غرفة المعيشة\" أو \"الصالة\". اختلاف ثقافي مهم.",
       common_mistake_ar="\"room\" تعني غرفة محددة، أما \"house\" فهي البيت كله."),

    _u(28, "R4", "The Things I Have", "الأشياء التي لديّ", "A1", 25, "grammar",
       new_language_en="have / has.", new_language_ar="have / has.",
       vocabulary_en="16 household items (TV, fridge, oven, microwave, sofa, bed, table, chair, washing machine, lamp, mirror, carpet, curtains, clock, plant, shelf).",
       vocabulary_ar="16 شيئًا منزليًا (تلفاز، ثلاجة، فرن، ميكروويف، أريكة، سرير، طاولة، كرسي، غسالة، مصباح، مرآة، سجاد، ستائر، ساعة، نبتة، رف).",
       skill_en="Talk about possessions.", skill_ar="تحدّث عن المُلكية.",
       grammar_en="have vs has; I/you/we/they vs he/she/it.",
       grammar_ar="have مقابل has؛ I/you/we/they مقابل he/she/it.",
       image_idea="Stylised living room cross-section; objects labelled.",
       speaking_goal_en="List 5 things you have in your living room.",
       examples=[("I have a TV.","لديّ تلفاز."),("She has two kids.","لديها طفلان."),("We have a small kitchen.","لدينا مطبخ صغير."),("They have a new sofa.","لديهم أريكة جديدة.")],
       dialogue=[("Layla","Do you have a microwave?"),("Rashid","No, but I have an oven."),("Layla","Does your sister have one?"),("Rashid","Yes, she has a new one.")],
       checklist=[("I can use have and has.","أستخدم have و has."),("I can name 10 household items.","أستطيع تسمية 10 أدوات منزلية.")],
       arabic_tip="\"have\" تستخدم مع I/you/we/they، و\"has\" مع he/she/it. تذكر الفرق.",
       common_mistake_ar="\"He have\" خطأ. الصحيح: \"He has\"."),

    _u(29, "R4", "What Do You Have?", "ماذا لديك؟", "A1", 25, "grammar",
       new_language_en="Questions with have — 'Do you have a microwave?', 'Does he have a car?'",
       new_language_ar="أسئلة have — \"Do you have a microwave?\"، \"Does he have a car?\"",
       vocabulary_en="Re-uses house and furniture.", vocabulary_ar="يعيد استخدام مفردات المنزل والأثاث.",
       skill_en="Ask about possessions.", skill_ar="اسأل عن المُلكية.",
       grammar_en="do/does + subject + have.",
       grammar_ar="do/does + الفاعل + have.",
       pronunciation_en="Linking 'do you' → /ˈdʒə/.",
       image_idea="Two characters in a kitchen — one checks a shopping list, the other answers.",
       speaking_goal_en="Ask 5 'Do you have …?' questions of a partner.",
       examples=[("Do you have a phone?","هل لديك هاتف؟"),("Does she have a car?","هل لديها سيارة؟"),("Do they have kids?","هل لديهم أطفال؟"),("Does he have time?","هل لديه وقت؟")],
       dialogue=[("Hala","Do you have a washing machine?"),("Tarek","Yes, I do."),("Hala","Does Salma have one too?"),("Tarek","No, she doesn't.")],
       checklist=[("I can ask Do you have …?.","أستطيع السؤال بـ Do you have …?."),("I can ask Does he/she have …?.","أستطيع السؤال بـ Does he/she have …?.")],
       arabic_tip="بدلًا من \"have you\" البريطانية القديمة، نستخدم \"do you have\" في الإنجليزية الأمريكية.",
       common_mistake_ar="بعد \"does\" نضع \"have\" وليس \"has\". \"Does she have …?\" وليس \"Does she has …?\"."),

    _u(30, "R4", "Food and Drink", "الطعام والشراب", "A1", 20, "vocabulary",
       new_language_en="(vocabulary unit)", new_language_ar="(وحدة مفردات)",
       vocabulary_en="20 foods/drinks (bread, rice, chicken, fish, beef, eggs, milk, water, tea, coffee, juice, fruit, apples, bananas, tomatoes, onions, salt, sugar, cheese, yogurt).",
       vocabulary_ar="20 طعامًا/شرابًا (خبز، أرز، دجاج، سمك، لحم بقري، بيض، حليب، ماء، شاي، قهوة، عصير، فواكه، تفاح، موز، طماطم، بصل، ملح، سكر، جبنة، زبادي).",
       skill_en="Name common foods and drinks.", skill_ar="تسمية الأطعمة والمشروبات الشائعة.",
       image_idea="Flat illustration tile grid of foods, no plates or characters.",
       speaking_goal_en="List 6 foods you eat weekly.",
       examples=[("I drink tea every morning.","أشرب الشاي كل صباح."),("She eats fish on Fridays.","هي تأكل السمك أيام الجمعة."),("We need bread and milk.","نحتاج خبزًا وحليبًا."),("They sell fresh fruit.","يبيعون فواكه طازجة.")],
       dialogue=[("Noor","What's for dinner?"),("Kareem","Chicken and rice."),("Noor","Do we have apples?"),("Kareem","Yes, in the fridge.")],
       checklist=[("I can name 10 foods.","أستطيع تسمية 10 أطعمة."),("I can name 5 drinks.","أستطيع تسمية 5 مشروبات.")],
       arabic_tip="بالإنجليزية، أسماء الأطعمة عادة بدون \"the\" عند الحديث عن العادة. \"I like tea\" وليس \"I like the tea\".",
       common_mistake_ar="\"fish\" مفرد وجمع في نفس الوقت — لا نقول \"fishes\" عادةً."),

    _u(31, "R4", "Counting", "العَدّ", "A1", 25, "grammar",
       new_language_en="Uncountable nouns — 'some bread', 'a piece of cheese', 'two glasses of water'.",
       new_language_ar="الأسماء غير المعدودة — \"some bread\"، \"a piece of cheese\"، \"two glasses of water\".",
       vocabulary_en="Food containers (bottle, glass, cup, slice, piece, bowl, can, pack).",
       vocabulary_ar="عبوات الطعام (زجاجة، كوب، فنجان، شريحة، قطعة، وعاء، علبة، كيس).",
       skill_en="Talk about food quantities.", skill_ar="تحدّث عن كميات الطعام.",
       grammar_en="a/an with countable; some with uncountable; container + of.",
       grammar_ar="a/an مع المعدود؛ some مع غير المعدود؛ العبوة + of.",
       image_idea="A café counter with labelled containers (bottle, glass, cup) and food items.",
       speaking_goal_en="Order 5 items from a stylised café menu.",
       examples=[("I'd like a glass of water.","أرغب في كوب ماء."),("She wants two slices of bread.","تريد شريحتي خبز."),("We need some sugar.","نحتاج بعض السكر."),("He has a cup of tea.","لديه فنجان شاي.")],
       dialogue=[("Tarek","Welcome! What would you like?"),("Hala","A coffee and two slices of cake."),("Tarek","Anything else?"),("Hala","A bottle of water, please.")],
       checklist=[("I know countable and uncountable.","أعرف المعدود وغير المعدود."),("I can order food and drink.","أستطيع طلب طعام وشراب.")],
       arabic_tip="بالإنجليزية، السوائل (water، milk، coffee) دائمًا غير معدودة. لذا نقول \"a glass of water\" وليس \"a water\".",
       common_mistake_ar="\"bread\" و\"rice\" و\"cheese\" غير معدودة. لا تقل \"two breads\" — قل \"two slices of bread\"."),

    _u(32, "R4", "Measuring", "القياس", "A1", 22, "grammar",
       new_language_en="Measurements — '500 grams of flour', '2 liters of milk', '1 cup of sugar'.",
       new_language_ar="القياسات — \"500 grams of flour\"، \"2 liters of milk\"، \"1 cup of sugar\".",
       vocabulary_en="Units (gram, kilogram, liter, milliliter, cup, teaspoon, tablespoon).",
       vocabulary_ar="وحدات (غرام، كيلوغرام، لتر، ميليلتر، كوب، ملعقة شاي، ملعقة طعام).",
       skill_en="State quantities like a recipe.", skill_ar="اذكر كميات كما في الوصفة.",
       image_idea="A measuring jug, a scale, and a spoon labelled with their units.",
       speaking_goal_en="Read a 4-line recipe out loud.",
       examples=[("Add 500 grams of flour.","أضف 500 غرامًا من الدقيق."),("Pour 2 liters of milk.","اسكب لترين من الحليب."),("Use 1 cup of sugar.","استخدم كوبًا من السكر."),("Add a teaspoon of salt.","أضف ملعقة شاي من الملح.")],
       dialogue=[("Layla","How much milk do we need?"),("Omar","2 liters."),("Layla","And flour?"),("Omar","Half a kilogram.")],
       checklist=[("I can talk about amounts.","أستطيع الحديث عن الكميات."),("I know 4 units of measure.","أعرف 4 وحدات قياس.")],
       arabic_tip="الولايات المتحدة تستخدم كوب (cup) وملعقة شاي (teaspoon) أكثر من الغرامات في الطبخ.",
       common_mistake_ar="نقول \"2 grams\" بالجمع، لكن \"1 gram\" بالمفرد. لاحظ القاعدة."),

    _u(33, "R4", "Clothes", "الملابس", "A1", 18, "vocabulary",
       new_language_en="(vocabulary unit)", new_language_ar="(وحدة مفردات)",
       vocabulary_en="18 clothes (shirt, t-shirt, sweater, jacket, coat, pants, jeans, shorts, skirt, dress, suit, sneakers, shoes, boots, hat, scarf, gloves, socks).",
       vocabulary_ar="18 قطعة ملابس (قميص، تي-شيرت، كنزة، جاكيت، معطف، بنطلون، جينز، شورت، تنّورة، فستان، بدلة، حذاء رياضي، حذاء، بوت، قبعة، وشاح، قفازات، جوارب).",
       skill_en="Name clothes.", skill_ar="تسمية الملابس.",
       pronunciation_en="Silent letter 'clothes' /kloʊz/.",
       image_idea="A wardrobe view with labelled garments on hangers.",
       speaking_goal_en="Name 6 items in your wardrobe.",
       examples=[("I have a red shirt.","لديّ قميص أحمر."),("She wears black sneakers.","ترتدي حذاءً رياضيًا أسود."),("These jeans are new.","هذا الجينز جديد."),("That hat is mine.","تلك القبعة لي.")],
       dialogue=[("Rashid","Where is my sweater?"),("Amani","On the chair."),("Rashid","And my socks?"),("Amani","In the drawer.")],
       checklist=[("I can name 10 clothes items.","أستطيع تسمية 10 قطع ملابس.")],
       arabic_tip="بالإنجليزية الأمريكية: \"pants\"، \"sneakers\"، \"sweater\". (البريطانية: trousers، trainers، jumper.)",
       common_mistake_ar="\"pants\" دائمًا بالجمع. \"a pants\" خطأ — قل \"a pair of pants\" أو \"these pants\"."),

    _u(34, "R4", "At the Store", "في المتجر", "A1", 25, "speaking",
       new_language_en="too / fit — 'This is too big.', 'It doesn't fit.'",
       new_language_ar="too / fit — \"This is too big.\"، \"It doesn't fit.\"",
       vocabulary_en="Sizes (small, medium, large, XL); shopping verbs (try on, buy, pay, return).",
       vocabulary_ar="المقاسات (S، M، L، XL)؛ أفعال التسوق (يجرّب، يشتري، يدفع، يرجع).",
       skill_en="Describe clothes that fit or don't fit.", skill_ar="صف ملابس تناسبك أو لا تناسبك.",
       grammar_en="too + adjective; doesn't fit.", grammar_ar="too + صفة؛ doesn't fit.",
       image_idea="Character in a fitting room; speech bubble 'This is too big.'",
       speaking_goal_en="Role-play a 30-sec store conversation.",
       examples=[("This is too big.","هذا كبير جدًا."),("These shoes don't fit.","هذا الحذاء لا يناسبني."),("That dress is too expensive.","ذلك الفستان غالٍ جدًا."),("I'll try the medium.","سأجرّب مقاس M.")],
       dialogue=[("Salma","Can I try this shirt?"),("Tarek","Sure. What size?"),("Salma","Medium, please."),("Tarek","Here you are.")],
       checklist=[("I can describe clothes that fit.","أستطيع وصف ملابس مناسبة المقاس."),("I can use too with adjectives.","أستخدم too مع الصفات.")],
       arabic_tip="\"too\" تعني \"أكثر من اللازم\" وليس \"أيضًا\" دائمًا — \"too big\" أي كبير جدًا.",
       common_mistake_ar="\"It doesn't fit\" تعني المقاس غير مناسب. \"I don't like it\" تعني لا يعجبني."),

    # ===== Cluster 5 — Preferences & free time =====
    _u(35, "R5", "Describing Things", "وصف الأشياء", "A1", 22, "grammar",
       new_language_en="Opinion adjectives — 'It's nice.', 'That's interesting.'",
       new_language_ar="صفات الرأي — \"It's nice.\"، \"That's interesting.\"",
       vocabulary_en="Opinion adjectives (nice, ugly, expensive, cheap, interesting, boring, easy, hard, comfortable, uncomfortable).",
       vocabulary_ar="صفات الرأي (جميل، قبيح، غالٍ، رخيص، مثير، ممل، سهل، صعب، مريح، غير مريح).",
       skill_en="Give an opinion.", skill_ar="أعطِ رأيًا.",
       image_idea="A board of 6 products, each with a thought-bubble adjective.",
       speaking_goal_en="Give 5 opinions on shown objects.",
       examples=[("This sofa is comfortable.","هذه الأريكة مريحة."),("That book is boring.","ذلك الكتاب ممل."),("It's a beautiful day.","إنه يوم جميل."),("This phone is expensive.","هذا الهاتف غالٍ.")],
       dialogue=[("Layla","What do you think of this jacket?"),("Yusuf","It's nice, but expensive."),("Layla","And this hat?"),("Yusuf","It's interesting!")],
       checklist=[("I can give an opinion.","أستطيع إعطاء رأي."),("I can use opinion adjectives.","أستخدم صفات الرأي.")],
       arabic_tip="\"interesting\" تعني مثير للاهتمام، لكنها أحيانًا تستخدم بأدب لتفادي قول \"غريب\".",
       common_mistake_ar="\"boring\" تصف الشيء، و\"bored\" تصف الشخص. \"The film is boring\" مقابل \"I am bored\"."),

    _u(36, "R5", "Sports", "الرياضات", "A1", 15, "vocabulary",
       new_language_en="(vocabulary unit)", new_language_ar="(وحدة مفردات)",
       vocabulary_en="14 sports (soccer, basketball, tennis, running, swimming, cycling, volleyball, table tennis, boxing, golf, baseball, skiing, surfing, hiking).",
       vocabulary_ar="14 رياضة (كرة قدم، كرة سلة، تنس، جري، سباحة، دراجة، كرة طائرة، تنس طاولة، ملاكمة، غولف، بيسبول، تزلج، ركوب أمواج، تسلق).",
       skill_en="Name sports.", skill_ar="تسمية الرياضات.",
       image_idea="14-tile flat illustration grid of sport pictograms.",
       speaking_goal_en="List 6 sports you've tried or seen.",
       examples=[("I play soccer.","ألعب كرة القدم."),("She goes swimming.","تذهب للسباحة."),("They play volleyball.","يلعبون كرة الطائرة."),("He likes basketball.","يحب كرة السلة.")],
       dialogue=[("Omar","Do you like sports?"),("Hala","Yes, I love tennis."),("Omar","Do you play?"),("Hala","Sometimes, on weekends.")],
       checklist=[("I can name 10 sports.","أستطيع تسمية 10 رياضات.")],
       arabic_tip="بالإنجليزية الأمريكية، \"soccer\" تعني كرة القدم، و\"football\" تعني كرة القدم الأمريكية.",
       common_mistake_ar="\"play\" مع رياضات الكرة، و\"go\" مع الرياضات بـ -ing (swimming، running)."),

    _u(37, "R5", "Talking About Sports", "التحدث عن الرياضة", "A1", 22, "grammar",
       new_language_en="go / play — 'I go swimming.', 'I play soccer.'",
       new_language_ar="go / play — \"I go swimming.\"، \"I play soccer.\"",
       vocabulary_en="Re-uses sports.", vocabulary_ar="يعيد استخدام مفردات الرياضات.",
       skill_en="Talk about which sports you do.", skill_ar="تحدّث عن الرياضات التي تمارسها.",
       grammar_en="go + -ing sports vs play + ball sports.",
       grammar_ar="go + رياضات بـ -ing مقابل play + رياضات الكرة.",
       image_idea="Split screen — left someone running ('go running'), right people playing soccer ('play soccer').",
       speaking_goal_en="Describe what sports you do per week.",
       examples=[("I go running every morning.","أذهب للجري كل صباح."),("She plays tennis on Sundays.","تلعب التنس أيام الأحد."),("We go swimming together.","نذهب للسباحة معًا."),("They play basketball at school.","يلعبون كرة السلة في المدرسة.")],
       dialogue=[("Kareem","What sports do you do?"),("Noor","I go cycling and I play tennis."),("Kareem","Do you go swimming?"),("Noor","No, I don't swim.")],
       checklist=[("I can use go + sport.","أستخدم go مع الرياضة."),("I can use play + sport.","أستخدم play مع الرياضة.")],
       arabic_tip="القاعدة: لو اسم الرياضة ينتهي بـ -ing → استخدم \"go\". لو الرياضة بها كرة → استخدم \"play\".",
       common_mistake_ar="\"I play swimming\" خطأ. الصحيح: \"I go swimming\"."),

    _u(38, "R5", "Hobbies and Pastimes", "الهوايات", "A1", 18, "vocabulary",
       new_language_en="(vocabulary unit)", new_language_ar="(وحدة مفردات)",
       vocabulary_en="14 hobbies (reading, painting, gardening, cooking, photography, gaming, dancing, knitting, fishing, chess, writing, singing, drawing, traveling).",
       vocabulary_ar="14 هواية (قراءة، رسم بألوان، بستنة، طبخ، تصوير، ألعاب فيديو، رقص، حياكة، صيد، شطرنج، كتابة، غناء، رسم، سفر).",
       skill_en="Name hobbies.", skill_ar="تسمية الهوايات.",
       image_idea="14-tile grid of stylised hobby icons.",
       speaking_goal_en="List 4 hobbies you have and 2 you'd like to try.",
       examples=[("I like reading.","أحب القراءة."),("She enjoys painting.","تستمتع بالرسم."),("He plays chess.","يلعب الشطرنج."),("They go fishing on Saturdays.","يذهبون للصيد أيام السبت.")],
       dialogue=[("Tarek","What are your hobbies?"),("Salma","Cooking and reading."),("Tarek","Do you cook every day?"),("Salma","Almost every day.")],
       checklist=[("I can name 10 hobbies.","أستطيع تسمية 10 هوايات.")],
       arabic_tip="الهوايات بالإنجليزية كثيرًا ما تنتهي بـ -ing لأنها أفعال تحوّلت إلى أسماء.",
       common_mistake_ar="\"I like to read\" و\"I like reading\" كلاهما صحيح. لكن في الكلام، \"reading\" أشيع."),

    _u(39, "R5", "Free Time", "وقت الفراغ", "A1", 25, "grammar",
       new_language_en="Adverbs of frequency — always, usually, often, sometimes, rarely, never.",
       new_language_ar="ظروف التكرار — always، usually، often، sometimes، rarely، never.",
       vocabulary_en="Re-uses hobbies.", vocabulary_ar="يعيد استخدام مفردات الهوايات.",
       skill_en="Talk about how often you do hobbies.", skill_ar="تحدّث عن مدى تكرار ممارستك للهوايات.",
       grammar_en="Adverb position before main verb, after 'to be'.",
       grammar_ar="موقع الظرف قبل الفعل الرئيسي، بعد to be.",
       image_idea="A horizontal bar gauge labelled with the 6 adverbs at intervals.",
       speaking_goal_en="Build 6 sentences from a chart: 'I [adverb] [hobby].'",
       examples=[("I always read at night.","أقرأ دائمًا في الليل."),("She often cooks.","هي تطبخ كثيرًا."),("They never go fishing.","لا يذهبون للصيد أبدًا."),("He is usually at the gym.","هو عادة في النادي.")],
       dialogue=[("Layla","Do you go to the cinema?"),("Yusuf","Sometimes, on weekends."),("Layla","And the gym?"),("Yusuf","I always go on Tuesdays.")],
       checklist=[("I can use 6 frequency adverbs.","أستخدم 6 ظروف تكرار."),("I can talk about my habits.","أستطيع التحدث عن عاداتي.")],
       arabic_tip="ظرف التكرار يأتي قبل الفعل الرئيسي: \"I always read.\" لاحظ الموقع.",
       common_mistake_ar="مع to be، الظرف يأتي بعدها: \"She is always happy.\" وليس \"She always is happy.\"."),

    _u(40, "R5", "Likes and Dislikes", "الإعجاب وعدم الإعجاب", "A1", 22, "grammar",
       new_language_en="love / like / don't like / hate + noun or -ing.",
       new_language_ar="love / like / don't like / hate + اسم أو -ing.",
       vocabulary_en="Re-uses sports, hobbies, food.", vocabulary_ar="يعيد استخدام مفردات الرياضات والهوايات والطعام.",
       skill_en="Express what you like and don't like.", skill_ar="عبّر عما تحبه وما لا تحبه.",
       grammar_en="Verb + noun OR verb + -ing.", grammar_ar="فعل + اسم أو فعل + -ing.",
       image_idea="A 4-bubble scale with thumbs gestures from love → hate.",
       speaking_goal_en="Give 5 likes/dislikes with a reason each.",
       examples=[("I love coffee.","أحب القهوة."),("She likes swimming.","تحب السباحة."),("He doesn't like spicy food.","لا يحب الأكل الحار."),("They hate boring movies.","يكرهون الأفلام المملة.")],
       dialogue=[("Hala","Do you like jazz?"),("Rashid","Yes, I love it."),("Hala","And reading?"),("Rashid","I like reading novels.")],
       checklist=[("I can say what I like.","أستطيع قول ما أحبه."),("I can say what I don't like.","أستطيع قول ما لا أحبه.")],
       arabic_tip="بعد \"like\" يمكن وضع اسم (\"I like tea\") أو فعل بـ -ing (\"I like swimming\"). كلاهما صحيح.",
       common_mistake_ar="\"I don't like to swim\" و\"I don't like swimming\" صحيحتان، لكن \"I don't like swim\" خطأ."),

    _u(41, "R5", "Music", "الموسيقى", "A1", 15, "vocabulary",
       new_language_en="(vocabulary unit)", new_language_ar="(وحدة مفردات)",
       vocabulary_en="12 genres + 6 instruments (pop, rock, jazz, classical, hip-hop, country, electronic, folk, blues, soul, R&B, reggae; guitar, piano, drums, violin, flute, saxophone).",
       vocabulary_ar="12 نوعًا موسيقيًا + 6 آلات (بوب، روك، جاز، كلاسيكي، هيب-هوب، كانتري، إلكتروني، فولك، بلوز، سول، R&B، ريغي؛ غيتار، بيانو، طبول، كمان، ناي، ساكسفون).",
       skill_en="Name music genres and instruments.", skill_ar="تسمية أنواع الموسيقى والآلات.",
       image_idea="Stylised iconography — speaker, headphones, instruments arranged in two strips.",
       speaking_goal_en="List 4 genres you like + 3 instruments you know.",
       examples=[("I love jazz.","أحب الجاز."),("She plays the piano.","تعزف البيانو."),("They listen to hip-hop.","يستمعون إلى الهيب-هوب."),("He plays the guitar.","يعزف الغيتار.")],
       dialogue=[("Amani","Do you play any instrument?"),("Omar","Yes, I play the guitar."),("Amani","What music do you like?"),("Omar","Rock and blues.")],
       checklist=[("I can name music genres.","أستطيع تسمية أنواع الموسيقى."),("I can name instruments.","أستطيع تسمية الآلات الموسيقية.")],
       arabic_tip="نقول \"play the piano\" مع \"the\". لكن \"play soccer\" بدون \"the\".",
       common_mistake_ar="\"I play piano\" مقبولة في الحديث غير الرسمي، لكن \"I play the piano\" أصح."),

    _u(42, "R5", "Expressing Preference", "التعبير عن التفضيل", "A1", 22, "grammar",
       new_language_en="favorite — 'My favorite music is jazz.'",
       new_language_ar="favorite — \"My favorite music is jazz.\"",
       vocabulary_en="Re-uses food, music, sports, hobbies.", vocabulary_ar="يعيد استخدام مفردات الطعام والموسيقى والرياضات والهوايات.",
       skill_en="Talk about favorites.", skill_ar="تحدّث عن المفضلات.",
       grammar_en="Possessive + favorite + noun.",
       grammar_ar="ضمير ملكية + favorite + اسم.",
       image_idea="A board of 'favorites' — small cards each with a topic + selected item.",
       speaking_goal_en="Give 4 'My favorite X is Y' statements.",
       examples=[("My favorite color is blue.","لوني المفضل أزرق."),("Her favorite sport is tennis.","رياضتها المفضلة التنس."),("Our favorite café is near the park.","مقهانا المفضل قرب الحديقة."),("His favorite singer is from Egypt.","مغنّيه المفضل من مصر.")],
       dialogue=[("Tarek","What's your favorite food?"),("Layla","Pizza. And yours?"),("Tarek","I love Sudanese food — kisra is my favorite."),("Layla","I want to try it!")],
       checklist=[("I can talk about favorites.","أستطيع التحدث عن المفضلات."),("I can use favorite in a sentence.","أستخدم favorite في جملة.")],
       arabic_tip="بالإنجليزية الأمريكية: \"favorite\". البريطانية: \"favourite\". نستخدم \"favorite\" في Onlenco.",
       common_mistake_ar="\"favorite\" دائمًا قبل الاسم: \"my favorite book\" وليس \"book favorite\"."),

    # ===== Cluster 6 — Ability & ambition =====
    _u(43, "R6", "Abilities", "المهارات والقدرات", "A1", 15, "vocabulary",
       new_language_en="(vocabulary unit)", new_language_ar="(وحدة مفردات)",
       vocabulary_en="14 abilities (drive, swim, cook, dance, sing, draw, paint, code, type, ride a bike, speak French, play piano, juggle, ski).",
       vocabulary_ar="14 قدرة (يقود، يسبح، يطبخ، يرقص، يغني، يرسم، يلوّن، يبرمج، يطبع، يركب دراجة، يتحدث الفرنسية، يعزف بيانو، يرمي ويلتقط، يتزلج).",
       skill_en="Name abilities.", skill_ar="تسمية القدرات.",
       image_idea="14-tile grid of stick figures doing each ability.",
       speaking_goal_en="List 4 things you can do.",
       examples=[("I can swim.","أستطيع السباحة."),("She can drive.","تستطيع القيادة."),("He can code.","يستطيع البرمجة."),("They can sing well.","يستطيعون الغناء جيدًا.")],
       dialogue=[("Noor","Can you ride a bike?"),("Kareem","Yes, I can."),("Noor","Can you swim?"),("Kareem","Yes, but not very well.")],
       checklist=[("I can name 10 abilities.","أستطيع تسمية 10 قدرات.")],
       arabic_tip="فعل \"can\" لا يضيف -s مع he/she/it — لا نقول \"He cans\".",
       common_mistake_ar="بعد \"can\" نضع الفعل الأساسي بدون \"to\". \"I can to swim\" خطأ. الصحيح: \"I can swim\"."),

    _u(44, "R6", "What You Can and Can't Do", "ما تستطيع وما لا تستطيع فعله", "A1", 25, "grammar",
       new_language_en="can / can't / cannot.", new_language_ar="can / can't / cannot.",
       vocabulary_en="Re-uses abilities.", vocabulary_ar="يعيد استخدام مفردات القدرات.",
       skill_en="State abilities and inabilities.", skill_ar="اذكر القدرات وعدم القدرات.",
       grammar_en="Modal can — no -s in 3rd person; base form follows.",
       grammar_ar="الفعل الناقص can — لا -s مع الضمير الثالث؛ الفعل الأساسي بعدها.",
       pronunciation_en="can /kən/ (weak) vs can't /kænt/ (strong).",
       pronunciation_ar="can /kən/ (ضعيف) مقابل can't /kænt/ (قوي).",
       image_idea="Two characters — one checks 'can' box, the other 'can't'.",
       speaking_goal_en="Make 6 can/can't statements about yourself.",
       examples=[("I can drive a car.","أستطيع قيادة السيارة."),("He can't swim.","هو لا يستطيع السباحة."),("She can speak three languages.","تستطيع التحدث بثلاث لغات."),("They can't come tonight.","لا يستطيعون المجيء الليلة.")],
       dialogue=[("Hala","Can you cook?"),("Rashid","Yes, I can — but only simple meals."),("Hala","Can you bake?"),("Rashid","No, I can't.")],
       checklist=[("I can use can and can't.","أستخدم can و can't."),("I can hear the difference.","أستطيع سماع الفرق بينهما.")],
       arabic_tip="\"can\" تعني \"يستطيع\"، و\"cannot\" أو \"can't\" تعني \"لا يستطيع\".",
       common_mistake_ar="في الكتابة، \"cannot\" تكتب ككلمة واحدة (وليس \"can not\")."),

    _u(45, "R6", "Describing Actions", "وصف الأفعال", "A1", 25, "grammar",
       new_language_en="Regular adverbs (quickly, slowly, quietly) + irregular (well, fast, hard).",
       new_language_ar="ظروف منتظمة (quickly، slowly، quietly) + غير منتظمة (well، fast، hard).",
       vocabulary_en="10 manner adverbs; re-uses ability verbs.", vocabulary_ar="10 ظروف كيفية؛ يعيد استخدام أفعال القدرة.",
       skill_en="Describe how an action is done.", skill_ar="صف كيف يتم الفعل.",
       grammar_en="Adverb position after verb-object; -ly derivation.",
       grammar_ar="موقع الظرف بعد الفعل والمفعول؛ اشتقاق -ly.",
       image_idea="Side-by-side panels — same action done two ways (quickly vs slowly).",
       speaking_goal_en="Describe 5 ability + adverb pairs.",
       examples=[("She runs quickly.","تجري بسرعة."),("He drives carefully.","يقود بحذر."),("They speak quietly.","يتحدثون بهدوء."),("I dance well.","أرقص جيدًا.")],
       dialogue=[("Tarek","How does Salma cook?"),("Yusuf","She cooks slowly but well."),("Tarek","And Omar?"),("Yusuf","He works hard.")],
       checklist=[("I can use adverbs of manner.","أستخدم ظروف الكيفية."),("I can form -ly adverbs.","أستطيع تكوين ظروف بـ -ly.")],
       arabic_tip="معظم الظروف بالإنجليزية تنتهي بـ -ly. \"slow\" → \"slowly\".",
       common_mistake_ar="ليست كل الظروف تنتهي بـ -ly: \"fast\" و\"hard\" و\"well\" غير منتظمة."),

    _u(46, "R6", "Describing Ability", "وصف مستوى المهارة", "A1", 22, "grammar",
       new_language_en="Modifying adverbs — very well, quite well, a little, not at all.",
       new_language_ar="ظروف التعديل — very well، quite well، a little، not at all.",
       vocabulary_en="Skill-level adverbs; re-uses abilities.", vocabulary_ar="ظروف مستوى المهارة؛ يعيد استخدام القدرات.",
       skill_en="Say how well you can do something.", skill_ar="قل مدى براعتك في شيء ما.",
       grammar_en="Adverb-of-degree + manner adverb.",
       grammar_ar="ظرف الدرجة + ظرف الكيفية.",
       image_idea="Horizontal bar gauge from 'not at all' → 'very well'.",
       speaking_goal_en="Describe 5 of your abilities by level.",
       examples=[("I can swim very well.","أستطيع السباحة جيدًا جدًا."),("She can cook a little.","تستطيع الطبخ قليلًا."),("He can't sing at all.","لا يستطيع الغناء أبدًا."),("They can drive quite well.","يستطيعون القيادة جيدًا.")],
       dialogue=[("Layla","Can you speak Spanish?"),("Noor","A little."),("Layla","And French?"),("Noor","Quite well, actually.")],
       checklist=[("I can describe my skill level.","أستطيع وصف مستوى مهارتي."),("I can use very well, a little, not at all.","أستخدم very well و a little و not at all.")],
       arabic_tip="\"quite well\" بالإنجليزية الأمريكية تعني \"جيد جدًا\" (إيجابي). في البريطانية أحيانًا تعني \"مقبول\".",
       common_mistake_ar="\"not at all\" تأتي عادة في نهاية الجملة: \"He can't sing at all.\" — وليس في البداية."),

    _u(47, "R6", "Wishes and Desires", "الرغبات والأمنيات", "A1", 25, "grammar",
       new_language_en="want / would like — 'I want a coffee.', 'I'd like to learn Spanish.'",
       new_language_ar="want / would like — \"I want a coffee.\"، \"I'd like to learn Spanish.\"",
       vocabulary_en="Leisure goals (learn a language, travel, study abroad, get a job, move, save money).",
       vocabulary_ar="أهداف ترفيهية (تعلّم لغة، السفر، الدراسة بالخارج، الحصول على وظيفة، الانتقال، الادخار).",
       skill_en="Talk about your ambitions.", skill_ar="تحدّث عن طموحاتك.",
       grammar_en="want / would like + noun OR to + base verb.",
       grammar_ar="want / would like + اسم أو to + فعل أساسي.",
       pronunciation_en="Contraction I'd /aɪd/.", pronunciation_ar="الاختصار I'd /aɪd/.",
       image_idea="A wish-board collage — sticky notes with goals and small icons.",
       speaking_goal_en="Record 4 wishes for next year.",
       examples=[("I want a new laptop.","أريد لابتوبًا جديدًا."),("She would like to travel.","تودّ السفر."),("They want to learn English.","يريدون تعلّم الإنجليزية."),("I'd like a glass of water.","أرغب في كوب ماء.")],
       dialogue=[("Omar","What do you want to do this year?"),("Hala","I'd like to learn Spanish."),("Omar","And next year?"),("Hala","I want to visit Spain.")],
       checklist=[("I can use want and would like.","أستخدم want و would like."),("I can talk about my goals.","أستطيع التحدث عن أهدافي.")],
       arabic_tip="\"would like\" أكثر أدبًا من \"want\". في المطاعم نقول دائمًا \"I'd like …\" وليس \"I want …\".",
       common_mistake_ar="بعد \"would like\" نضع \"to\" + فعل. \"I'd like swim\" خطأ. الصحيح: \"I'd like to swim\"."),

    _u(48, "R6", "Studying", "الدراسة", "A1", 30, "grammar",
       new_language_en="Adverbs of frequency + articles — 'I usually study in the library.'",
       new_language_ar="ظروف التكرار + الأدوات — \"I usually study in the library.\"",
       vocabulary_en="Academic subjects (math, science, history, geography, English, Arabic, art, music, biology, chemistry, physics, computer science).",
       vocabulary_ar="المواد الأكاديمية (رياضيات، علوم، تاريخ، جغرافيا، إنجليزية، عربية، فن، موسيقى، أحياء، كيمياء، فيزياء، علوم الحاسوب).",
       skill_en="Talk about studying habits and subjects.", skill_ar="تحدّث عن عادات الدراسة والمواد.",
       grammar_en="Adverb position with to be + articles for places.",
       grammar_ar="موقع الظرف مع to be + الأدوات مع الأماكن.",
       pronunciation_en="usually /ˈjuː.ʒu.ə.li/ — 4 syllables.",
       image_idea="A character at a library desk; sticky note with weekly subject list.",
       speaking_goal_en="Record a 40-second routine about how you study.",
       examples=[("I usually study in the library.","عادة أدرس في المكتبة."),("She always reads before bed.","هي تقرأ دائمًا قبل النوم."),("He studies math on weekends.","يدرس الرياضيات في عطلة نهاية الأسبوع."),("We study English together.","ندرس الإنجليزية معًا.")],
       dialogue=[("Rashid","What do you study?"),("Amani","Math, science, and English."),("Rashid","Do you like English?"),("Amani","Yes! It's my favorite.")],
       checklist=[("I can talk about my subjects.","أستطيع التحدث عن مواد دراستي."),("I can use frequency adverbs naturally.","أستخدم ظروف التكرار بشكل طبيعي."),("I'm ready for A1.","أنا جاهز للمستوى A1.")],
       arabic_tip="بعد \"in\" مع الأماكن العامة (the library، the classroom) نضع \"the\" عادة.",
       common_mistake_ar="\"I study English\" تعني الفعل العام. \"I'm studying English\" تعني الآن — انتبه للفرق."),
])

assert len(UNITS) == 48, f"Expected 48 units, got {len(UNITS)}"


# ---------------------------------------------------------------------------
# Content builders. Pure functions: take a unit dict and return strings.
# ---------------------------------------------------------------------------

def _h(s: str) -> str:
    """HTML-escape a piece of inline text."""
    return escape(s or "", quote=True)


def build_content_html(unit: dict) -> str:
    """Produce the 12-section English content for a Lesson's content_html."""
    examples_html = "".join(
        f"<li><strong>{_h(en)}</strong> — <em>{_h(ar)}</em></li>"
        for en, ar in unit.get("examples", [])
    ) or "<li><em>(populated in P12)</em></li>"

    dialogue_html = "".join(
        f"<li><strong>{_h(speaker)}:</strong> {_h(line)}</li>"
        for speaker, line in unit.get("dialogue", [])
    ) or "<li><em>(populated in P12)</em></li>"

    checklist_html = "".join(
        f"<li>{_h(en)}</li>"
        for en, _ar in unit.get("checklist", [])
    ) or "<li><em>(populated)</em></li>"

    return (
        f"<h3>1. Lesson Goal</h3><p>{_h(unit['skill_en'])}</p>"
        f"<h3>2. New Language</h3><p>{_h(unit['new_language_en'])}</p>"
        f"<h3>3. Key Vocabulary</h3><p>{_h(unit['vocabulary_en'])}</p>"
        f"<h3>4. Grammar Focus</h3><p>{_h(unit['grammar_en'])}</p>"
        f"<h3>5. Visual Guide</h3><p><em>{_h(unit['image_idea'])}</em></p>"
        f"<h3>6. Examples</h3><ul>{examples_html}</ul>"
        f"<h3>7. Mini Dialogue</h3><ul>{dialogue_html}</ul>"
        f"<h3>8. Practice Activity</h3><p>{_h(unit['quiz_goal_en'])}</p>"
        f"<h3>9. Listening Task</h3><p>{_h(unit['listening_goal_en'])}</p>"
        f"<h3>10. Speaking Practice</h3><p>{_h(unit['speaking_goal_en'])}</p>"
        f"<h3>11. AI Tutor Drill</h3><p>{_h(unit['ai_tutor_goal_en'])}</p>"
        f"<h3>12. Checklist</h3><ul>{checklist_html}</ul>"
    )


def build_content_ar(unit: dict) -> str:
    """Produce the Arabic explanation block for a Lesson's content_ar."""
    examples_ar = "".join(
        f"<li>{_h(ar)}</li>"
        for _en, ar in unit.get("examples", [])
    ) or "<li><em>(يُعبأ لاحقًا)</em></li>"

    return (
        f"<h3>هدف الدرس</h3><p>{_h(unit['skill_ar'])}</p>"
        f"<h3>القاعدة الجديدة</h3><p>{_h(unit['new_language_ar'])}</p>"
        f"<h3>المفردات</h3><p>{_h(unit['vocabulary_ar'])}</p>"
        f"<h3>شرح القاعدة</h3><p>{_h(unit['grammar_ar'])}</p>"
        f"<h3>أمثلة مترجمة</h3><ul>{examples_ar}</ul>"
        f"<h3>هدف المحادثة</h3><p>{_h(unit['speaking_goal_ar'])}</p>"
        f"<h3>ملاحظة للطالب العربي</h3><p>{_h(unit['arabic_tip'])}</p>"
        f"<h3>تنبيه على خطأ شائع</h3><p>{_h(unit['common_mistake_ar'])}</p>"
        f"<h3>تدريب AI Tutor</h3><p>{_h(unit['ai_tutor_goal_ar'])}</p>"
    )


def build_image_prompts(unit: dict) -> list[tuple[str, str]]:
    """Return (prompt_type, prompt_text) pairs to seed for one Lesson."""
    return [
        ("cover", unit["image_idea"] or
         f"Lesson cover for '{unit['title_en']}' — flat Onlenco illustration, soft background, no DK trade dress, no text in image."),
        ("vocabulary",
         f"Vocabulary tile grid for '{unit['title_en']}': flat icons of {unit['vocabulary_en'][:140]}. No labels in image. Style: clean, single-colour pale background, two-pixel outlines."),
        ("grammar",
         f"Grammar visual for '{unit['title_en']}': simple diagram illustrating {unit['grammar_en'] or 'the new construction'}. No characters, abstract shapes only."),
        ("quiz",
         f"Quiz illustration for '{unit['title_en']}': minimal scene that supports {unit['quiz_goal_en']}. No text, no copyrighted characters."),
    ]


def build_audio_scripts(unit: dict) -> list[tuple[str, str, str]]:
    """Return (script_type, voice_style, script_text) triples for one Lesson."""
    examples_block = " ".join(en for en, _ar in unit.get("examples", []))
    dialogue_block = " ".join(f"{spk}: {line}" for spk, line in unit.get("dialogue", []))
    return [
        ("intro", "friendly_teacher",
         f"In this lesson, you will learn {unit['new_language_en']}. {unit['skill_en']} Let's begin."),
        ("vocabulary", "slow_beginner",
         f"Today's vocabulary: {unit['vocabulary_en']} Listen and repeat each word."),
        ("examples", "friendly_teacher",
         examples_block or "(examples populated after generation)"),
        ("dialogue", "dialogue",
         dialogue_block or "(dialogue populated after generation)"),
        ("listening", "slow_beginner",
         unit["listening_goal_en"] or "Listen carefully and complete the task."),
        ("speaking", "friendly_teacher",
         unit["speaking_goal_en"] or "Now it's your turn to speak. Record yourself and compare with the model."),
    ]


# Final integrity check at import time — keeps a typo from shipping.
def _validate_units() -> None:
    seen = set()
    for u in UNITS:
        assert u["n"] not in seen, f"Duplicate unit number: {u['n']}"
        seen.add(u["n"])
        assert 1 <= u["n"] <= 48
        assert u["cefr"] in ("A0", "A1")
        assert u["review_group"] in ("R1", "R2", "R3", "R4", "R5", "R6")
    assert seen == set(range(1, 49)), f"Missing units: {set(range(1, 49)) - seen}"


_validate_units()
